### PR TITLE
Black format

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Painting the ``conda-build`` with Black.

* Formatted the whole codebase using Black
* Modified the ``Travis`` CI to also run ``black --check``
* Add pre-commit hook as an optional tool to the developer to facilitate his life when submitting code to be black and flake8 compliant.
* Added Black's badged

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Regarding the blame, the developer can use the following command to "bypass" this commit:
```
git blame $BLACK_REV^ -- $FILE
```
As informed by @ambv in https://github.com/DistrictDataLabs/yellowbrick/issues/456#issuecomment-392884311

**Comment by marcelotrevisani** [comment]
It is missing ``black`` on the main channel. How do I add black to the channel?

**Comment by ocefpaf** [comment]
@msarahan b/c this PR touches all the code base I believe it will be need a strategy to merge it. Like: merge all other PRs that ar good to go, rebase this and coordinate a fast merge to avoid creating conflicts for new PRs.

While using adding black to an existing project is always painful I believe that the long term advantages are worth it.

**Comment by msarahan** [comment]
I am totally on board with this, but we can't currently dedicate the time to get this done. If one or both of you would like to be a maintainer, even if only long enough to get this done, we can make that happen. We have time to talk with you and support you, but we don't have time to do the usual PR CI babysitting that is necessary to push things over the line.

**Comment by marcelotrevisani** [comment]
> I am totally on board with this, but we can't currently dedicate the time to get this done. If one or both of you would like to be a maintainer, even if only long enough to get this done, we can make that happen. We have time to talk with you and support you, but we don't have time to do the usual PR CI babysitting that is necessary to push things over the line.

I have some experience with that, I think I can handle it. But would be good to have someone to review the modifications. Maybe @ocefpaf can review the modifications and also can help to move it forward (if he wants/has time for that of course).
:)

**Comment by marcelotrevisani** [comment]
I think that is ready to be integrated if we want to move forward to use ``black``.

``Git`` 2.23 supports ignore revisions file after we integrate this PR we might add a file with the revision of this PR
https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt

**Comment by marcelotrevisani** [comment]
The flake8 complain will be fixed with this PR #3729

**Comment by marcelotrevisani** [comment]
The following folders are not being formated:
```
      \.eggs
    | \.git    
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | docs
    | ci
    | news
    | utils
  | tests/test-recipes/metadata
```

**Comment by mingwandroid** [comment]
@marcelotrevisani I have a load of PRs incoming and this would break them. Can we defer this until perhaps just after the next CB release (or at least until my PRs get merged?)

I wouldn't normally mention it but this will break the mergeability of a load of commits.

Cheers!

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani I have a load of PRs incoming and this would break them. Can we defer this until perhaps just after the next CB release (or at least until my PRs get merged?)
> 
> I wouldn't normally mention it but this will break the mergeability of a load of commits.
> 
> Cheers!

Hi @mingwandroid , sure, no problem at all! It can wait. :)

**Comment by jezdez** [comment]
Closing again since this is out of scope of the project at the moment, while we're digging us out of a lot of tech-debt. To be clear, I'm a big fan of black and hope we'll adopt it eventually.

**Pull request closed without merging**
