### PR TITLE
[WIP] Avoid encoding/decoding on line-endings processing on patch files

### LINKED ISSUE #2032: Patch with non-ascii characters causes UnicodeDecodeError
I'm build a package for conda-forge on appveyor and it fails when applying a patch with non-ascii characters:

```
Downloading source to cache: ftfy-5.1.tar.gz
Downloading https://pypi.io/packages/source/f/ftfy/ftfy-5.1.tar.gz
Success
Applying patch: 'C:\\projects\\ftfy-feedstock\\recipe\\tests-fix-linesep.patch'
Traceback (most recent call last):
  File "C:\Miniconda35\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda35\lib\site-packages\conda_build\cli\main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "C:\Miniconda35\lib\site-packages\conda_build\cli\main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "C:\Miniconda35\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda35\lib\site-packages\conda_build\build.py", line 1510, in build_tree
    config=config)
  File "C:\Miniconda35\lib\site-packages\conda_build\build.py", line 1058, in build
    config=config)
  File "C:\Miniconda35\lib\site-packages\conda_build\render.py", line 86, in parse_or_try_download
    source.provide(metadata, config=config)
  File "C:\Miniconda35\lib\site-packages\conda_build\source.py", line 544, in provide
    apply_patch(src_dir, join(metadata.path, patch), config, git)
  File "C:\Miniconda35\lib\site-packages\conda_build\source.py", line 499, in apply_patch
    patch_args[-1] = _ensure_unix_line_endings(path)
  File "C:\Miniconda35\lib\site-packages\conda_build\source.py", line 420, in _ensure_unix_line_endings
    for line in inputfile:
  File "C:\Miniconda35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 331: character maps to <undefined>
Command exited with code 1
```

I tried to set the envvar `PYTHONIOENCODING=UTF-8` but had no success.

Full log: https://ci.appveyor.com/project/conda-forge/ftfy-feedstock/build/1.0.11/job/soe86qk54ln43gtd
Patch file: https://github.com/rolando-contrib/ftfy-feedstock/blob/fix-win-build/recipe/tests-fix-linesep.patch

### PR DESCRIPTION
**Pull request by rolando**
When a patch contains non-utf8 or when the system encoding doesn't match the file encoding the line endings processing fails because it attempts to decode the content.

Fixes #2032

### CODE REVIEW

**Comment by msarahan** [comment]
Excellent. I'm glad you have a better handle on this than me.  I'll wait for CI, but this looks fine at first glance.

**Comment by msarahan** [comment]
This seems to mess up patching on Windows.  I'm reasonably sure that it's my fault.  I need to be smarter about detecting the line endings of the source code somehow, and then dynamically determining how to coerce line endings from the patch to match.  I'll push fixes for that to this PR, if you don't mind.

**Comment by rolando** [comment]
@msarahan I haven't got time to look into why the other tests fail. Please go ahead.

**Comment by jakirkham** [comment]
Probably worth noting this fixes issue ( https://github.com/conda/conda-build/issues/1973 ) as well.

**Comment by msarahan** [comment]
Merging this.  Seems like it picked up an error that I let slip from another PR.  I'll sort out any other failures.  Thanks @rolando!

**Pull request merged**
