### PR TITLE
fix building when git is not installed

### PR DESCRIPTION
**Pull request by ilanschnell**
This simple PR fixes https://github.com/conda/conda-build/issues/647

### CODE REVIEW

**Comment by ilanschnell** [comment]
@kalefranz please review

**Comment by jasongrout** [comment]
As noted in https://github.com/conda/conda-build/issues/713#issuecomment-178235625, this change broke a lot of recipes that depended on git being automatically detected, and probably should be documented in the changelog as a breaking change requiring an update to meta.yaml files (e.g., `path: ... -> git_url: ...`. Also, this change breaks `python -m conda_build.environ` since we don't check to see if `m` is `None`.

**Comment by ilanschnell** [comment]
Sorry for the breakage.

**Comment by jakirkham** [comment]
Just so I understand what broke here, `path` could have been used to specify the a git URL before? Also, I don't think I have ever used `conda_build.environ` before what did this do before it stopped working?

**Comment by jasongrout** [comment]
When debugging, I saw the if statement at the bottom of the file, which
indicates it can be run separately. It looks like it will print out the
environment.

**Comment by jasongrout** [comment]
To be clear, I support the change. It prevents problems I've had in the
past with the auto guessing, like
https://github.com/conda/conda-build/issues/529.  It just caught us by
surprise when it broke our builds.

**Comment by frol** [comment]
<irony>Super change! I love it!</irony>

I have a number of internal recipes, which are cloned by Jenkins, so the ssh credentials for the repos are not available to make another clone on `conda build`, also, it is quite annoying to re-clone a huge project with a number of submodules on every build. `path` options worked just perfect and now it is gone... What is the recommended way of dealing with this kind of workflow?

P.S. The reason I hit by this "feature" only today is that I was using conda-build 1.18.1 because of the broken 1.18.2 release. Today, in a hope of that the bugs of 1.18.2 were solved, I moved on 1.20.0... and here I am.

**Pull request merged**
