### PR TITLE
Activate for test

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Please review @msarahan.

**Comment by msarahan** [comment]
This seems fine to me. I'm surprised that it's needed, though. It seems like we would have noticed the lack of activation before now? Activation is definitely necessary and this appears to be the right place. I just wonder if there is also somewhere deeper that is writing it, like in this function: https://github.com/conda/conda-build/pull/3515/commits/3da2b16a4b1204c9783811fe7062dd52b70d2bcb#diff-ac55d744935b1f37a3369258b88e8f1fR1970

**Comment by mingwandroid** [comment]
I am fixing the bug I introduced [here](https://github.com/conda/conda-build/commit/c03f5a067e98b0a6c2e5f932e168d51e966f8159)

I didn't consider changing the behaviour as something I wanted to be doing here.

**Comment by mingwandroid** [comment]
I assume there's no test coverage for this either. If you want me to add that, let me know.

**Pull request merged**
