### PR TITLE
pipbuild: don't check if package already exists

### LINKED ISSUE #390: conda pipbuild fails to fetch metadata for some packages
It appears that `conda pipbuild` fails when fetching metadata for some packages. For instance, here is an example with `six` below. Note after attempting to fetch metadata, it simply drops back to prompt.

    $ conda pipbuild six
    Package search: {'_pypi_ordering': 20, 'version': '1.9.0', 'name': 'six', 'summary': 'Python 2 and 3 compatibility utilities'}
    Fetching package metadata: ......
    $

### LINKED ISSUE #435: conda-pipbuild exists with no message if the package already exists
```
$ conda-pipbuild pbr
Package search: {'_pypi_ordering': False, 'version': '1.0.1', 'name': 'pbr', 'summary': 'Python Build Reasonableness'}
Fetching package metadata: ......
```
we should exit with something more informative.

### PR DESCRIPTION
**Pull request by hargup**
fixes #435
fixes #390

### CODE REVIEW

**Comment by hargup** [comment]
@asmeurer @ilanschnell

**Comment by hargup** [comment]
I don't think that checking if a package exists helps in anyway, because there are cases when a user (like me) would like the rebuild a package, maybe with a new version or with some other options like `--noarch_python`.

**Comment by asmeurer** [comment]
This has merge conflicts.

**Comment by hargup** [comment]
Fixed the merge conflicts.

**Pull request merged**
