### PR TITLE
add option nasty

### PR DESCRIPTION
**Pull request by looooo**
related to #1570

more work have to be done. This is only a first draft of what I would like to have.

This option should give the possibility to:

- run a build within an existing build dir (like --dirty)
- reuse old build (like --dirty)
- but update the source (this isn't working yet. There I need some help, how to implement this)

### CODE REVIEW

**Comment by looooo** [comment]
somehow [this](https://github.com/conda/conda-build/pull/1574/commits/b3c9cad61cfb1e125b8aad0e8187885ea5af5a12#diff-ba343c116f2df712f571a28c16577543L228) already prevents conda from pulling the source.

**Comment by msarahan** [comment]
@looooo thanks for this start.  I laughed about the title quite a bit.

I think a better option than repurposing the --dirty flag will be to create a new flag.  Perhaps ```--update-source-in-place``` or just ```--update-source```?   Maybe ```--reuse-build```?

Alternatively, we might be able to change the behavior of ```--dirty``` by passing some other flag - perhaps ```--force-download```.  This is already part of the API, but not a command line option, so it should be easy to add.

**Comment by looooo** [comment]
ok I have followed your suggestion.
specifying these --dirty and --force_download now produces this:

```
Traceback (most recent call last):
  File "/home/lo/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 261, in main
    execute(sys.argv[1:])
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 253, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/api.py", line 75, in build
    need_source_download=need_source_download, config=config)
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 1230, in build_tree
    config=recipe_config)
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 791, in build
    assert not need_source_download, "Source download failed.  Please investigate."
AssertionError: Source download failed.  Please investigate.
```

**Comment by msarahan** [comment]
I think you need more logic at https://github.com/conda/conda-build/pull/1574/commits/b2a83987800c9d03a15a37622638dc45e0cf5cb6#diff-a273b977a04f704063ec213a6230e203R84 - it is currently always going to skip the source when dirty is true.

**Comment by looooo** [comment]
I found a way to get things done with --dirty... So I think we can close this.

**Pull request closed without merging**
