### PR TITLE
patch: Automatically determine patch strip level

### PR DESCRIPTION
**Pull request by mingwandroid**
@msarahan, another one for you.

### CODE REVIEW

**Comment by msarahan** [comment]
LGTM.  I'd break the test up into at least 2 parts though:
  * determine patch level
  * apply patch

If it simplifies things to separate the setup stuff into either files to bundle, or a separate setup/teardown function, that would be nice too.

Let me know how much time you have to spend on this.

**Comment by mingwandroid** [comment]
I've not got much to be honest. This whole `patch.py` thing was a bit of a time-sink. For my setup I've switched to installing `m2-patch` in my conda root envs and it seems to be working well (albeit with a warning about CR (or is it LF, I can never remember!)).

**Comment by msarahan** [comment]
OK.  Merging this as-is.  Let's clean it up in some idle future moment.

**Comment by msarahan** [comment]
I'll wait on Travis, just in case - but it is pretty backed up right now.

**Comment by mingwandroid** [comment]
@msarahan I'm refreshing this now to address the flake8 problems, I've split the patch test too ..

**Comment by msarahan** [comment]
Thanks, Ray.  I've been meaning to submit a patch to this PR to do this, but you'll beat me to it.

**Comment by msarahan** [comment]
Thanks, Ray.  Merging.

**Comment by mingwandroid** [comment]
Cheers!

**Pull request merged**
