### PR TITLE
Add prelink_message files to the conda package

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Related to https://github.com/conda/conda/issues/10118

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
cc: @conda/conda-core

**Review by chenghlee — CHANGES_REQUESTED** [review]
Perhaps we should change the naming from `eula` to `prelink_message`? In the context of conda/conda#10118, EULAs will be a common, but not the only, use case for the feature.

**Comment by marcelotrevisani** [comment]
> Perhaps we should change the naming from `eula` to `prelink_message`? In the context of [conda/conda#10118](https://github.com/conda/conda/issues/10118), EULAs will be a common, but not the only, use case for the feature.

Sure, no worries! I will make this change tomorrow, thanks for reviewing the PR :)

**Comment by marcelotrevisani** [comment]
> Perhaps we should change the naming from `eula` to `prelink_message`? In the context of [conda/conda#10118](https://github.com/conda/conda/issues/10118), EULAs will be a common, but not the only, use case for the feature.

Sure, no worries! I will make this change tomorrow, thanks for reviewing the PR :)

**Comment by marcelotrevisani** [comment]
> Perhaps we should change the naming from `eula` to `prelink_message`? In the context of [conda/conda#10118](https://github.com/conda/conda/issues/10118), EULAs will be a common, but not the only, use case for the feature.

Done!

**Comment by marcelotrevisani** [comment]
@chenghlee @ocefpaf 
image

**Review by chenghlee — APPROVED** [review]
Code looks fine, but I/we need to figure out why the macOS CI checks are failing.

**Comment by marcelotrevisani** [comment]
> Code looks fine, but I/we need to figure out why the macOS CI checks are failing.

It was failing before, it is not related to this modification. But indeed it would be nice to take a look at it

**Pull request merged**
