### PR TITLE
override conda-build option with meta value if it exists

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@mingwandroid, this way, the value for `error_overlinking` can be overriden to be False

**Comment by mingwandroid** [comment]
There are 2 ways to enable it: `--error-overlinking --no-overdepending` or emit this to condarc:

```
conda_build:
  error_overlinking: true"
  error_overdepending: true"
```

Are they not enough? I was hoping to change the default to true for conda-build 4.

**Comment by isuruf** [comment]
I like this approach because it is per recipe instead of a global option.

**Comment by mingwandroid** [comment]
Sure. I tend to agree

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
