### PR TITLE
add creation of index.html to `conda index` command

### PR DESCRIPTION
**Pull request by kalefranz**
The index.html file is created when the `--channel-name` flag is passed
to the command.

@msarahan If there are existing tests for `conda index` that I can replicate or extend, just point them out to me and I'll be happy to augment this PR with tests.

**WARNING: This cannot (yet) be used on pkgs/free or pkgs/pro.  All hell will break loose if `conda index` is ran on those two channels right now.**  Please talk with Kale before doing that.

### CODE REVIEW

**Comment by goanpeca** [comment]
@kalefranz could you paste a screenshot of how it looks :-) ?

**Comment by kalefranz** [comment]
image

**Comment by goanpeca** [comment]
@kalefranz how about a date looking more like 

`2017-09-22 05:50:53`

**Comment by jjhelmus** [comment]
Should the index include links to `repodata.json` and `repodata.json.bz2`?

**Comment by kalefranz** [comment]
@jjhelmus Didn't realize that. Will push another commit.  They should also probably be listed at the top.

**Comment by kalefranz** [comment]
Screen shot for index.html with repodata.json listed.  About to push the change now.

image

**Comment by goanpeca** [comment]
@kalefranz whats with the date format?

**Comment by kalefranz** [comment]
Yeah, haha.  Was already on that.  Now with better timestamps :)

image

**Comment by kalefranz** [comment]
The template is based on what Ilan had already (it's just jinja2 now :party:).  If anyone wants to modify it in a future PR, go for it.  Adding the conda logo publicly available at https://conda.io/docs/_images/conda_logo.svg might be a nice touch.

**Comment by kalefranz** [comment]
Oh, one more thing... This PR modifies the repodata output of `conda index` to now leave the `mtime` field.  I actually think that's useful to have.

Want to call that out explicitly though, in case anybody objects.

**Comment by msarahan** [comment]
Does this depend on any conda PR?  There's quite a few errors: https://travis-ci.org/conda/conda-build/jobs/278826729#L1554

**Comment by kalefranz** [comment]
This PR currently has CI pinned to 4.3.27, not 4.3.x.  It shouldn't be merged with that still in place.

**Comment by msarahan** [comment]
Requested some small changes in https://github.com/kalefranz/conda-build/pull/2

If/when you merge that, I'd like to see how it behaves with conda 4.3.27.  After that, please rebase away 4.3.27, or add a commit to remove it if you prefer.

**Comment by msarahan** [comment]
Thanks.  Merging as result of 8a351fd coming out OK.

**Pull request merged**
