### PR TITLE
Conda 4.3 compatibility - fix

### LINKED ISSUE #1650: Conda 4.3 compatibility
Summary of causes for incompatibility with conda 4.3 at present.

1. Resolve class lost its "get_pkg" method: https://travis-ci.org/conda/conda-build/jobs/190827542#L1088
2. package_cache() has been neutered: https://travis-ci.org/conda/conda-build/jobs/190827542#L1155

Really, those look like the only major things.  They just kill lots of tests...  Oh, to have time to refactor the test suite...

CC @kalefranz

### LINKED ISSUE #1654: 'Resolve' object has no attribute 'get_pkgs'
Running with conda build 2.0.12 on conda 4.3.3, I see the following when running a basic conda build:

```
$ conda build .
BUILD START: jenkins-1.0.2-py27_0
updating index in: /Users/mahmoud/anaconda2/conda-bld/osx-64
updating index in: /Users/mahmoud/anaconda2/conda-bld/noarch

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0
    pip:        9.0.1-py27_1
    python:     2.7.13-0
    readline:   6.2-2
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3

Traceback (most recent call last):
  File "/Users/mahmoud/anaconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 255, in main
    execute(sys.argv[1:])
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 247, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 75, in build
    need_source_download=need_source_download, config=config)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1230, in build_tree
    config=recipe_config)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 758, in build
    create_env(config.build_prefix, specs, config=config)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 664, in create_env
    warn_on_old_conda_build(index=index)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 712, in warn_on_old_conda_build
    available_packages = get_conda_build_index_versions(index)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 690, in get_conda_build_index_versions
    pkgs = r.get_pkgs(MatchSpec('conda-build'))
AttributeError: 'Resolve' object has no attribute 'get_pkgs'
```

The recipe is pretty basic, generated by conda skeleton with almost no tweaks, [based on the PyPI Jenkins package](https://pypi.python.org/pypi/jenkins). I also tried it with canary conda build and got the same error.

### PR DESCRIPTION
**Pull request by msarahan**
fixes #1650 
fixes #1652
fixes #1654

### CODE REVIEW

**Comment by msarahan** [comment]
@kalefranz the one remaining issue I have locally is with test_catch_openssl_legacy_short_prefix_error (https://github.com/conda/conda-build/blob/master/tests/test_build.py#L110-L125)

It looks to me like conda is catching the error (SystemExit, probably), and swallowing it.  Conda-build is unable to catch it, and thus doesn't know that it needs to try a shorter prefix.  How do you want to fix this?

Output leading me to this conclusion:
```
Traceback (most recent call last):
  File "/Users/msarahan/code/conda-build/tests/test_build.py", line 128, in test_catch_openssl_legacy_short_prefix_error
    assert "Falling back to legacy prefix" in caplog.text()
AssertionError: assert 'Falling back to legacy prefix' in 'config.py                  405 INFO     --dirty flag not specified.  Removing build folder after successful build/test.\n\n'
 +  where 'config.py                  405 INFO     --dirty flag not specified.  Removing build folder after successful build/test.\n\n' = u'config.py                  405 INFO     --dirty flag not specified.  Removing build folder after successful build/test.\n\n'()
 +    where u'config.py                  405 INFO     --dirty flag not specified.  Removing build folder after successful build/test.\n\n' = <pytest_catchlog.CompatLogCaptureFixture object at 0x1138f3e50>.text
----------------------------------------------- Captured stdout call -----------------------------------------------
BUILD START: test_catch_openssl_legacy_short_prefix_error-1.0-py26_1
updating index in: /private/tmp/cb/test_catch_openssl_legacy_shor0/osx-64
updating index in: /private/tmp/cb/test_catch_openssl_legacy_shor0/noarch

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1
    pip:        7.1.0-py26_0
    python:     2.6.9-1
    readline:   6.2-2
    setuptools: 18.0.1-py26_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    zlib:       1.2.8-3

Package: test_catch_openssl_legacy_short_prefix_error-1.0-py26_1
source tree in: /private/tmp/cb/test_catch_openssl_legacy_shor0/test_catch_openssl_legacy_short_prefix_error_1484792036395/work
number of files: 1
Fixing permissions
Fixing permissions
Detected hard-coded path in text file binary-has-prefix
/private/tmp/cb/test_catch_openssl_legacy_shor0/osx-64/test_catch_openssl_legacy_short_prefix_error-1.0-py26_1.tar.bz2
updating index in: /private/tmp/cb/test_catch_openssl_legacy_shor0
updating index in: /private/tmp/cb/test_catch_openssl_legacy_shor0/noarch
updating index in: /private/tmp/cb/test_catch_openssl_legacy_shor0/osx-64
updating: test_catch_openssl_legacy_short_prefix_error-1.0-py26_1.tar.bz2
updating index in: /private/tmp/cb/test_catch_openssl_legacy_shor0
TEST START: test_catch_openssl_legacy_short_prefix_error-1.0-py26_1
Deleting work directory, /private/tmp/cb/test_catch_openssl_legacy_shor0/test_catch_openssl_legacy_short_prefix_error_1484792036395/work
updating index in: /private/tmp/cb/test_catch_openssl_legacy_shor0/osx-64
updating index in: /private/tmp/cb/test_catch_openssl_legacy_shor0/noarch

The following NEW packages will be INSTALLED:

    openssl:                                      1.0.1k-1
    pip:                                          7.1.0-py26_0
    python:                                       2.6.9-1
    readline:                                     6.2-2
    setuptools:                                   18.0.1-py26_0
    sqlite:                                       3.13.0-0
    test_catch_openssl_legacy_short_prefix_error: 1.0-py26_1    file:///private/tmp/cb/test_catch_openssl_legacy_shor0
    tk:                                           8.5.18-0
    zlib:                                         1.2.8-3

A-OK
TEST END: test_catch_openssl_legacy_short_prefix_error-1.0-py26_1
# Automatic uploading is disabled
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /private/tmp/cb/test_catch_openssl_legacy_shor0/osx-64/test_catch_openssl_legacy_short_prefix_error-1.0-py26_1.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

----------------------------------------------- Captured stderr call -----------------------------------------------
Error: PREFIX too long: 255 characters, but only 128 allowed

WARNING: conda-build appears to be out of date. You have version 2.0.11 but the
latest version is 2.1.1. Run

conda update -n root conda-build

to get the latest version.

+ python -c '
import os

prefix = os.environ['\''PREFIX'\'']
fn = os.path.join(prefix, '\''binary-has-prefix'\'')

with open(fn, '\''wb'\'') as f:
    f.write(prefix.encode('\''utf-8'\'') + b'\'''\'')
 '

WARNING: conda-build appears to be out of date. You have version 2.0.11 but the
latest version is 2.1.1. Run

conda update -n root conda-build

to get the latest version.

+ /bin/bash -x -e /private/tmp/cb/test_catch_openssl_legacy_shor0/test_catch_openssl_legacy_short_prefix_error_1484792036395/test_tmp/run_test.sh
+ echo A-OK
+ exit 0
INFO conda_build.config:__exit__(405): --dirty flag not specified.  Removing build folder after successful build/test.
```

I'm kind of inclined to just nuke this test.  It was much more important when more of our packages were short-prefix.  Now that we've had long-prefix for a while, especially with OpenSSL, I think we can just kill this test and not deal with this behavior.

**Comment by kalefranz** [comment]
> It looks to me like conda is catching the error (SystemExit, probably), and swallowing it.

Can you point me to where, in the conda-build code, you have the machinery built to catch that SystemExit error?  I'll take it from there and figure out if it's a different error that you need to catch or what else is going on...

**Comment by kalefranz** [comment]
> I'm kind of inclined to just nuke this test. It was much more important when more of our packages were short-prefix. Now that we've had long-prefix for a while, especially with OpenSSL, I think we can just kill this test and not deal with this behavior.

Or that's fine too if you want.  Wouldn't hurt for me to spend 10 minutes on it though if there's an easy fix somewhere...

**Comment by msarahan** [comment]
https://github.com/conda/conda-build/blob/master/conda_build/build.py#L680-L701

The error shows up in the output, as you can see above, but it seems the exception itself gets swallowed rather than reraised or translated into a CondaError (catching the CondaError is part of this PR at https://github.com/conda/conda-build/pull/1667/files#diff-ac55d744935b1f37a3369258b88e8f1fR686 ).

**Comment by kalefranz** [comment]
For test_catch_openssl_legacy_shor, the `except` line actually gets triggered because of `LinkError` in conda 4.2, so looking at `PaddingError` was misdirection for us.

Now looking into why conda isn't raising LinkError.

**Comment by kalefranz** [comment]
So https://github.com/conda/conda-build/blob/master/conda_build/build.py#L682

    'post-link failed for: openssl' in str(exc) or

has changed to

   'post-link failed for: defaults::openssl' in str(exc) or

This found a legitimate bug.  But now I'm not quite sure how you want to handle that part...

**Comment by kalefranz** [comment]
Except for ^^^, which I guess will require some type of change in conda-build (even if it's removing the test), the *real* fix to the problem that was occurring is at https://github.com/conda/conda/pull/4382

**Comment by msarahan** [comment]
OMG!  That's a green conda 4.3 on the latest Travis result!  Quick! merge it!

**Comment by kalefranz** [comment]
As soon as we get a single "all green" for conda with conda-build, I'll be removing the `||` part of https://github.com/conda/conda/blob/4.3.6/utils/travis-run-script.sh#L58 that let's the build show green even if a few tests fail.

**Pull request merged**
