### PR TITLE
skeleton (cran): Switch cran url to mran. This syncs it with ./conda_…

### PR DESCRIPTION
**Pull request by mingwandroid**
…build/variants.py

### CODE REVIEW

**Comment by msarahan** [comment]
This is fine with me.  @jdblischak you seem to have an interest in R stuff.  Do you have strong opinions here?  @mingwandroid believes that mran is a better choice here because it is more reproducible.  We have had odd issues where a skeleton came from cran, but wasn't available on mran.  We think that will go away as long as we keep these two in sync (the CLI arg default here, and the value in the default variant config.)

**Comment by jdblischak** [comment]
Well this explains why I just having trouble testing my recent changes to conda-build. I was confused why the skeleton was pulling from CRAN but then `conda build` was trying (unsuccessfully) to find that version on the MRAN January snapshot.

>  Do you have strong opinions here?

I fear that I might. I agree that MRAN is more reproducible, but I think R users are going to be surprised when the default behavior of `conda skeleton cran` is to install the package version from potentially months ago.

Some follow-up questions:
1. Would it be possible to make this more dynamic? i.e. instead of pinning the default to the 2018-01-01 snapshot, it would use the most recent daily snapshot.
1. Can you link me to past discussions of this issue? I'm sure you've thought a lot about it, so it would help to learn more about the motivation.
1. How often are you planning on changing the MRAN URL? With every conda-build release or some set time interval?

**Comment by mingwandroid** [comment]
If you want to implement search for latest snapshot then please go ahead, but I'd request that it's done according to the R-base release date rather than the current date.

Otherwise we can go back to CRAN and I can pass the options on the command line and via conda-build's -m option.

**Comment by isuruf** [comment]
How about `{{ cran_mirror }}` instead and we can override it in `conda_build_config.yaml`?

**Comment by msarahan** [comment]
@isuruf that's already there.

https://github.com/conda/conda-build/blob/master/conda_build/skeletons/cran.py#L851
https://github.com/conda/conda-build/blob/master/conda_build/variants.py#L36

This needs to respect it as a default, though:
https://github.com/conda/conda-build/blob/master/conda_build/skeletons/cran.py#L307

**Comment by mingwandroid** [comment]
(but FTR I won't be making any further PRs to change this, see my 'better things' statement).

**Comment by msarahan** [comment]
Superseded by #2836 which makes the default be cran.  We'll work separately on how to make life easier for Ray so that he doesn't have to always remember to pass that ``-m cbc.yaml`` flag.

**Pull request closed without merging**
