### PR TITLE
Use extra R_ARGS

### PR DESCRIPTION
**Pull request by isuruf**
helps with cross compiling

### CODE REVIEW

**Comment by isuruf** [comment]
@mingwandroid, this is ready

**Comment by mingwandroid** [comment]
I rebased this @isuruf, hope you do not mind!

**Comment by isuruf** [comment]
Thanks

**Comment by mingwandroid** [comment]
Oops, thanks

**Comment by mingwandroid** [comment]
Thanks @isuruf!

**Pull request merged**
