### PR TITLE
Delay warning about numpy being unpinned until actually needed.

### PR DESCRIPTION
**Pull request by anntzer**
Closes https://github.com/conda/conda-build/issues/3170.

### CODE REVIEW

**Comment by anntzer** [comment]
As in https://github.com/conda/conda-build/pull/3863, I already have signed the CLA on Jan 31st, 2020.

**Comment by jjhelmus** [comment]
@cla-bot check

**Comment by jjhelmus** [comment]
> As in #3863, I already have signed the CLA on Jan 31st, 2020.

Sorry about that, the process to add signers is manual.  I've added you to the list.

**Comment by mingwandroid** [comment]
Closing to retrigger CI

**Comment by anntzer** [comment]
Kindly bumping again.

**Comment by anntzer** [comment]
I am no longer regularly using conda-build and thus have little interest in pushing this patch further.  Feel free to pick it up.

**Pull request closed without merging**
