### PR TITLE
Activate in build scripts, rather than trying to have Python manage env

### LINKED ISSUE #1040: all builds fail on Fedora due to environment corruption
On Fedora 22, conda build fails when trying to run build.sh, like this:

```
/bin/bash: scl: line 1: syntax error: unexpected end of file
Command failed: /bin/bash -x -e /home/hp/checkout/conda-project/conda.recipe/build.sh
```

The issue appears to be that the environment variable called `BASH_FUNC_scl()` (the parens are in the env var name!) gets its value corrupted. `BASH_FUNC_module()` also exists and has the same issue.

Here is the output of printenv:
```
BASH_FUNC_scl()=() {  local CMD=$1;
 if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
```

If I add debug prints to conda_build/build.py, the value of `BASH_FUNC_scl()` is `() {  local CMD`

The code in environ.py doesn't look prepared for newline or "=" to be in the value of an env var, but in this case both of them are.

On Linux a possible fix would be to use `env --null` then `split('\x00')` instead of newline, and then only special-case the _first_ '=' (treat any subsequent '=' as part of the value), maybe using `var.split('=', 1)`.  However, I wouldn't be surprised if BSD lacks `--null`. Then again, BSD probably doesn't set env vars to stuff containing '=' and newline.

### PR DESCRIPTION
**Pull request by msarahan**
The gist of this is that trying to have Python record the environment variable changes from activation was prone to all sorts of variable corruption.  Rather than deal with that, we just call the activation scripts in the build scripts (by prepending this activation bit into a copy of the build script)

Fixes #1040 #1042 

cc @havocp

### CODE REVIEW

**Comment by msarahan** [comment]
wow! first all-green appveyor in a long time!  Merging.

**Comment by marscher** [comment]
I'm not 100% sure if this PR introduced this new failure on Windows (Appveyor):
https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/1.0.930/job/iumjxgiw762xn0cu#L258

Somehow the variables exported by Visual Studios vcsvars.bat script got omitted... It seems it only affects 64bit systems:

https://ci.appveyor.com/project/marscher/pyemma/build/1.0.2097

**Comment by msarahan** [comment]
Interesting. It passed our tests locally. Must be something with the alternative compilers. 

I know the change involved and will revert it until I fix it.

**Comment by marscher** [comment]
We're using VS2015 on Appveyor if that helps. My guess is that is has 
something to do with the way conda-build treats env variables.

**Comment by msarahan** [comment]
We tried to use distutils for finding and getting the compiler environment
variables. It would make things much simpler, and we hoped more reliable,
because it uses the registry to find installations.

I think it's still a good idea, just not ready for prime time.

**Comment by marscher** [comment]
yeah, sounds like a neat idea. Maybe setuptools is better suited (since 
it is modern) and also available in every conda installation?

**Pull request merged**
