### PR TITLE
force target_platform as used when not noarch

### PR DESCRIPTION
**Pull request by isuruf**
Follow up to https://github.com/conda/conda-build/pull/4065

### CODE REVIEW

**Comment by isuruf** [comment]
cc @beckermr

**Comment by beckermr** [comment]
Thank you for following up on this. For my own knowledge, what problem is this solving?

**Comment by mingwandroid** [comment]
Thanks again!

**Comment by isuruf** [comment]
@beckermr, in the earlier PR, I made a change to not remove `target_platform` from hash contents, but it never appeared in the first place.

**Pull request merged**
