### PR TITLE
Remove transient dependency on conda vendored six.py, and py2 code.

### PR DESCRIPTION
**Pull request by erykoff**
### Description

Following https://github.com/conda/conda/pull/11979, I thought it was worthwhile to remove the transient dependency on conda's vendored six.py.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by travishathaway** [comment]
Hi @erykoff,

We really appreciate this pull request and the fact that you are helping us tame some technical debt 💪 . Could you please add a news item like you already did for your other pull request in conda? (https://github.com/conda/conda/pull/11979)

Thank you.

**Comment by travishathaway** [comment]
Also, once that is done and assuming this passes all the tests, I will be happy to give my approval on it ✅.

**Comment by erykoff** [comment]
Thanks!  I added the news fragment, but I don't have the power to make the tests run.  (Also the previous workflow tests did fail with a strange problem on one of the linux parallel tests).

**Comment by erykoff** [comment]
Failure on Windows 3.9, canary, parallel with "permission denied"?

**Comment by travishathaway** [comment]
@erykoff re-running this test. Sometimes these things fail randomly.

**Comment by erykoff** [comment]
It worked!

**Review by travishathaway — APPROVED** [review]

**Pull request merged**
