### PR TITLE
don't assume 'extras_require' is present in pkginfo dict

### LINKED ISSUE #4354: KeyError: 'extras_require' while running conda skeleton
Hi, 

I was trying to prepare a recipe for my pypi package by running conda skeleton and got the following traceback (pasted below). To test if the problem was with my package, I tried running the conda skeleton pypi click command from the tutorial, and got exactly the same error.

```
Traceback (most recent call last):
  File "/Users/kevinkuchinski/miniconda3/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_skeleton.py", line 64, in main
    return execute(sys.argv[1:])
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_skeleton.py", line 59, in execute
    api.skeletonize(args.packages, args.repo, output_dir=args.output_dir, recursive=args.recursive,
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/api.py", line 276, in skeletonize
    skeleton_return = module.skeletonize(packages, output_dir=output_dir, version=version,
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 315, in skeletonize
    get_package_metadata(package, d, data, output_dir, python_version,
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 752, in get_package_metadata
    requires = get_requirements(package, pkginfo, all_extras=all_extras)
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 1115, in get_requirements
    for extra in pkginfo['extras_require']:
KeyError: 'extras_require'
```

### PR DESCRIPTION
**Pull request by wimglenn**
closes #4354

### CODE REVIEW

**Comment by beeankha** [comment]
Hi @wimglenn , could you please rebase this PR against the current `master` branch so that all CI tests (which are now in GitHub Actions) can run as they currently are? Also, did you sign the [Conda Contributor License Agreement](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement)?

**Comment by wimglenn** [comment]
@beeankha  I have rebased against master. Yes I signed the CLA nine days ago, but the bots don't seem to have noticed..

**Comment by beeankha** [comment]
@anaconda-issue-bot check

**Comment by beeankha** [comment]
Hi @wimglenn , it looks like the CI tests are relying on the changes that are happening in [this PR](https://github.com/conda/conda-build/pull/4412) before they can run properly here. Sorry for the delay, we're actively working on those tests currently and I'll let you know as soon as it's time to rebase again!

**Comment by jezdez** [comment]
I've left a larger comment in https://github.com/conda/conda-build/pull/4412#issuecomment-1098972719 that I think may point to a bigger problem with the way package data is retrieved.

**Comment by wimglenn** [comment]
Closing in favor of https://github.com/conda/conda-build/pull/4434

**Pull request closed without merging**
