### PR TITLE
Added HG_* variables to environ when build

### PR DESCRIPTION
**Pull request by pigmej**
Added:

``HG_BRANCH`` - current branch
``HG_NUM_ID`` - commit num id
``HG_LATEST_TAG_DISTANCE`` commit distance from latest known tag (possibly follows ``GIT_DESCRIBE_NUMBER`` logic)
``HG_SHORT_ID`` - commit short id
``HG_BUILD_STR`` - similar to ``GIT_BUILD_STR`` so NUM + SHORT joined with `_`

Allows to create meta.yaml like:

```
package:
  name: package_name
  version: {{ environ.get('HG_LATEST_TAG', "current") }}

build:
  number: {{ environ.get('HG_NUM_ID', 0) }}

  string: {{ environ.get('HG_BUILD_STR', '') }}

source:
  hg_url: /tmp/repo_path

```

Idea at first reported by me there: https://github.com/conda/conda/issues/916

### CODE REVIEW

**Comment by tacaswell** [comment]
@pigmej Any chance of reviving this?

**Comment by pigmej** [comment]
@tacaswell I'm very busy last time. But afair this generally works fine. (tests missing, probably corner cases missing)

**Comment by pigmej** [comment]
@asmeurer how the test code should look like ? Git recipe does not test this variables.

**Comment by groutr** [comment]
Is this PR still alive?

**Comment by msarahan** [comment]
Sorry this has been abandoned so often, @pigmej.  I'd like to merge it.  Can you resolve the conflicts, or would you prefer that I do so?

**Comment by msarahan** [comment]
I will be updating this to bring it up to date for the conda-build 2.0 release.  @pigmej please let me know if you want any further involvement here.

**Comment by msarahan** [comment]
Superseded by #1234.  Closing.

**Comment by pigmej** [comment]
@msarahan I remember that there were some drawbacks of that but I don't remember right now ;( Sorry, it was quite long time ago ;/

**Comment by msarahan** [comment]
No worries @pigmej - we'll see what happens.  It's a step in the right direction, no matter what.

**Pull request closed without merging**
