### PR TITLE
ENH handle symlinks in symlinks

### LINKED ISSUE #4178: Conda build of symlink fails since 5f46fdd06ebb19a69a2a0b779ac40fbc6772db32
Build failed due to commit https://github.com/conda/conda-build/commit/5f46fdd06ebb19a69a2a0b779ac40fbc6772db32#

### Actual Behavior
Build is aborted with: "TODO :: Nested symlinks not handled yet".

### Expected Behavior
Build should pass as it used to be prior to last update of conda-build.

### Steps to Reproduce
Build directory that contains symlink to symlink to symlink of file.

##### `Output of conda info`
Not relevant - it's conda 4.8.2

### PR DESCRIPTION
**Pull request by beckermr**
This PR closes #4178 by recusively parsing symlinks.

### CODE REVIEW

**Comment by beckermr** [comment]
cc @chenghlee @mingwandroid

**Comment by mingwandroid** [comment]
Thanks @beckermr! Can you add a news entry? Then I will get a new build done ASAP.

**Comment by beckermr** [comment]
Done!

**Comment by mingwandroid** [comment]
Thank you so much @beckermr! I have one other PR to merge and then I will tag this.

**Pull request merged**
