### PR TITLE
Cran updates

### PR DESCRIPTION
**Pull request by mingwandroid**
@groutr, @ilanschnell, @kalefranz please review. I've left the larger Windows/Unix unification change out until these are dealt with.

### CODE REVIEW

**Comment by groutr** [comment]
LGTM

**Comment by mingwandroid** [comment]
Thanks @groutr, merging.

**Comment by groutr** [comment]
Spoke too soon.  With Python 2.7 get:
```
Traceback (most recent call last):
  File "...../miniconda/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "...../conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "...../conda-build/conda_build/main_skeleton.py", line 298, in main
    args_func(args, p)
  File "...../conda-build/conda_build/main_build.py", line 493, in args_func
    args.func(args, p)
  File "...../conda-build/conda_build/main_skeleton.py", line 317, in execute
    cran.main(args, parser)
  File "/Users/rgrout/continuum/projects/conda-build/conda_build/cran.py", line 480, in main
    if d['license'].contains('GPL (>= 2)') or d['license'] == 'GPL':
AttributeError: 'unicode' object has no attribute 'contains'
```

**Comment by mingwandroid** [comment]
Not merging :-)

**Comment by groutr** [comment]
Strings don't have a `contains` method.  You would need to do `'GPL (>=2)' in d['license']` or `d['license'].find('GPL (>=2)') > -1`

**Comment by msarahan** [comment]
with the former being preferred "pythonic" syntax

**Comment by mingwandroid** [comment]
Ok, merging this now. Tested on Python 2.7.

**Pull request merged**
