### PR TITLE
Remove duplicate `extract_package_and_build_text` call

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

Looking to see just how much of a speedup we get by removing this redundant line.

Extracted from:
- https://github.com/conda/conda-build/pull/5225
- https://github.com/conda/conda-build/pull/5237
- https://github.com/conda/conda-build/pull/5248

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

### CODE REVIEW

**Comment by kenodegard** [comment]
FYI @mbargull

**Comment by mbargull** [comment]
Thanks, I wondered too and wanted to do the same, just didn't get to it yet :).
I've pushed the other commit I was interested in (somewhat) isolation.

**Comment by mbargull** [comment]
> |  |  |  |  |  |
> | --------- | ----------------------- | ------------------- | ------ | --- |
> | `test_pin_subpackage_benchmark` | 122.9 s | 97 s | +26.64% | `build_id` |
> | `test_pin_subpackage_benchmark` | 122.9 s | 90.9 s | +35.22% | `build_id` <br /> `get_output_dicts_from_metadata` |
> | `test_pin_subpackage_benchmark` | 122.9 s | 83.8 s | +46.52% | `build_id` <br /> `get_output_dicts_from_metadata` <br /> `_filter_recipe_text` |

It's nice to see that these innocuous changes would yield considerable improvements already.

> |  |  |  |  |  |
> | --------- | ----------------------- | ------------------- | ------ | --- |
> | `test_pin_subpackage_benchmark` | 122.8 s | 73.5 s | +67.07% | `build_id` <br /> `get_output_dicts_from_metadata` <br /> `_filter_recipe_text` <br /> `_split_line_selector`|
> | `test_pin_subpackage_benchmark` | 122.8 s | 71.4 s | +72.06% | `build_id` <br /> `get_output_dicts_from_metadata` <br /> `_filter_recipe_text` <br /> `_split_line_selector` <br /> `select_lines`/`selector_cache`|
> | `test_pin_subpackage_benchmark` | 122.8 s | 73.7 s | +66.55% | `build_id` <br /> `get_output_dicts_from_metadata` <br /> `_filter_recipe_text` <br /> `select_lines`/namespace hash |

As hoped for in https://github.com/conda/conda-build/pull/5237#issuecomment-2008993026 , your approach offers at least a much improvements as my more complicated bolted-on version!
It's also nice to see what part contributes the most improvement in the benchmark, i.e., as expected, factoring out `_split_line_selector` has the most impact.

> |  |  |  |  |  |
> | --------- | ----------------------- | ------------------- | ------ | --- |
> | `test_pin_subpackage_benchmark` | 122.8 s | 71.4 s | +72.07% | `build_id` <br /> `get_output_dicts_from_metadata` <br /> `_filter_recipe_text` <br /> `_split_line_selector` <br /> `select_lines`/`selector_cache` <br /> regex shortcut |

This was just to confirm that any impact (if at all) of these micro "only-`re.match`/`re.search`-if-needed" optimizations would not be reflected in the current benchmarks.
The test cases carry no script files and the `meta.yaml` (or lines therein) might be too small for `sel_pat.match(line)` to matter; plus, due to the memoization the latter might not make much of difference anymore anyway (which would be the desired outcome, of course!).

**Comment by kenodegard** [comment]
@mbargull thanks for doing this! should we split each of the commits into separate PRs now?

**Comment by beckermr** [comment]
What can I do to get these changes moving towards being included in the next conda-build release?

**Comment by kenodegard** [comment]
All of these improvements have been split off into separate PRs for easier review. Reverting this PR to the first commit.

**Review by beckermr — APPROVED** [review]

**Pull request merged**
