### PR TITLE
Update path logic to avoid Windows path sensitivity

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

`test_convert` in `tests/test_cli.py` has become particularly flaky on Windows recently (updates to the Windows runners perhaps?). This is an attempt to adjust the code to avoid this flakiness.

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

### CODE REVIEW

**Review by chenghlee — DISMISSED** [review]

**Comment by dholth** [comment]
Why does it need to rename source dir to dest dir (different case?) That is the strange thing about this code.

Maybe it could rename source dir to intermediate-dir, and then rename to source dir (different case)

**Comment by kenodegard** [comment]
@dholth 🤷🏼‍♂️ renaming src to dst is an atomic operation?

based on the [error message](https://github.com/conda/conda-build/actions/runs/3388870367/jobs/5633340193#step:11:1176) I don't think an intermediate dir would make a difference?

**Comment by dholth** [comment]
Considering the possibility that renaming Lib to lib is not allowed because Lib already exists.

Directory or file renames are atomic.

**Comment by dholth** [comment]
@kenodegard I'll walk across the room to my Windows machine and try this out.

**Comment by kenodegard** [comment]
Lol the test is still flaky, see https://github.com/conda/conda-build/actions/runs/3395410223/jobs/5645381714#step:11:1193

**Pull request merged**
