### PR TITLE
fix invalid option to gcc

### PR DESCRIPTION
**Pull request by groutr**
```
cc1: error: unrecognized command line option "-m"
```

### CODE REVIEW

**Comment by mingwandroid** [comment]
LGTM

**Comment by msarahan** [comment]
wow, how did this ever work before?  What was I smoking?

**Comment by groutr** [comment]
@msarahan My guess is you weren't building 32bit binaries.

**Comment by groutr** [comment]
@msarahan @kalefranz can we merge this, please?

**Comment by msarahan** [comment]
thanks @groutr

**Pull request merged**
