### PR TITLE
fix symlinks to folders in packaging

### LINKED ISSUE #1769: Symbolic link folders don't work anymore
A symbolic link to a folder worked fine in conda-build 2.1.4, but it's not in conda-build 2.1.5 on osx (linux works fine).

conda-build 2.1.5 log
https://travis-ci.org/conda-forge/gap-feedstock/builds/204615074

conda-build 2.1.4 log
https://travis-ci.org/conda-forge/gap-feedstock/builds/200925407

### PR DESCRIPTION
**Pull request by msarahan**
Note: for conda 4.3, this requires the fix at https://github.com/conda/conda/pull/4759

This works as-is for conda 4.2.

Fixes #1769

### CODE REVIEW

**Comment by msarahan** [comment]
Travis?  Can you hear me?  Please build my PR.

**Comment by isuruf** [comment]
@msarahan, I checked the latest release 2.1.7, and the symlinks folders are still broken

**Comment by msarahan** [comment]
@isuruf There's a better test on master: https://github.com/conda/conda-build/tree/master/tests/test-recipes/metadata/symlinks

If you want to put up a PR to backport that to 2.1.x, I'd appreciate it and it would get done faster.

**Comment by isuruf** [comment]
Ah, didn't realize that this was only in master. I'll send a PR

**Comment by msarahan** [comment]
Yes, I didn't either.  I'm having a very hard time keeping both in sync.  Sorry.

**Pull request merged**
