### PR TITLE
Re-evaluate prefix when need to use 80 char version

### PR DESCRIPTION
**Pull request by mingwandroid**
Hi @msarahan, I ran into this just now.

### CODE REVIEW

**Comment by msarahan** [comment]
doh.  That's a really dumb one.  Thanks for the fix.  I think it might be cleaner to pass config.build_prefix in the function call directly, though.  Want to change to that, or want me to do it?

**Comment by mingwandroid** [comment]
Done.

**Comment by mingwandroid** [comment]
.. and actually done :-)

**Comment by msarahan** [comment]
Thanks @mingwandroid - good catch here.

**Pull request merged**
