### PR TITLE
Added path_ignore to meta.yaml to skip copying some source files

### PR DESCRIPTION
**Pull request by dan-blanchard**
This was my quick attempt at updating #301 to resolve merge conflicts. I must admit I haven't really tested it out. Just wanted to see what I could do in a few minutes. :)

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks @dan-blanchard - do you mind adding some tests?  Ones that cover your use case, at least?

**Comment by aldanor** [comment]
Is anyone still on it?

**Comment by msarahan** [comment]
I'm not clear what the use case is here. Does the multiple output feature
with it's customizable install script fill the same niche? If not, what is
the new functionality you need?

**Comment by msarahan** [comment]
Closing as inactive.  Happy to reopen if anyone wants to pick this one up.  You'll need to start by answering my questions above about why you need this.

**Pull request closed without merging**
