### PR TITLE
Refactor conda_build.build.get_all_replacements

### PR DESCRIPTION
**Pull request by njalerikson**
Refactor to make code readable and to remove duplicate logic. Also removed what appears to be debugging print statements that are no longer in use.

### CODE REVIEW

**Comment by mingwandroid** [comment]
The debugging code is there because I suspect there is still a bug in here .. I'd like to defer merging this one or else I'll need to add debugging back to it, which isn't too bad..

**Comment by njalerikson** [comment]
Yeah, that's what I was suspecting when I saw how new the code was, no hard feelings if you reject this then :)

**Comment by mingwandroid** [comment]
It's no problem, I appreciate the help and will give this a proper review when I can.

**Comment by mingwandroid** [comment]
It is still plenty debuggable like this, thanks @njalerikson

**Pull request merged**
