### PR TITLE
ENH check all sysroot locations for DSOs

### PR DESCRIPTION
**Pull request by beckermr**
This PR changes the DSO checking code to examine all sysroots for potential DSOs when trying to detect missing DSOs in the post-build stage. 

We (@isuruf and myself), found that when we have a symlink to the sysroot in the build env and we refer to a DSO by its symlinked location, conda build thinks it's missing because it only checks one spot. 

The fact that it only checks one has been in the code since its start in these commits

 - https://github.com/conda/conda-build/commit/b888a853f55306d4eacd67082f3fbd7f33dbc965
 - https://github.com/conda/conda-build/commit/1b2b6337e07c59cd04c2ad5cf6bb4921b416a811

IDK why it only checks one. @mingwandroid should comment on that.

### CODE REVIEW

**Comment by beckermr** [comment]
cc @jjhelmus

**Comment by beckermr** [comment]
If this change is accepted, I'd very much like it to make the next release.

**Comment by beckermr** [comment]
Also, we need this as part of shipping cos7 on conda-forge.

**Comment by beckermr** [comment]
Bump here everyone.

**Comment by beckermr** [comment]
another bump here

**Comment by beckermr** [comment]
bump again on this

cc @mingwandroid @jjhelmus

**Comment by mingwandroid** [comment]
Should we do a rebuild of all cos6 cdts with this fix? And host them on CF? I'm happy with that but will also upload them to defaults.

**Comment by beckermr** [comment]
Yes this is my plan.

**Comment by beckermr** [comment]
Shall we merge @mingwandroid ?

**Comment by beckermr** [comment]
bump here again on merging

**Comment by mingwandroid** [comment]
Thanks @beckermr!

**Comment by beckermr** [comment]
You closed it but didn't merge it @mingwandroid. :)

**Comment by beckermr** [comment]
Bump here @mingwandroid @jjhelmus this was accidentally closed instead of merged. Can we please reopen and merge it?

**Comment by beckermr** [comment]
Bump here @mingwandroid @jjhelmus this was accidentally closed instead of merged. Can we please reopen and merge it?

**Comment by beckermr** [comment]
Thanks @marcelotrevisani! Can you please merge this one?

cc @jjhelmus @mingwandroid

**Comment by marcelotrevisani** [comment]
I would be more comfortable if you create a test to cover this scenario.
Could you please add a test for it?

**Comment by beckermr** [comment]
@mingwandroid was happy to merge without. I’ve tested the code live. 

Making a test for this is pretty hard as id need a package to build, link to some dso and then insert two sysroot paths in the env to find the dso in.

**Comment by beckermr** [comment]
Bump here again. Tests for this edge case are quite difficult. I’d like to merge without them. 

Can we please merge this?

**Comment by beckermr** [comment]
bump here again @jjhelmus @mingwandroid

**Comment by beckermr** [comment]
Ugh now there are conflicts

**Comment by mingwandroid** [comment]
Oops, sorry!

**Comment by beckermr** [comment]
Thanks!

**Pull request merged**
