### PR TITLE
Check for dash in text with variants

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks.  This looks fine to me.  Is there a test we can add for this?

I think this is meant to fix the problem where a variant key should have - replaced with _, but that won't be the case for the dependency name, right?  So something like

```
r_base:
  - 3.4.3
```

in CBC.yaml and

```
requirements:
  host:
    - r-base
```

in meta.yaml would do the wrong thing without this PR?

**Comment by mbargull** [comment]
Yes, that's the failing pattern exactly. @msarahan, would you want to a separate test case for this or is it fine to add this to `tests.test_variants.test_get_used_loop_vars`? I.e.:

`tests/test_variants.py` in `test_get_used_loop_vars`:
```diff
-assert m.get_used_vars() == {'python', 'some_package', 'zlib'}
+assert m.get_used_vars() == {'python', 'some_package', 'zlib', `pthread-stubs`}
```
`tests/test-recipes/variants/19_used_variables/conda_build_config.yaml`:
```diff
 zlib:
   - 1.2.11
+pthread_stubs:
+  - 0.3
```
`tests/test-recipes/variants/19_used_variables/meta.yaml`:
```diff
     # an implicit usage other than python
     - zlib
+    # an implicit usage containing a dash
+    - pthread-stubs
```
(Why `pthread-stubs`? => name includes `-`, package is small, no (apart from `vc` on Windows) dependencies, available on all platforms and `defaults`/`conda-forge`.
The test currently uses `finalize=False, bypass_env_check=True`, so this doesn't really matter, but could be useful if the tests change, I guess...)

**Comment by mbargull** [comment]
\[OT: Whooho! I made an edit to the previous choice and GitHub told me that from now on the edit history can be seen by clicking on `edited`. Nice!\]

**Comment by msarahan** [comment]
@mbargull adding to the existing test is fine.  Please go ahead if you have time.

**Comment by isuruf** [comment]
ping

**Comment by msarahan** [comment]
Thanks for the ping.  All failures look unrelated here.  Thanks @isuruf and @mbargull for the improvement here.

**Comment by isuruf** [comment]
Thanks

**Comment by isuruf** [comment]
@msarahan, do you mind making a new release with this patch? Waiting for this in conda-smithy.

**Comment by isuruf** [comment]
This still fails in python 2.7. https://travis-ci.org/conda/conda-build/jobs/391283327#L1710
Works fine in python 3.6

**Comment by mbargull** [comment]
> This still fails in python 2.7. https://travis-ci.org/conda/conda-build/jobs/391283327#L1710

Well, F me! https://docs.python.org/3/library/re.html#re.escape
> Changed in version 3.3: The '_' character is no longer escaped.

I'll submit a fix right away.

**Pull request merged**
