### PR TITLE
Rever

### PR DESCRIPTION
**Pull request by scopatz**
This PR adds support for releasing conda-build with rever.  Currently, it needs https://github.com/regro/rever/pull/169, but after that is merged I'll cut a release. After this, you'll be able to cut a new release with:

```sh
$ rever 3.17.7
```

Some notes about this configuration though:

* For everyone who has participated in a release, their github names will need to be added to the `.authors.yml` file. I have done this for the five or so folks (@msarahan, myself, etc) who have already contributed to this release. Docs for this can be found [here](https://regro.github.io/rever-docs/authorship.html#metadata-format) if you need them
* I didn't add the `sphinx` and `ghpages` activities for rendering and publishing docs, respectively. This is because I am not sure what the workflow is for conda-build. Are the docs pushed to GitHub Pages? In any event happy to work through this with you if you want. You can also always [create your own release activities](https://regro.github.io/rever-docs/tutorial.html#writing-custom-activities) in the rever.xsh if you are doing something super custom.

### CODE REVIEW

**Comment by msarahan** [comment]
Awesome!  Thanks.  It seems like the author list ordering is a little off, but that's no big deal.  Can you please add a comment to the readme or some other doc on how to use rever in normal workflows?  Things like:

* Should authors add something to their PR's so that their PR gets documented as part of the release?
* What command(s) should package maintainers run to accomplish a release?  Are there any preparatory steps they need to take?
* Are there any major gotcha's of things that will ruin rever's ability to operate, and thus should be strongly avoided?

**Comment by scopatz** [comment]
> Awesome! Thanks. It seems like the author list ordering is a little off, but that's no big deal.

NP!  The ordering is configurable (see [`$AUTHORS_SORTBY`](https://regro.github.io/rever-docs/activities.html#authors)), so feel free to change it from it's current `"num_commits"`.

> Should authors add something to their PR's so that their PR gets documented as part of the release?

Yes, I added a PR template to address this.

> What command(s) should package maintainers run to accomplish a release? Are there any preparatory steps they need to take?

Yep! I added a `rever check` step to more recent versions of rever. Docs are in the readme for all of this.

> Are there any major gotcha's of things that will ruin rever's ability to operate, and thus should be strongly avoided?

I am not aware of any, but I'd love to hear of some if you run into them

**Comment by scopatz** [comment]
Seems like travis is timing out...

**Comment by msarahan** [comment]
Very nice.  Thanks for all your work on this.  I'm concerned about the timeout - especially since conda 4.6.1 should be what is in use - but that's not related to this PR.  I'm merging this, and I look forward to using it to cut the next release!

**Pull request merged**
