### PR TITLE
Include `jinja2` in CI environments.

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
@msarahan and @groutr, I think @stuarteberg is right. There are still a ton of place where `jinja2` doesn't seem to exist. Mind providing some help in identifying them and/or letting us move to a new version of `miniconda` as appropriate to make this simpler.

**Comment by jakirkham** [comment]
Ok, this now install `jinja2` correctly. The fact that it is working correctly can be demonstrated by its use in this test ( https://github.com/conda/conda-build/pull/691 ).

**Comment by msarahan** [comment]
@jakirkham what do you mean "letting us move to a new version of miniconda"?  For the purposes of testing this repo, or what?  I'd be totally OK with updating recipes to use miniconda "latest" - but we need to be careful about its installation path, since the python2 version used to install as miniconda, but now installs as miniconda2 by default.  Nothing an explicit setting can't fix.

**Comment by jakirkham** [comment]
@msarahan, sorry, no longer relevant. Feel free to disregard as to works with the versions present.

**Comment by jakirkham** [comment]
Also, this should be ready to merge barring any other comments.

**Comment by msarahan** [comment]
Thanks!

**Pull request merged**
