### PR TITLE
add CONDA_BUILD_RENDERING env var that is set while rendering

### PR DESCRIPTION
**Pull request by msarahan**
Ping @janssen for comment.  This is meant to be my implementation of our discussion in https://github.com/conda/conda-build/issues/1023#issuecomment-236064273

### CODE REVIEW

**Comment by msarahan** [comment]
Travis failure is the race condition on anaconda.org.  This is ready to go.

**Comment by janssen** [comment]
Looks OK.  Is there a corresponding CONDA_BUILD_BUILDING that is set while actually building?

**Comment by msarahan** [comment]
Not presently.  Can you enlighten me on a use case?  I think CONDA_BUILD_BUILDING is sort of the default state (formerly the only state), but I am also wary of the dangers that a default state entail.  If you have even a half-compelling use case, I'll put it in.  Might as well go ahead and introduce the whole notion of state, and add in a state for testing, too.  Perhaps CONDA_BUILD_RENDERING would be better represented with a CONDA_BUILD_STATE variable that can be RENDERING or BUILDING or TESTING or whatever else is down the road.

**Comment by janssen** [comment]
I don't have a use case, I was just thinking that if there are going to be these explicit modes of operation, it would be useful to be able to find out which mode the build process was in.  CONDA_BUILD_STATE would work.

**Comment by msarahan** [comment]
OK.  I will work this into the 2.0 release.

**Comment by msarahan** [comment]
Implemented in #1232

**Pull request merged**
