### PR TITLE
Master.dry run patch

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
@jjhelmus @isuruf, fixes https://github.com/conda/conda-build/issues/4054

**Comment by jjhelmus** [comment]
LGTM, thanks @mingwandroid

**Comment by mbargull** [comment]
The comment
```
        # 3. When patch indicates failure, we call it with -R to reverse the damage.
```
is now out of sync ;).
I haven't checked: there is some test coverage for failing patches, right?

But the code looks fine to me -- happy to see that the simple `--dry-run` seems to work out!

**Comment by realthunder** [comment]
I got a recent build failure which probably relate to the change here. Please note that `patch --dry-run` may fail if the patch modifies the same file more than once, even if the patch applies fine when you do it for real. See [here](https://savannah.gnu.org/bugs/?25860), which also mentions the complication when doing reverse patch. Modifying the same file multiple times is common when squashing multiple commits into one patch file.

**Pull request merged**
