### PR TITLE
[2.1.x test backport] change r skeleton from nmf to acs; nmf got removed

### PR DESCRIPTION
**Pull request by mbargull**
Do we need this for the `conda` tests? Ref: https://circleci.com/gh/conda/conda/6995

### CODE REVIEW

**Comment by msarahan** [comment]
conda's tests appear to be pointed specifically at the 2.1.17 release.  Fixing things here is necessary, but not sufficient for conda's tests to pass.  We'll also need to update conda - probably to point at the 2.1.x branch.

**Comment by mbargull** [comment]
Makes sense, thanks Mike. Do you mind merging this so that I can make a PR with the `2.1.17`->`2.1.x` switch were the CI will use this right away?

**Comment by msarahan** [comment]
Sure, I'm fine with that.  Merging...

**Comment by mbargull** [comment]
Oops, this might not have been necessary at all... I didn't noticed the `conda` tests already define some `conda-build` tests to skip; I used that functionality instead in https://github.com/conda/conda/pull/6989.
(Well, at least it doesn't hurt to have this merged -- but sorry for the noise)

**Pull request merged**
