### PR TITLE
Only fetch `lfs` files for specific `git_ref`

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
### Description
Currently conda-build fetches _all_ lfs files that _ever_ existed in the history. This is not necessary, and as outlined in https://github.com/conda/conda-build/issues/4809 is costly when e.g. using GitHub. For the specific use case that I have in mind (see https://github.com/RoboStack/ros-humble/pull/155), the lfs files were actually removed from the repository and moved elsewhere (as the GitHub limits were exceeded, and now require payment), but the conda build still fails.

We already have the `git_ref` that we are interested in, so this is a relatively minor change; much smaller than making git-lfs completely optional as suggested in https://github.com/conda/conda-build/issues/4809

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by kenodegard** [comment]
@conda-bot check

**Comment by Tobias-Fischer** [comment]
Hi @kenodegard - any chance to run this again, please?

**Comment by Tobias-Fischer** [comment]
I think this is ready to go - all CI failures are unrelated :)

**Comment by Tobias-Fischer** [comment]
A quick reminder @kenodegard :)

**Comment by kenodegard** [comment]
@Tobias-Fischer thanks for checking in, we're still working to resolve the unrelated test failures caused by upstream deprecations, once we untangle that we'll get this moving again

**Review by kenodegard — APPROVED** [review]

**Review by schuylermartin45 — APPROVED** [review]
I appreciate you providing the additional context in the PR notes. This looks pretty straight forward and a good win all-around. Thanks!

**Pull request merged**
