### PR TITLE
fix symlinked folders not getting picked up in packaging. test.

### LINKED ISSUE #1769: Symbolic link folders don't work anymore
A symbolic link to a folder worked fine in conda-build 2.1.4, but it's not in conda-build 2.1.5 on osx (linux works fine).

conda-build 2.1.5 log
https://travis-ci.org/conda-forge/gap-feedstock/builds/204615074

conda-build 2.1.4 log
https://travis-ci.org/conda-forge/gap-feedstock/builds/200925407

### PR DESCRIPTION
**Pull request by msarahan**
fixes #1769

### CODE REVIEW

**Comment by isuruf** [comment]
@msarahan, thanks for fixing this. One question, does this make the symlinked folder a symlink after packaging or a copy?

**Comment by msarahan** [comment]
It should not affect whether the folder is a symlink or a copy.  It should just mark it as a path that has changed between initial files and files after installation (stuff to package.)

**Comment by isuruf** [comment]
I've noticed that symlinked folders are copied in 2.1.4
For example, if `a` is a symlink to `b` and `a/foo.so` is a file, then `b/foo.so` is also in the package as a copy. This means the conda package has 2 copies of the same file. I'll open another issue for this.

**Comment by msarahan** [comment]
That might be related to #1521 but that was quite a while ago (2.0.9) - I'd be surprised if you were only just now noticing it.  Probably some new bug.

**Pull request merged**
