### PR TITLE
Write out info/files in the noarch case. Always sanity check info/files.

### PR DESCRIPTION
**Pull request by Bezier89**
This fixes https://github.com/conda/conda-build/issues/2377

### CODE REVIEW

**Comment by msarahan** [comment]
thanks!  I'll wait on CI, but the changes look conceptually fine to me.

**Comment by Bezier89** [comment]
Looks like the "perl-cpan-Moo-" test failed. It seems unrelated to these changes as far as I can tell, though. Log:

> Traceback (most recent call last):
  File "/home/travis/build/conda/conda-build/conda_build/skeletons/cpan.py", line 429, in core_module_version
    output = subprocess.check_output(cmd, env=environ.copy())
  File "/home/travis/miniconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/travis/miniconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['corelist', '-v', '5.26.0', 'Moo']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/conda/conda-build/tests/test_api_skeleton.py", line 35, in test_repo
    config=testing_config)
  File "/home/travis/build/conda/conda-build/conda_build/api.py", line 260, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/home/travis/build/conda/conda-build/conda_build/skeletons/cpan.py", line 256, in skeletonize
    core_version = core_module_version(package, perl_version, config=config)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda-4.3.26.post10+c72e4a8b-py3.6.egg/conda/utils.py", line 47, in __call__
    value = self.func(*args, **kw)
  File "/home/travis/build/conda/conda-build/conda_build/skeletons/cpan.py", line 435, in core_module_version
    'environment.') % ' '.join(cmd))
SystemExit: Error: command failed: corelist -v 5.26.0 Moo
Please make sure you have the perl conda package installed in your default environment.

**Comment by msarahan** [comment]
Yeah, that one is fine to ignore.

**Comment by Bezier89** [comment]
Thanks @msarahan. This PR is ready to merge if you're satisfied with the changes.

**Comment by msarahan** [comment]
Thanks @Bezier89 - merging.

**Pull request merged**
