### PR TITLE
enable py3.5 win; quiet updates, use flake8; fix pep8

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by msarahan** [comment]
flake failures appear to be related to https://bugs.launchpad.net/pyflakes/+bug/1560134 - which seems to be an upstream bug in pyflakes/flake8.  Going to try pinning to an older version.

**Comment by msarahan** [comment]
@kalefranz @groutr @mingwandroid @ilanschnell 

I think these are uncontroversial changes - but please make sure you are OK with this before I go forward.  Changes here are only whitespace, plus CI changes to use flake8 instead of pyflakes, and enabling py3.5 on AppVeyor.

**Comment by mingwandroid** [comment]
LGTM.

**Comment by msarahan** [comment]
Thanks @mingwandroid - merging.

**Pull request merged**
