### PR TITLE
 Fix issue 3899

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
I cannot figure out why the AP builds are not being run here. Do you have any idea @jjhelmus?

**Comment by marcelotrevisani** [comment]
That is odd, indeed
Let's try to close and reopen this PR to see it is going to trigger it

**Comment by marcelotrevisani** [comment]
@mingwandroid 
I think I fixed it with
https://github.com/conda/conda-build/pull/3904/files

But the explanation of why this way is not working anymore... I really don't know.
Microsoft might drop the way to trigger branches

**Comment by mingwandroid** [comment]
Failures are connection things. Please review @jjhelmus

**Comment by jjhelmus** [comment]
LGTM, thanks for the fix @mingwandroid

**Pull request merged**
