### PR TITLE
Master variant values as dicts

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
@msarahan, @jjhelmus this should be ready for review. The sole Windows failure appears unrelated (permissions stuff).

@conda-forge/core : the test recipe's conda-build-config.yaml sketches out how I intend this to be used. Your thoughts/reviews would be welcome.

**Comment by msarahan** [comment]
You can't ping conda-forge/core here - it only works within an org.  Probably better to announce it to them on gitter.

**Comment by msarahan** [comment]
All looks good to me.  We could use tqdm for progress bars, but we can add that later.

**Comment by mingwandroid** [comment]
OK, I'll ping them when the last part of this is hooked up. Trying to decide what to do about CBC.yaml files passed on the command line when running --test.

**Pull request merged**
