### PR TITLE
Always use the subdir defined in the package

### LINKED ISSUE #4750: Downstream tests download to wrong subdir (breaks boa+libsolv>=0.7.23)
### What happened?

See https://github.com/conda/conda-index/issues/89 and linked issues.

> This comes from https://github.com/openSUSE/libsolv/commit/cc2da2e789f651b2d0d55fe31c258426bf9e984d#diff-2f0af950e6d2249e0340147b80f5b8194de5362f23026ff65cdb65dfa57696aaR314-R320 , i.e., a newly added strict check in `libsolv=0.7.23` update.
That check is probably reasonable/good -- but `conda-build` is not so strict and dumps the to-be-downstream-tested packages in the current subdir.

In https://github.com/conda-forge/conda-feedstock/pull/197#issuecomment-1400851029 the `noarch` package `conda-smithy` gets downloaded to `conda-build/linux-64` which is then indexed and thus results in a `repodata.json` for `linux-64` with a `noarch` package.

----

I didn't dig deep enough, but I guess somewhere around
https://github.com/conda/conda-build/blob/3.23.3/conda_build/build.py#L3144
-> https://github.com/conda/conda-build/blob/3.23.3/conda_build/render.py#L311
is the culprit.

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

Address a second case (conda-build downstream tests) where conda-build is incorrectly downloading packages into the wrong subdir. This was discovered during conda 23.3.0 on conda-forge.

Resolves #4750

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jezdez** [comment]
@isuruf @mbargull do you have concerns about this change?

**Comment by isuruf** [comment]
Nope. Looks good to me.

**Review by jezdez — CHANGES_REQUESTED** [review]
Needs news and tests?

**Comment by dholth** [comment]
One place that packages get mixed even though they belong to different subdirs is in `~/miniconda3/pkgs`. I've enjoyed running conda-index on that directory to test.

**Review by jezdez — APPROVED** [review]

**Pull request merged**
