### PR TITLE
Make the long build prefix longer

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
For binary prefix replacement (much rarer than plain text replacement, which is what's used for shebang lines), the install prefix cannot be longer than the build prefix.

**Comment by asmeurer** [comment]
This one can be merged whenever. It will just require rebuilding some packages.

**Comment by pelson** [comment]
:+1:

**Comment by msarahan** [comment]
consolidating discussion in #877

**Pull request closed without merging**
