### PR TITLE
warn for path conflicts during environment building for test phase

### PR DESCRIPTION
**Pull request by kalefranz**
Per discussion.  Probably not done yet.  Figured I'd get something started and in the queue though.

### CODE REVIEW

**Comment by jjhelmus** [comment]
This is a good idea but I believe the warnings are currently being suppressed.  I tested these changes with a recipe that is know to have conflicts and observed no warnings during the test phase.

**Comment by msarahan** [comment]
yeah, I'll try to figure out how to let warnings show up.  I'll push to this PR.

**Comment by msarahan** [comment]
@jjhelmus what is a good recipe to use to test this?

**Comment by jjhelmus** [comment]
[tensorboard](https://github.com/AnacondaRecipes/aggregate/tree/master/tensorboard-feedstock/recipe) is what I've been testing, it has a conflicting file (bin/tensorboard) with tensorflow-base.  Unfortunately, the recipes takes ~3.5 minutes to build on my machine so it is not the most convenient example.  If I find a better example I will update this issue.

**Comment by msarahan** [comment]
@jjhelmus I'm hopeful that my latest commit here may show the warnings.  Can you take a look and see if they show up for you now?

**Comment by jjhelmus** [comment]
I'm still not seeing any warning message when testing packages which have conflicting files.  I put together this minimal example:

pkg_a/meta.yaml
``` yaml
package:
  name: pkg_a
  version: "1.0.0"

build:
  script: touch $PREFIX/this_is_a_file
```

pkg_b/meta.yaml
``` yaml
package:
  name: pkg_b
  version: "1.0.0"

build:
  script: touch $PREFIX/this_is_a_file

requirements:
  run:
    - pkg_a

test:
  commands:
    - echo "hello"
```

**Comment by msarahan** [comment]
re-running now that #2844 is merged.

**Pull request merged**
