### PR TITLE
add support for .tar.lzma

### PR DESCRIPTION
**Pull request by abloemert**

### CODE REVIEW

**Comment by mingwandroid** [comment]
IMHO, if we are going to support this it should be done via `libarchive` and `python-libarchive` rather than an external executable.

**Comment by abloemert** [comment]
> IMHO, if we are going to support this it should be done via libarchive and python-libarchive rather than an external executable.

@mingwandroid: I added the external executable for backwards compatibility with Python 2. Python 3 has built-in support for lzma.

**Comment by mingwandroid** [comment]
Sure, but we have python-libarchive with lzma support for Python 2 on all platforms.

Also python-libarchive is way faster than tarfile.

**Comment by abloemert** [comment]
If python-libarchive is really faster, we should use it for all formats indeed. However this will be much more work and could have a big impact. This simple change however will at least add support for .tar.lzma files, which is currently missing in conda-build.

**Comment by mingwandroid** [comment]
But you introduce a feature that works with some pretty bad caveats, that is IMHO worse than not having it.

**Comment by mingwandroid** [comment]
> However this will be much more work and could have a big impact

About 15 minutes work in my estimation.

**Comment by mingwandroid** [comment]
Here you go: https://github.com/conda/conda-build/commit/cfaada3246ab3d773ae221a2a7b64e17acb2eb20

**Comment by mingwandroid** [comment]
> However this will be much more work

In any PR, this is a terrible argument BTW, it doesn't give me confidence that you will maintain the code you propose.

**Comment by msarahan** [comment]
superseded by https://github.com/conda/conda-build/pull/2878

Thanks @abloemert for getting the ball rolling here.

**Pull request closed without merging**
