### PR TITLE
Configure `pip` to disable pulling in dependencies

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda/conda-build/issues/2748

We never want `pip` to install dependencies in the build as we will supply them ourselves.

### CODE REVIEW

**Comment by jjhelmus** [comment]
Does it make sense to add `env["PIP_NO_BUILD_ISOLATION"] = False` as well to disable build isolation?

**Comment by jakirkham** [comment]
Yeah was just trying to figure out if we were doing that or not earlier as well. Seems like we are, which is good.

**Comment by jakirkham** [comment]
Looks like there are a couple CI failures related to some `rpm` test where the HTTP request fails. Seems unrelated. Also one Travis CI test timed out.

**Comment by msarahan** [comment]
Added some small comments about the counterintuitive logic of the "NO" env vars.  Thanks @jakirkham

**Comment by jakirkham** [comment]
Thanks @msarahan.

Yeah the "NO" environment variables are still very weird. In addition to the counterintuitive logic, some of them will crash if set incorrectly (as they expect more arguments).

xref: https://github.com/pypa/pip/issues/2897

**Comment by msarahan** [comment]
Frustrating, but at least they are consistent.

**Pull request merged**
