### PR TITLE
Attempt to fix issues when git commits have non-ASCII characters in Python 2

### LINKED ISSUE #456: git source fails when the changeset's commit message is non-ASCII
This is a traceback we got on a Jenkins builder (Numba):

```
Traceback (most recent call last):
  File "/var/jenkins/workspace/Numba-Builder-Linux32@2/CONDA_NPY/19/CONDA_PY/34/label/CentOS5x32b/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/var/jenkins/workspace/Numba-Builder-Linux32@2/CONDA_NPY/19/CONDA_PY/34/label/CentOS5x32b/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 118, in main
    args_func(args, p)
  File "/var/jenkins/workspace/Numba-Builder-Linux32@2/CONDA_NPY/19/CONDA_PY/34/label/CentOS5x32b/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
  File "/var/jenkins/workspace/Numba-Builder-Linux32@2/CONDA_NPY/19/CONDA_PY/34/label/CentOS5x32b/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 288, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/var/jenkins/workspace/Numba-Builder-Linux32@2/CONDA_NPY/19/CONDA_PY/34/label/CentOS5x32b/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 347, in build
    source.provide(m.path, m.get_section('source'))
  File "/var/jenkins/workspace/Numba-Builder-Linux32@2/CONDA_NPY/19/CONDA_PY/34/label/CentOS5x32b/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 251, in provide
    git_source(meta, recipe_dir)
  File "/var/jenkins/workspace/Numba-Builder-Linux32@2/CONDA_NPY/19/CONDA_PY/34/label/CentOS5x32b/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 135, in git_source
    git_info()
  File "/var/jenkins/workspace/Numba-Builder-Linux32@2/CONDA_NPY/19/CONDA_PY/34/label/CentOS5x32b/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 163, in git_info
    print(stdout + u'\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 296: ordinal not in range(128)
```

You can see that changeset in the Numba git repository:
```
$ git checkout 6efdca690a4e13d10cc18e2c172c0b2050159c95
[...]
$ git log -n1
commit 6efdca690a4e13d10cc18e2c172c0b2050159c95
Merge: 49d01f4 e9e1a70
Author: Siu Kwan Lam <michael.lam.sk@gmail.com>
Date:   Tue Jun 16 13:20:44 2015 -0500

    Merge pull request #1231 from pitrou/cuda_del_warnings
    
    Fix #1164: avoid warnings at shutdown when finalizing a CUDA context …
```

Note the unicode ellpsis (`…` not `...`) in the commit message.

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes #456

### CODE REVIEW

**Comment by pitrou** [comment]
(note that it's also an issue in Python 3)

**Comment by asmeurer** [comment]
So is the issue that the Jenkins machine has a weird locale?

**Comment by pitrou** [comment]
Probably the C locale. This is common on some minimally-configured (or very old...) server boxes.

**Comment by pitrou** [comment]
I can confirm this fixes the issue on Python 3 (at home, but certainly on the Jenkins box as well).

**Pull request merged**
