### PR TITLE
14 for new release

### PR DESCRIPTION
**Pull request by mingwandroid**
@jjhelmus, @ktietz, still quite WIP (final content is the same as 13-New-features.3, so we have features that are still WIP) .. I have squashed the commits into sensible commits that can be judged independently though.

### CODE REVIEW

**Comment by mingwandroid** [comment]
Oh yeah, for now, PR is mainly to catch issues, I expect them.

**Comment by ktietz** [comment]
I think you tagged the wrong person haha. Hope the build goes well though :)

**Comment by mingwandroid** [comment]
Oops, thanks, pinging @katietz

**Comment by kenodegard** [comment]
Superseded by:
- https://github.com/conda/conda-build/commit/94c16481f8338138e4bb961fa2677f422c4631df
- https://github.com/conda/conda-build/pull/4120
- https://github.com/conda/conda-build/pull/4026
- https://github.com/conda/conda-build/pull/4028

**Pull request closed without merging**
