### PR TITLE
Do not disable pip's cache, rather point in to a location inside the work dir

### LINKED ISSUE #3094: Disabling pip's cache directory results in .egg-info directories
#3053 disabled pip's cache directory by default in the build environment.  

An unfortunate side effect of disabling pip's cache directory is that an `.egg-info` directory is produced rather than a `.dist-info` directory.  This is a result a pip not generating wheels during the install process.

For example, take the following recipe:

``` yaml
package:
  name: imagesize
  version: 1.0.0

source:
  url: https://pypi.io/packages/source/i/imagesize/imagesize-1.0.0.tar.gz
  sha256: 5b326e4678b6925158ccc66a9fa3122b6106d7c876ee32d7de6ce59385b96315

build:
  #script: python -m pip install .
  script: unset PIP_NO_CACHE_DIR; python -m pip install .

requirements:
  host:
    - python
    - pip
  run:
    - python
```

As written, pip's cache directory is disabled in conda-build >= 3.12.1.  The resulting package will contain an `.egg-info` directory:

```
lib/python3.6/site-packages/imagesize-1.0.0-py3.6.egg-info/dependency_links.txt
lib/python3.6/site-packages/imagesize-1.0.0-py3.6.egg-info/top_level.txt
lib/python3.6/site-packages/imagesize-1.0.0-py3.6.egg-info/installed-files.txt
lib/python3.6/site-packages/imagesize-1.0.0-py3.6.egg-info/SOURCES.txt
```

Using the commented script, re-enables the cache directory, resulting in a wheel being generated as an intermediate.  The conda package then contains a `.dist-info` directory.

``` 
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/INSTALLER
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/top_level.txt
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/WHEEL
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/RECORD
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/LICENSE.txt
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/METADATA
```

I believe that `dist-info` directories should be preferred and these are currently not the default. 

It is possible that the python version entry in the `egg-info` directories (**py3.6**.egg-info) could be problematic for `noarch: python` packages although I have no evidence of this.

### PR DESCRIPTION
**Pull request by jjhelmus**
closes #3094

### CODE REVIEW

**Comment by jjhelmus** [comment]
Disabling pip's cache results in [pip not building wheels](https://github.com/pypa/pip/blob/10.0.1/src/pip/_internal/commands/install.py#L293-L295) which leads to the conda package containing Python versioned `.egg-info` directories rather than modern `.dist-info` directories.  This change leaves the choice of disabling the cache up to the user (pip by default uses the cache directory) but when the cache is enabled it points to a location inside the work directory.  This avoid situations where the wheels from the default pip cache are installed into the conda environment.

**Comment by jjhelmus** [comment]
My choice of `mktemp` was intentional despite the function being deprecated and unsafe.  Other options from the tempfile module would create a folder inside the work directory which is not ideal.  If there is better method to generate a unique directory name but not actually create the directory I'm all ears.

**Comment by nehaljwani** [comment]
Wouldn't this hurt the builder in the scenario where `merge_build_host: True` ? Wouldn't the cache directory would then become part of the package itself?

How about instead of putting it in the `_build_env` directory, we shove it one level up and call it something like `__pycache_<(not-necessarily!?-)long-path-here>` ?

**Comment by nehaljwani** [comment]
Sorry, I misread. You are actually using the work directory. Nevertheless, I would still like to know your thoughts about a top level __pipcache diretory.

**Comment by nehaljwani** [comment]
Or we could still put it in the work directory, but prefix it with `__pipcache`. I want an identifier, so that I wouldn't have to go inside the work directory and hunt for the cache directory whereas I could simply `/path/to/worl-or-top-level/__pipcache<hit-tab>`

**Comment by msarahan** [comment]
There's one more of these vars in windows.py.

If it helps @nehaljwani, I agree that it would be helpful to have a folder for these files, though I personally don't know that I would use it.

**Comment by jakirkham** [comment]
Thanks all. This seems like a nice, simple fix to the issue.

**Pull request merged**
