### PR TITLE
Ensure `test/commands` & `run_test.*` both work

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda/conda-build/issues/4427

Not sure if this is the right approach. Though this does fix the issue based on local testing. If there is a different way we would like to go about this, happy to discuss.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @chenghlee (as we discussed this issue/fix today)

**Comment by jakirkham** [comment]
Please let me know if there's anything else needed here 🙂

**Comment by jakirkham** [comment]
Rebased

**Comment by travishathaway** [comment]
Hi @jakirkham,

Thanks a lot for this PR and trying to solve this particular bug. The concerns that we have is that `m.config.info_dir` may not always contain the tests. specifically if the following options are passed to `conda build`:

```
--no-include-recipe   Don't include the recipe inside the built package.
--no-copy-test-source-files
                        Disables copying the files necessary for testing the package into the info/test folder.
                        Passing this argument means it may not be possible to test the package without internet
                        access. There is also a danger that the source archive(s) containing the files could become
                        unavailable sometime in the future.
```

I also played around with this myself yesterday, and realized that you could also solve this particular issue by completely remove this line:

https://github.com/conda/conda-build/blob/3268fddb1476ea3263b797e62cd34faea31b1be2/conda_build/create_test.py#L70

To be perfectly honest with you, I am not sure why this check exists in the first place (I tried "git blame" to no avail). But, if we can determine that it's not necessary then simply removing this may be the best way. Maybe this is something you could help out with?

Here's the test recipe I used during debugging:

[test-recipe-issue-4429.zip](https://github.com/conda/conda-build/files/8570361/test-recipe-issue-4429.zip)

Thanks again for your hard work on this!

**Review by beeankha — DISMISSED** [review]

**Review by jezdez — CHANGES_REQUESTED** [review]
This needs a news file

**Comment by h-vetinari** [comment]
Could someone come up with the news file here? It's a pity this PR is held up over that.

Here's a suggestion in case someone wants it:
```
### Enhancements

* <news item>

### Bug fixes

* Ensure that `tests/commands` get run also in the presence of `run_test.*` (#4429, fixes #4427)

### Deprecations

* <news item>

### Docs

* <news item>

### Other

* <news item>
```

**Comment by h-vetinari** [comment]
Sure, but later reviews did not dwell on that point. It could be taken up independently IMO; this fix is certainly a step in the right direction already, as right now there are a bunch of recipes whose tests aren't being run properly.

**Comment by jakirkham** [comment]
Perhaps folks felt no need to repeat a view that was already shared (with a good bit of detail)?

Anyways would rather not ignore Travis' feedback. He spent quite a bit of time looking into it.

Think the challenge here is none of us have a good understanding of why this check is present. So lack confidence in this or another change.

If you are interested in helping this move forward, maybe more testing of the kind Travis suggested would help.

**Comment by kenodegard** [comment]
Ahhhh! Just stumbled over this myself while working on the conda canaries (https://github.com/conda/conda/pull/12603).

From my testing focused on `conda build --test PACAKAGE` we can safely remove the `if basename(test_dir) != "test_tmp":` entirely.

**Review by kenodegard — DISMISSED** [review]

**Comment by jakirkham** [comment]
Just pushed changes. Not sure what GH is doing with reviews (sorry about that)

**Comment by kenodegard** [comment]
@jakirkham this is expected, we automatically dismiss prior reviews if changes are pushed

**Review by beeankha — APPROVED** [review]

**Comment by jakirkham** [comment]
> this is expected, we automatically dismiss prior reviews if changes are pushed

Ah ok. Is this a setting on the repo or something?

In any event, wanted to make sure that event wasn't misinterpreted 🙂

**Comment by kenodegard** [comment]
> > this is expected, we automatically dismiss prior reviews if changes are pushed
> 
> Ah ok. Is this a setting on the repo or something?

It's a repo/branch setting

**Review by jezdez — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
