### PR TITLE
Add support for defining `_CONDA_BUILD_ISOLATED_ACTIVATION` in `meta.yaml`

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

The `_CONDA_BUILD_ISOLATED_ACTIVATION` environment variable is special and can currently only be set prior to running `conda build`, (e.g. `_CONDA_BUILD_ISOLATED_ACTIVATION=1 conda build ...`). This makes it hard to enable for packaging teams that do not normally expose this kinds of customizations. So instead of exclusively relying on a pre-set environment variable, let's also allow the value to be set within `meta.yml`'s `build/script_env`.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by kenodegard** [comment]
To indicate that its private?

**Comment by jezdez** [comment]
I'm not sure this should be "private" if it becomes part of the recipe format. Are there other ways to add this as a first-level recipe option?

**Comment by kenodegard** [comment]
@jezdez I don't want this environment variable to become an official `meta.yaml` setting. IMO isolated mode should be the only mode conda is ever invoked as. We also need to work to eliminate the need to run conda via subprocess in the first place. Furthermore, there needs to be proper API end-points that conda-build should call instead.

**Comment by kenodegard** [comment]
we are collectively displeased with this solution and should consider something like https://github.com/conda-forge/conda-feedstock/pull/204 instead

**Pull request closed without merging**
