### PR TITLE
WIP: Fix cross compiling

### PR DESCRIPTION
**Pull request by msarahan**
We discovered a number of issues with the cross-compiling support recently.  This PR is still failing with several git-jinja2 related failures.  These have to do with work_dir not matching up and source code not being present.

I'm going to come back to this late Sunday or first thing Monday.

### CODE REVIEW

**Comment by kalefranz** [comment]
https://en.wikipedia.org/wiki/Unix_time

**Comment by msarahan** [comment]
You're not wrong, but the ship really has sailed here.  Ray built about 4000 packages across the different platforms that all have timestamps that would be 100 times whatever we would correct them to.  Sorry for the confusion.  If you can propose a correction scheme, I'll consider it.  Otherwise, please deal with it.

**Comment by kalefranz** [comment]
Yeah I can correct it on the conda side.  Give me a sec to make a PR against 4.3.

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/6001

**Pull request merged**
