### PR TITLE
Fix behaviour with --output for noarch packages

### LINKED ISSUE #467: conda build --output doesn't honor noarch_python
I'm using the recent feature of `noarch_python: true` in meta.yaml (merged in #317). My package builds fine, but when I try to get the package path via `conda build --output conda_build.recipe`, it shows the path with `linux-64` instead of `noarch`, where the package is stored after successful build.

```
$ conda build conda_build.recipe
...
# If you want to upload this package to binstar.org later, type:
#
# $ binstar upload /home/jenkins/conda-bld/noarch/mypackage-1.0-py_27.tar.bz2
```

```
$ conda build --output conda_build.recipe
/home/jenkins/conda-bld/linux-64/mypackage-1.0-py_27.tar.bz2
```

### PR DESCRIPTION
**Pull request by hargup**
fixes #467

### CODE REVIEW

**Comment by hargup** [comment]
@frol Can you verify the patch?

**Comment by frol** [comment]
@hargup Sure. Let me build it and I will respond.

**Comment by frol** [comment]
@hargup This works! Great!

**Comment by hargup** [comment]
@asmeurer @ilanschnell

**Pull request merged**
