### PR TITLE
Add SHLIB_EXT environment variable to the build

### PR DESCRIPTION
**Pull request by jschueller**
Often seen in feedstocks as DYN_EXT, SO_EXT, DYNAMIC_EXT, EXT, SONAME, LIBEXT, etc

### CODE REVIEW

**Comment by mingwandroid** [comment]
Personally I would rather see something platform agnostic here, so neither so, dll nor dylib. SHLIB_EXT for example.

**Comment by jschueller** [comment]
ok, I liked dyn_ext though, but thought dylib was more specific.

**Comment by msarahan** [comment]
Thanks @jschueller - this makes good sense to me.  Thanks especially for updating the docs, too.

**Comment by jschueller** [comment]
on feedstocks I cannot use this as latest conda-build is not used because it conflicts with the one from defaults and conda choses the oldest :(

```
WARNING: conda-build appears to be out of date. You have version 1.21.14 but the
latest version is 2.0.7. Run

conda update -n root conda-build

to get the latest version.
```

**Comment by msarahan** [comment]
This is an issue with conda-forge, not conda-build.  You need to re-render your feedstock in order to un-pin conda-build.

**Comment by jschueller** [comment]
@msarahan I rerenderend with latest 1.3.3 in the same PR

**Comment by msarahan** [comment]
OK, sorry, I don't know what else to do.  Please ping @jakirkham and ask how to deal with conda-forge-setup pinning conda-build.  It's happening here: https://travis-ci.org/conda-forge/hmat-oss-feedstock/builds/170480555#L122

**Pull request merged**
