### PR TITLE
Reword note on OS skips containing typos

### PR DESCRIPTION
**Pull request by jacobtylerwalls**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Can you sign our CLA please?

**Comment by jacobtylerwalls** [comment]
I signed it on 11/24/20. I'm waiting for someone to verify it.

**Comment by mingwandroid** [comment]
Ah, apologies. I'll look into that now.

**Comment by mingwandroid** [comment]
@anaconda-issue-bot check

**Comment by jacobtylerwalls** [comment]
@anaconda-issue-bot check

**Comment by jacobtylerwalls** [comment]
@anaconda-issue-bot check

**Comment by jacobtylerwalls** [comment]
> Ah, apologies. I'll look into that now.

No, I was at fault! In the same 24-hr period I was submitting patches to both conda and conda-build for the first time and neglected to notice that the identical forms needed to be submitted to both orgs (both repos?)

**Pull request merged**
