### PR TITLE
Support output packages with both script and files

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
This is ready for review

**Review by mbargull — DISMISSED** [review]
LGTM!

**Comment by isuruf** [comment]
Ping on this. This PR makes it easier to write multi-output recipes.

cc @jezdez, @chenghlee

**Review by jezdez — APPROVED** [review]
Sounds good to me, this just needs a news items.

**Comment by isuruf** [comment]
ping

**Comment by isuruf** [comment]
ping

**Review by jezdez — APPROVED** [review]

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
