### PR TITLE
[skip ci] Reorganized Resources, updated link scripts

### PR DESCRIPTION
**Pull request by rrigdon**
Massive reorganization of conda-build by adding a Resources section. I also updated the link scripts page per PR #619.

### CODE REVIEW

**Comment by msarahan** [comment]
are there any redirects we need to put in place before this goes in?  Or will all of these keep any potential bookmarks or google hits working?

**Comment by rrigdon** [comment]
This will likely break those links. I'll work on putting redirects in now.

**Comment by rrigdon** [comment]
Redirects are in place.

**Comment by msarahan** [comment]
fingers crossed!  good luck.

**Pull request merged**
