### PR TITLE
Revert "Use normpath instead of fnmatch where appropriate"

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Reverts conda/conda-build#3793

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Reverting in favor of
https://github.com/conda/conda-build/pull/3793#issuecomment-549035227

**Comment by msarahan** [comment]
@mingwandroid should this be merged given your work in #3791 ?

**Comment by mingwandroid** [comment]
I'd leave it as-is for *now* and I'll try to figure out the best plan. My PR adopts the normpath stuff FWIW.

**Comment by marcelotrevisani** [comment]
I will close it then but feel free to reopen it if you think it is necessary

**Pull request closed without merging**
