### PR TITLE
Recompress test .tar.bz2 archives

### PR DESCRIPTION
**Pull request by dholth**
### Description

Recompress so they are actually .tar.bz2.

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [x] Add / update necessary tests?
- [ ] ~Add / update outdated documentation?~

### CODE REVIEW

**Review by kenodegard — APPROVED** [review]

**Review by kenodegard — DISMISSED** [review]

**Review by kenodegard — APPROVED** [review]

**Review by sven6002 — APPROVED** [review]
Looks good

**Review by sven6002 — APPROVED** [review]
looks good

**Review by kenodegard — APPROVED** [review]

**Comment by jezdez** [comment]
There seem to be other changes related to allure in this PR, is this intended?

**Comment by jezdez** [comment]
Ah I found https://github.com/conda/conda-build/pull/4624#issuecomment-1372923325 nevermind

**Review by jezdez — APPROVED** [review]

**Comment by dholth** [comment]
@jezdez something is wrong with Windows test speed, this will pass in about 2h 15 minutes. https://github.com/conda/conda-build/pull/4694 includes these changes but skips enough tests to make further work possible.

**Comment by dholth** [comment]
Obsoleted by https://github.com/conda/conda-build/pull/4694

**Pull request closed without merging**
