### PR TITLE
fix conda skeleton for packages having `setup_requires` in `setup.py`

### PR DESCRIPTION
**Pull request by hargup**

### CODE REVIEW

**Comment by asmeurer** [comment]
According to https://pythonhosted.org/setuptools/setuptools.html, setup_requires aren't installed by setuptools automatically. What package needs this fix to work?

**Comment by hargup** [comment]
There are a lot of them 54/500, they fail with a error message like this

```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/pbr/r
```

**Comment by hargup** [comment]
Well here is the diff of the scores for the first 500 packages after I ran with this patch:

```diff
-recipe score: 479/500
+recipe score: 467/500
 
 
-build score: 326/500
+build score: 367/500
 
 
 * * *

-No recipe available: 21/174
+No recipe available: 33/133
 
 
-No packages found in current linux-64 channels: 30/174
+No packages found in current linux-64 channels: 26/133
 
 
-missing build dependency: 54/174
+missing build dependency: 3/133
 
 
-test failure: missing dependency: 37/174
+test failure: missing dependency: 41/133
 
 
-test failure: other reasons: 14/174
+test failure: other reasons: 12/133
 
 
-invalid syntax: 4/174
+invalid syntax: 5/133
 
 
-unclassified: 14/174
+unclassified: 13/133
```

I've to investigate a little more to see why there are more failed recipes now.

**Comment by asmeurer** [comment]
Do those dependencies get installed when you `pip` install those packages into a test environment?

**Comment by hargup** [comment]
Those packages are not installed but the dependencies in `setup_requires` are downloaded. You can try it out on the package `linecache2`. When `conda-build` runs the setup it disallows setuptools downloading as I mentioned in https://github.com/conda/conda-build/pull/419#issuecomment-105776890 I think rather than putting `setup_requires` under build dependencies

**Comment by asmeurer** [comment]
What dependency should be there for linecache2?

**Comment by hargup** [comment]
It is only `pbr` and `setuptools`, `pbr` is not installed but it "depends" on it in the sense that it is used in the setup process, here's the output for `pip install . -vvv` (`.` is the git directory for `linecache2`)
```
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /home/ubuntu/linecache2
  Running setup.py (path:/tmp/pip-wJwnfP-build/setup.py) egg_info for package from file:///home/ubuntu/linecache2
    Running command python setup.py egg_info

    Installed /tmp/pip-wJwnfP-build/.eggs/pbr-1.0.1-py2.7.egg
    [pbr] Generating ChangeLog
    running egg_info
    creating pip-egg-info/linecache2.egg-info
    writing pip-egg-info/linecache2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/linecache2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/linecache2.egg-info/dependency_links.txt
    writing pbr to pip-egg-info/linecache2.egg-info/pbr.json
    [pbr] Processing SOURCES.txt
    writing manifest file 'pip-egg-info/linecache2.egg-info/SOURCES.txt'
    warning: LocalManifestMaker: standard file '-c' not found

    [pbr] In git context, generating filelist from git
    warning: no files found matching 'ChangeLog'
    warning: no previously-included files found matching '.gitreview'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'pip-egg-info/linecache2.egg-info/SOURCES.txt'
  Source in /tmp/pip-wJwnfP-build has version 1.0.0, which satisfies requirement linecache2==1.0.0 from file:///home/ubuntu/linecache2
  Requirement already satisfied (use --upgrade to upgrade): linecache2==1.0.0 from file:///home/ubuntu/linecache2 in /home/ubuntu/miniconda/envs/test_2.7/lib/python2.7/site-packages
Cleaning up...
  Removing source in /tmp/pip-wJwnfP-build
```

**Comment by asmeurer** [comment]
So should these dependencies only be added to the build requirements then?

**Comment by hargup** [comment]
> So should these dependencies only be added to the build requirements then?

I'm not sure about that. Probably we should add setup requirements separately from other requirements but handle them like build requirements.

```yaml
requirements:
  build:
    - python

  run:
    - python

  setup:
    - pbr
```

**Pull request closed without merging**
