### PR TITLE
Fix bug corrupting rendered meta.yaml from conda build

### PR DESCRIPTION
**Pull request by mwiebe**
Fixes https://github.com/conda/conda-build/issues/1588. Any ideas how a test for this would be structured?

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks!  I'll look into a test tomorrow and submit a PR on your branch.

I'm also pretty close to working out the build customization stuff, finally.  See #1585 - but I'll also ping you when I think it's really ready to be honestly evaluated.

I think where I'm headed with it is that compilers are going to be conda packages themselves.  Things like VS may not actually contain the compilers, but will contain the code to put the necessary compilers on PATH.  This is going to depend on using conda-build to activate the build environment, as I'm thinking the compiler activation stuff will be scripts that run when an environment is activated.  Still about a day or two's work to get there.

**Comment by mwiebe** [comment]
Cool! The way our stuff is set up right now is with a `toolchain` variant package the way @mcg1969 gisted, to represent whether it's msvc 2015 release, msvc 2015 debug, etc, and then a compiler configuration package on top of that which brings in the actual compiler via a script that all our recipes source when they start. Currently we're not using multiple compilers for a given `toolchain`,  but the structure will be useful for packages built with clang or mingw, but matching the runtime of a particular msvc.

**Comment by mwiebe** [comment]
We've also started using the `script_env` for parameterizing packages, and create build matrices based on all the possible values of these variables (with the `build/skip` metadata pruning the explosion of possible combinations).

**Comment by msarahan** [comment]
Not sure how to test.  Probably should build a package and look at the generated meta.yaml file in that built package.  Merging for now, will leave your issue open to remind me to test.  Thanks @mwiebe

**Comment by mwiebe** [comment]
If you want the issue to stay open you'll have to reopen it, I put the "closes" meta-phrase in the merge request. :)

**Pull request merged**
