### PR TITLE
Cap CPU_COUNT using config.max_cpu_count

### PR DESCRIPTION
**Pull request by jschueller**
As discussed in https://github.com/conda-forge/staged-recipes/pull/531#discussion_r62087468
Depends on https://github.com/conda/conda/pull/2429

### CODE REVIEW

**Comment by groutr** [comment]
Do we have a file for conda-build settings?

**Comment by jschueller** [comment]
Whitelisting CPU_COUNT is simpler

**Comment by jakirkham** [comment]
> Whitelisting CPU_COUNT is simpler

Agreed. Done in PR ( https://github.com/conda/conda-build/pull/1149 ).

**Comment by msarahan** [comment]
Closing this issue.  #1149 will be in the next conda-build release, coming in the next week or so.

**Pull request closed without merging**
