### PR TITLE
implement --old-build-string option (no hash in filename)

### LINKED ISSUE #1919: conda-build 3.0.0alpha3 produces conda packages with new build strings
I'm raising some concerns about the new build strings which conda-build 3.0 is creating:
  * the new build strings are different from the existing ones, and this might cause problems for existing users.  The build string does not need to be of a specific format, as far as conda is concerned.  The existing convention, e.g. `np19py27_1` has existed since the beginning of the conda project (this convention actually predates conda-build) and many people are probably very used to it by now.  Moreover, people (such as myself, but likey others as well) have written scripts around conda-build which rely on the existing build string naming convention.
  * the new build strings contain opaque hashes, which makes users wonder what exactly they mean and which information they contain.  In creating the conda ecosystem, one of it's core design principles has always been simplicity and transparency.  The hashes are not transparent and therefore violate this design principle.

### PR DESCRIPTION
**Pull request by msarahan**
closes #1919 

Please review @ilanschnell

### CODE REVIEW

**Comment by teoliphant** [comment]
Thanks for working on this.   Wouldn't it be better if we just instead provided a "--build-string-override" option.   Then conda-build wouldn't have to have any of the "old build-string" logic.   But, a package builder could just override if they insist (and are willing to deal with the hassles themselves).    The hashing approach is a much better "standardized approach" for package naming.   It would be great if conda-build just used it, but provided a "escape-hatch" for users of conda-build that for what-ever reason want to use a different package-naming convention in their collections.

**Comment by ilanschnell** [comment]
I would argue that having both the hash and explicit naming is somehow confusing, as the both contain the same information (but in different ways).  The default build string could always be a pure hashsum, but I'm not very concerned about the default.

What I think wold be useful is a `--build-string` option would overwrite the default hash.  The `--build-string` option is also more flexible for possible future conventions which some people might want to implement.

**Comment by msarahan** [comment]
The hash is only an addition to the previous build string behavior.  Hashes do not replace things like py27 or np111, they only supplement them.  Furthermore, the automatic determination logic only takes effect if the ``build/string`` field is not defined in meta.yaml.  @teoliphant I believe that defining the ``build/string`` field in meta.yaml provides the customization that you're after.  Perhaps the flag added by this PR would be better named ``--no-hash-in-build-string``

I don't see good reason to replace the existing customization of the build string via meta.yaml with a CLI flag that would presumably be set to some static string.  Do you?  It would be much less flexible than the existing scheme (no jinja2 templating at all)

**Comment by msarahan** [comment]
Discussed with @ilanschnell during standup this morning.  Option added by this PR is acceptable.

**Pull request merged**
