### PR TITLE
Fix ZeroDivisionError in ELF sections that have no entry table

### PR DESCRIPTION
**Pull request by ChristopherHogan**
I'm trying to create a conda package for Guile (GNU Scheme) at conda-forge/staged-recipes#6564. Guile's [object file format](https://www.gnu.org/software/guile/manual/html_node/Object-File-Format.html) with the `.go` extension uses ELF, but doesn't include all the sections that a normal shared object would include, particularly the `.dynstr` section:

```
cannot find section .dynstr
patchelf: --print-rpath failed for /home/conda/feedstock_root/build_artifacts/guile_1548869580275/_h_env_placehold.../lib/guile/2.2/ccache/ice-9/time.go
```
Additionally, attempting to create an `elffile` instance from these objects results in a zero division error:
```
raceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 130, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 120, in build_folders
    conda_build.api.build(list(d.keys()), config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1628, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 954, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 818, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 1018, in post_build
    check_overlinking(m, files)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 955, in check_overlinking
    m.config.channel_urls)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 882, in check_overlinking_impl
    build_prefix, build_prefix_substitution)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 603, in _collect_needed_dsos
    envroot=run_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 606, in __call__
    value = self.func(*args, **kw)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 635, in get_linkages_memoized
    recurse=recurse, sysroot=sysroot, envroot=envroot, arch=arch)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 419, in get_linkages
    sysroot=sysroot, arch=arch)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 1138, in inspect_linkages
    filename, sysroot=sysroot, arch=arch)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 1082, in _inspect_linkages_this
    cf = codefile(ReadCheckWrapper(f), arch)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 1000, in codefile
    return elffile(file, list(initial_rpaths_transitive))
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 871, in __init__
    es.postprocess(self, file)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 779, in postprocess
    for m in range(int(self.sh_size / self.sh_entsize)):
ZeroDivisionError: division by zero
```
This PR ensures Guile `.go` files don't get treated as ELF shared objects, although I'm uncertain if any type of relocation is necessary for these files. The manual says

> One ELF segment is marked as “dynamic”, meaning that it has data of interest to the loader. Guile uses this segment to record the Guile version corresponding to this file. There is also an entry in the dynamic segment that points to the address of an initialization thunk that is run to perform any needed link-time initialization. **(This is like dynamic relocations for normal ELF shared objects, except that we compile the relocations as a procedure instead of having the loader interpret a table of relocations.)** Finally, the dynamic segment marks the location of the “entry thunk” of the object file. This thunk is returned to the caller of load-thunk-from-memory or load-thunk-from-file. When called, it will execute the “body” of the compiled expression.

I verified that a Guile package built with this change is usable in a test environment.

### CODE REVIEW

**Comment by msarahan** [comment]
This seems fine to me.  @nehaljwani @mingwandroid any opinion here?

**Comment by mingwandroid** [comment]
If `.go` files are ELF files then I'd like as much of our sanity checking tooling to operate on them as possible. Therefore you should add a special case so that `patchelf` is allowed to fail.

However, due to bugs in `patchelf` we are likely going to start making more use of `LIEF` which is able to modify `rpaths`.

`LIEF` will also phase out all use of `pyldd.py` once I get round to it, again in the meantime, I'd rather we make `pyldd.py` not perform a division by zero here.

**Comment by ChristopherHogan** [comment]
Comments addressed, and ready for review.

**Comment by mingwandroid** [comment]
Thank you @ChristopherHogan, I will try to rebase my branch that changes a lot of this stuff (that moves towards replacing `patchelf` with `LIEF`) on top of this now.

Do you think it worthwhile to add some tests either that guile files can be processed by our elf patching mechanism or to ensure that these specific bugs do not happen again? Are they arch and/or OS independent, beyond being ELF files? To me it appears that way.

**Comment by mingwandroid** [comment]
Can you rebase this PR on top of the latest conda-build master branch please?

**Comment by ChristopherHogan** [comment]
Rebased.

> Are they arch and/or OS independent, beyond being ELF files?

As far as I can tell, yes.

> Do you think it worthwhile to add some tests either that guile files can be processed by our elf patching mechanism or to ensure that these specific bugs do not happen again?

If it's easy to set up, it wouldn't hurt.

**Comment by ChristopherHogan** [comment]
I added a test to make sure Guile `.go` files run through the elf patching process.

**Comment by msarahan** [comment]
This is rolled into #3409 - closing

**Pull request closed without merging**
