### PR TITLE
Fix pin compatible dependencies by removing tilde from dependency

### LINKED ISSUE #2351: conda skeleton leaves tilde chars from requires.txt
Running conda skeleton pypi fs gives

requirements:
  build:
    - python
    - setuptools
    - appdirs~ 1.4.3
    - pytz
    - setuptools
    - six~ 1.10.0
  run:
    - python
    - setuptools
    - appdirs~ 1.4.3
    - pytz
    - setuptools
    - six~ 1.10.0

### PR DESCRIPTION
**Pull request by mandeep**
fixes #2351 

This PR adds pin compatible versioning functionality to the PyPI skeleton. For example, a version listed as ``package ~= 1.4.3`` will be converted to ``package >=1.4.3,<2``.

The error stems from https://github.com/conda/conda/blob/master/conda/cli/common.py#L106 so I'll be submitting a PR there as well. 

Tests look fine locally.

### CODE REVIEW

**Comment by nehaljwani** [comment]
I could be mistaken, but shouldn't `package ~= 1.4.3` mean `package >=1.4.3,<1.4.4`? https://stackoverflow.com/a/39590286/1005215

**Comment by nehaljwani** [comment]
As mentioned in the spec at https://www.python.org/dev/peps/pep-0440/#compatible-release, the example is:
```
~= 1.4.5
>= 1.4.5, == 1.4.*
```

**Comment by msarahan** [comment]
I need to read the pep again. I'll do whatever the pep says. Thanks @mandeep for following up on this.

**Comment by msarahan** [comment]
My reading of the pep is that for a given spec with n places pinned, the upper bound has n-1 places pinned.

1.2.3  has 3 places pinned, so the upper bound should be 1.3

I can work on this later, Mandeep. It would make a lot of sense to use existing logic for this.

**Comment by mandeep** [comment]
I've committed a change to reflect PEP 440. If there's some existing logic that you want me to take a look at just let me know.

**Comment by msarahan** [comment]
This still needs a tiny bit more work.  As the pep mentions, post-versions need to be ignored.  I think the current count will include them.

```
~= 2.2.post3
>= 2.2.post3, == 2.*
```

**Comment by mandeep** [comment]
Do I need to factor in other release types besides pre, post, and developmental?

**Comment by msarahan** [comment]
Only whatever is listed in pep440.  I think in addition to the 3 you listed, there's also alpha, beta, and rc.  I think alpha and beta may be just one letter, too.

**Comment by mandeep** [comment]
@msarahan I added support for pre and post releases per PEP 440. I also included a test for the new function that I created to make sure versions are converted correctly.

**Comment by msarahan** [comment]
Sorry this slipped past me @mandeep.  This is nice work.  Thanks for fixing this up.

**Pull request merged**
