### PR TITLE
convert popen args to bytestrings if unicode

### LINKED ISSUE #1412: env vars must be bytestrings on Windows
Some recipes are failing when `conda-build` tries to apply the patch:

```shell
Source cache directory is: C:\Miniconda\conda-bld\src_cache
Downloading source to cache: freexl-1.0.2.tar.gz
Downloading http://www.gaia-gis.it/gaia-sins/freexl-1.0.2.tar.gz
Success
Applying patch: u'C:\\projects\\conda-recipes\\recipes\\freexl\\makefile.vc.patch'
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-all-script.py", line 11, in <module>
    load_entry_point('conda-build-all==1.0.0', 'console_scripts', 'conda-build-all')()
  File "C:\Miniconda\lib\site-packages\conda_build_all\cli.py", line 90, in main
    b.main()
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 263, in main
    built_dist_location = self.build(meta, build_config)
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 200, in build
    conda_build.api.build(meta.meta, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1004, in build_tree
    config=recipe_config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 593, in build
    config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 87, in parse_or_try_download
    source.provide(metadata.path, metadata.get_section('source'), config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 509, in provide
    apply_patch(src_dir, join(recipe_dir, patch), config, git)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 468, in apply_patch
    check_call_env([patch] + patch_args, cwd=src_dir)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 462, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 458, in _func_defaulting_env_to_os_environ
    return func(*popenargs, **kwargs)
  File "C:\Miniconda\lib\subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Miniconda\lib\subprocess.py",
```

Full log https://ci.appveyor.com/project/comtbot/conda-recipes/build/job/kxq68fcnidpdj2kr and recipe https://github.com/ioos/conda-recipes/tree/master/recipes/freexl

(Tried to fix this in https://github.com/conda/conda-build/pull/1377 and https://github.com/conda/conda-build/pull/1383 but gave up because I do not have a Windows machine to finish it :unamused:)

### PR DESCRIPTION
**Pull request by msarahan**
fixes #1412 

confirmed by building freexl for py27 and py35 on win.

### CODE REVIEW

**Comment by msarahan** [comment]
Sorry this didn't make it into the release yesterday.  I'll try to have more stuff for another release soon.

**Comment by ocefpaf** [comment]
@msarahan do you think we can get a new release? We have a Python course coming up and new packages with `conda-build 2` on Windows will be most welcomed to avoid things like https://github.com/conda-forge/hdf5-feedstock/issues/41

**Comment by msarahan** [comment]
Sure - I can tag this pretty much right away, but packages might not get built until Monday (unless the updating CF repo is an option for you.)

**Comment by ocefpaf** [comment]
No worries. I won't be back in office until Tuesday, and I will be teaching only the week after that.

**Comment by ocefpaf** [comment]
I just tried to re-start AppVeyor and it seems that the issue is still there even with `conda-build 2.0.3`. See
https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.2199/job/wurppplai2900sb9#L76

I just got back home... will take a better look at this tomorrow.

**Pull request merged**
