### PR TITLE
Fix apply selectors

### PR DESCRIPTION
**Pull request by CJ-Wright**
Attn:
@isuruf

### CODE REVIEW

**Comment by CJ-Wright** [comment]
I haven't tested it yet. (I'm running some experiments rn)

**Comment by CJ-Wright** [comment]
This worked on my local.

**Comment by msarahan** [comment]
Test fails look unrelated.  Is there a test we can add for this?

**Comment by CJ-Wright** [comment]
Maybe? @isuruf thoughts?

**Comment by msarahan** [comment]
Merging for now.  If anyone would like to add a test later, please put up another PR.

**Pull request merged**
