### PR TITLE
WIP: --extra-specs for conda-skeleton.

### PR DESCRIPTION
**Pull request by rainwoodman**
Proposed solution to Issue #1697.

- the documentation / guides may need changes.
- we may be able to change the current numpy heuristics to the default value of --extra-specs.

### CODE REVIEW

**Comment by msarahan** [comment]
I can't remember exactly how this works.  I kind of think that the root environment is the one used to run setup.py right now.  This is not desirable.  It should be a purpose-built environment.  I may be getting mixed up between this skeletonize operation and the reading of setup.py for Jinja2 templating.  Both should be using a build environment, and I think your approach here is a good generalization for numpy.  If there are few enough special cases to handle (numpy, cython, what else?) then maybe it makes sense to add your option, but keep the special cases to make life easier for people.

**Comment by rainwoodman** [comment]
- In current master, The call to `create_env` in `pypi.py` appears to create a purpose-built env, not using `root`.

- I thought the sketonize has to run setup.py in the purpose-built env to extra values for 'template building'. But I never really read the portion of code about templates.

- `numpy, cython, mpi4py`, are those I know of; but we cannot really speak for other users. Potential other cases where setup.py may need other package are code generation with other conda packages, e.g. linking against GPU libraries or using LLVM? 

- One can use a static source code analyze tool to find all Python imports from setup.py and build a list from that -- but then it is going to be difficult to relate the module name to the conda package name. This is why I believe the proposed --extra_specs makes more sense.

- I don't know if this is possible with conda -- pinning against any package? We will run into issues when the binary extensions depend on each other in a binary incompatiable way. But this is probably a separate thread.

**Comment by msarahan** [comment]
The Travis failure is just a race condition failure that I'm working on.  Appveyor is a separate unrelated issue that I think is fixed on master.  No need to rebase.  I'll work it out elsewhere.

Would you mind adding a test for this?  You can probably mostly copy the existing tests in test_api_skeleton.py, but point to recipe that needs cython or mpi4py, and demonstrate both that 1) the recipe fails without specifying your new option and 2) that it works when your option is specified.

Are you willing/able to sign the CLA?  If so, please do so.  Otherwise, please let me know who your employer is, and I'll need to review these changes with the higher ups.  Email me if you'd prefer: msarahan@continuum.io

**Comment by rainwoodman** [comment]
I didn't demontrate 1) (not sure how to capture the exceptions), but I demonstrated 2). I made an attempt at the CLA. My employer is UC Berkeley and I could only find a FAQ page on IP and software which didn't really say much about contribution to other projects.

**Comment by msarahan** [comment]
Thanks.  There were a couple of timeouts in the Travis tests.  No big deal.  Appveyor's in good shape.

For your future reference, you can catch exceptions in pytest like this:

```
def test_failed_tests_exit_build(testing_workdir, test_config):
    """https://github.com/conda/conda-build/issues/1112"""
    with pytest.raises(SystemExit) as exc:
        api.build(os.path.join(metadata_dir, "_test_failed_test_exits"), config=test_config)
        assert 'TESTS FAILED' in exc
```

(from https://github.com/conda/conda-build/blob/master/tests/test_api_build.py#L371-L375)

It is extremely handy for getting coverage of those annoying hard-to-cover bits of exception handling code.

**Pull request merged**
