### PR TITLE
Test binaries passed to `setup` via `scripts` keyword argument using `--help`

### PR DESCRIPTION
**Pull request by jakirkham**
Just included everything passed to `scripts` in the `--help` tests. This will help improve testing for Python packages not leveraging the keyword arguments added by `bdist_conda`. Also, it applies a reasonable on all other Python packages (namely having basic help for command line tools).

As this is something `argparse` pretty much handles (or the deprecated `optparse`), this seems like a reasonable constraint.

### CODE REVIEW

**Comment by jakirkham** [comment]
This appears to be passing on my branch with Travis and my own local testing. However, Travis' web interface has been down so I have been unable to look at their logs more closely.

**Comment by jakirkham** [comment]
Any thoughts on this @asmeurer? Open to suggestions as always.

**Comment by asmeurer** [comment]
Not all scripts support --help but it's good enough practice that I'm in favor of doing this.

**Comment by jakirkham** [comment]
Cool. I was trying to think if there were ways I might improve on this. Even though you have merged this, if you do have more thoughts, I am willing to contribute changes to improve this check.

**Pull request merged**
