### PR TITLE
Versioneer 0.14

### PR DESCRIPTION
**Pull request by jakirkham**
Sorry, thought I had added this. Versioneer 0.14 generate PEP440 compatible versions for every commit not only releases. It explicitly states the number of commits since the last release and short SHA of the commit so as to be unique (hopefully collisions aside).

### CODE REVIEW

**Comment by asmeurer** [comment]
I am +1. @ilanschnell do you have any comments? This changes the format of the versions

```
$conda build -V
conda-build 1.12.0+18.gb0e6ef3
```

**Comment by ilanschnell** [comment]
Does the new version format have any advantages?

**Comment by asmeurer** [comment]
It's PEP 440 compatible.

**Comment by ilanschnell** [comment]
Yes, In that case I'm also +1, as we want to move to PEP 440.

**Comment by jakirkham** [comment]
Please let me know if you guys have feedback.

**Comment by asmeurer** [comment]
Let's merge it and see if there are any problems. If there aren't, let's do the same for conda.

**Pull request merged**
