### PR TITLE
Add windows platform on Azure

### PR DESCRIPTION
**Pull request by marcelotrevisani**
* Add windows platform on Azure
* Remove appveyor

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
If it pass, we need to deactivate ``appveyor`` after we integrated it to the master

**Comment by marcelotrevisani** [comment]
There are two tests failing on windows
 * test_build_string_does_not_incorrectly_add_hash
 * test_debug_recipe_default_path

**Comment by marcelotrevisani** [comment]
Finally! :tada: :tada: :tada: :tada: 
hahaha

I think it is ready to be integrated!

**Comment by mingwandroid** [comment]
Got thumbs up for merging from Mike and Jonathan. Thanks.

**Comment by msarahan** [comment]
This is really stellar!  Thanks @marcelotrevisani!

**Pull request merged**
