### PR TITLE
Fix convert paths [WIP]

### LINKED ISSUE #2501: After conda-convert from win -> unix, can only install using "-c file://some/dir"
Hello!

I am on a windows machine and I am trying build an osx-64 package. I run the following commands:
* ```conda build --py 3.6 --output-folder output```
* ```conda convert -p osx-64 -o output output\win-64\{my_package}.tar.bz2```
* ```conda index output\osx-64```
* ```anaconda upload output\osx-64\{my_package}.tar.bz2```

```output\osx-64``` now contains {my_package}.tar.bz2, repodata.json, .paths.json, etc. My anaconda cloud account contains just the {my_package}.tar.bz2 file.

I copy the whole ```output``` folder to my osx machine, and run the following commands:

* ```conda create --name new_blank_env```
* ```source activate new_blank_env```
* ```conda install -c file:///path/to/output {my_package} --use-local```

The install will prompt to me to install new packages, I say 'y'. My conda package installs correctly, without hitch.

_HOWEVER_, if I run:

* ```conda create --name new_blank_env```
* ```source activate new_blank_env```
* ```conda install -c {my_username} {my_package}```

The install will prompt to me to install new packages, I say 'y'. The install will then hang for a few minutes, spitting out this error:

```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'file:///path/to/output::{my_package}'.
CondaError: Cannot link a source that does not exist. /anaconda3/pkgs/{my_package}/lib\python3.6\site-packages\{my_package}.egg-info\PKG-INFO
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.

CondaError: Cannot link a source that does not exist. /anaconda3/pkgs/{my_package}/lib\python3.6\site-packages\{my_package}.egg-info\PKG-INFO
Running `conda clean --packages` may resolve your problem.
```

Interestingly enough, that same error exists if I run ```conda install -c file:///path/to/output {my_package}``` without --use-local

I ran 'conda clean --packages' and it did not fix the issue. You may notice that the error contains a unix path mixed with a windows path: I checked, ```/anaconda3/pkgs/{my_package}/lib/python3.6/site-packages/{my_package}.egg-info/PKG-INFO``` _DOES_ exist.

[Here is my conda env in root](https://github.com/conda/conda-build/files/1476262/conda_list_of_root.txt), I  am running ```conda-build               3.0.27           py36hb78d8cd_0```

Here is the DEBUG output of ```conda install -c {my_username} {my_package} -v -v &> conda_install_debug.txt```: [conda_install_debug.txt](https://github.com/conda/conda-build/files/1476279/conda_install_debug.txt)

Let me know if you need any more information from me, thanks!

### PR DESCRIPTION
**Pull request by mandeep**
fixes #2501

Replaced 'lib/site-packages' with os.path.join to join the two directories. After fixing this, I was able to successfully install a package as instructed in #2501.

Also added an indent to the dump to paths.json as I found the sometimes the file wasn't indented.

Edit: I'm starting to see some errors so let me see what else I can try.

### CODE REVIEW

**Comment by mandeep** [comment]
@msarahan ready for review

**Comment by msarahan** [comment]
Thanks @mandeep for tackling this.  Is there a test that is worth adding?  If not, I'm happy enough with the code here to merge.

**Comment by mandeep** [comment]
I'm not sure if I there's a test to be added here. The paths are handled fine by the different operating systems. I think this is mostly a workaround for conda.

**Comment by msarahan** [comment]
great, works for me.  Thanks again.

**Comment by mandeep** [comment]
No problem!

**Pull request merged**
