### PR TITLE
Add *_constrains run_export types

### PR DESCRIPTION
**Pull request by mbargull**
@isuruf, is this what you had in mind for adding `constrains: ['__glibc >=2.17']` automatically from, e.g., `sysroot_linux-64`?

### CODE REVIEW

**Comment by mbargull** [comment]
(Needs tests and news entry.)

**Comment by isuruf** [comment]
Looks good. Thanks @mbargull

**Comment by mingwandroid** [comment]
Thanks! Can you add some docs though and a news entry please and I'll start thinking about the next CB release.

**Comment by mingwandroid** [comment]
Oh, a test would be great too.

**Comment by isuruf** [comment]
Here's an example of a test https://github.com/conda/conda-build/pull/3868/files#diff-f13446e8df3ae23003517f6e3b56c40efebd9475c5d6d814811a18afc6569443

**Comment by mbargull** [comment]
> I'll start thinking about the next CB release.

Nice! I'll add the missing pieces to this PR either this evening or earlier tomorrow.

**Comment by mbargull** [comment]
Test failures are unrelated (connection issues).
This is ready to go!

**Comment by mingwandroid** [comment]
Thanks @mbargull and @isuruf.

**Pull request merged**
