### PR TITLE
[WIP] Speed up fixing linking phase for macos binary builds

### PR DESCRIPTION
**Pull request by rlizzo**
This PR is in relation to Issue https://github.com/conda/conda-build/issues/2291

On MacOS, when building relocatable binaries the the post build "fixing linking" stage can take hours to complete on a large library (VTK, QT). I've traced the main source of the issue to a single function that is repeatedly called for every shared library that is examined. 

 **I see a 21% reduction in the time spent on this last phase (on a common library I compile it went from from 628.304 sec before to 498.068 sec after) when building the ITK library**

The line profile output pasted below traces the major time suck from post build instantiation to the problem function. 

```
Total time: 606.69 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: post_build at line 455

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   455                                           @do_profile(follow=[mk_relative])
   456                                           def post_build(m, files, prefix, build_python, croot):
   457         1           45     45.0      0.0      print('number of files:', len(files))
   458         1       335402 335402.0      0.1      fix_permissions(files, prefix)
   459                                           
   460      4607         3736      0.8      0.0      for f in files:
   461      4606       166853     36.2      0.0          make_hardlink_copy(f, prefix)
   462                                           
   463         1            1      1.0      0.0      if sys.platform == 'win32':
   464                                                   return
   465                                           
   466         1           31     31.0      0.0      binary_relocation = m.binary_relocation()
   467         1            0      0.0      0.0      if not binary_relocation:
   468                                                   print("Skipping binary relocation logic")
   469         1            7      7.0      0.0      osx_is_app = bool(m.get_value('build/osx_is_app', False)) and sys.platform == 'darwin'
   470                                           
   471         1       110099 110099.0      0.0      check_symlinks(files, prefix, croot)
   472                                           
   473      4607         6357      1.4      0.0      for f in files:
   474      4606         4815      1.0      0.0          if f.startswith('bin/'):
   475         1         1077   1077.0      0.0              fix_shebang(f, prefix=prefix, build_python=build_python, osx_is_app=osx_is_app)
   476      4606         2461      0.5      0.0          if binary_relocation is True or (isinstance(binary_relocation, list) and
   477                                                                                    f in binary_relocation):
   478      4606    606058739 131580.3     99.9              mk_relative(m, f, prefix)

Timer unit: 1e-06 s

Total time: 606.04 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: mk_relative at line 403

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   403                                           def mk_relative(m, f, prefix):
   404      4606         4165      0.9      0.0      assert sys.platform != 'win32'
   405      4606        32170      7.0      0.0      path = os.path.join(prefix, f)
   406      4606       369296     80.2      0.1      if not is_obj(path):
   407      4520         3254      0.7      0.0          return
   408                                           
   409        86          140      1.6      0.0      if sys.platform.startswith('linux'):
   410                                                   mk_relative_linux(f, prefix=prefix, rpaths=m.get_value('build/rpaths', ['lib']))
   411        86           51      0.6      0.0      elif sys.platform == 'darwin':
   412        86    605630470 7042214.8     99.9          mk_relative_osx(path, prefix=prefix)


Total time: 1.90857 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: mk_relative_osx at line 333

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   333                                           @do_profile(follow=[macho.install_name_change])
   334                                           def mk_relative_osx(path, prefix, build_prefix=None):
   335                                               '''
   336                                               if build_prefix is None, then this is a standard conda build. The path
   337                                               and all dependencies are in the build_prefix.
   338                                           
   339                                               if package is built in develop mode, build_prefix is specified. Object
   340                                               specified by 'path' needs to relink runtime dependences to libs found in
   341                                               build_prefix/lib/. Also, in develop mode, 'path' is not in 'build_prefix'
   342                                               '''
   343         1            6      6.0      0.0      if build_prefix is None:
   344         1            2      2.0      0.0          assert path.startswith(prefix + '/')
   345                                               else:
   346                                                   prefix = build_prefix
   347                                           
   348         1          125    125.0      0.0      assert sys.platform == 'darwin' and is_obj(path)
   349         1      1874056 1874056.0     98.2      s = macho.install_name_change(path, partial(osx_ch_link, prefix=prefix))
   350                                           
   351         1        12561  12561.0      0.7      names = macho.otool(path)
   352         1            2      2.0      0.0      if names:
   353                                                   # Add an rpath to every executable to increase the chances of it
   354                                                   # being found.
   355         1           28     28.0      0.0          rpath = os.path.join('@loader_path',
   356         1           30     30.0      0.0                       os.path.relpath(os.path.join(prefix, 'lib'),
   357         1          110    110.0      0.0                               os.path.dirname(path)), '').replace('/./', '/')
   358         1         7884   7884.0      0.4          macho.add_rpath(path, rpath, verbose=True)
   359                                           
   360                                                   # 10.7 install_name_tool -delete_rpath causes broken dylibs, I will revisit this ASAP.
   361                                                   # .. and remove config.build_prefix/lib which was added in-place of
   362                                                   # DYLD_FALLBACK_LIBRARY_PATH since El Capitan's SIP.
   363                                                   # macho.delete_rpath(path, config.build_prefix + '/lib', verbose = True)
   364                                           
   365         1            2      2.0      0.0      if s:
   366                                                   # Skip for stub files, which have to use binary_has_prefix_files to be
   367                                                   # made relocatable.
   368         1        13767  13767.0      0.7          assert_relative_osx(path, prefix)

Total time: 1.87402 s
File: /Users/rick/projects/conda-build/conda_build/os_utils/macho.py
Function: install_name_change at line 227

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   227                                           def install_name_change(path, cb_func, verbose=False):
   228                                               """Change dynamic shared library load name or id name of Mach-O Binary `path`.
   229                                           
   230                                               `cb_func` is called for each shared library load command. The dictionary of
   231                                               the load command is passed in and the callback returns the new name or None
   232                                               if the name should be unchanged.
   233                                           
   234                                               When dealing with id load commands, `install_name_tool -id` is used.
   235                                               When dealing with dylib load commands `install_name_tool -change` is used.
   236                                               """
   237         1        19405  19405.0      1.0      dylibs = otool(path)
   238         1            1      1.0      0.0      changes = []
   239         4            6      1.5      0.0      for index, dylib in enumerate(dylibs):
   240         3      1854599 618199.7     99.0          new_name = cb_func(path, dylib)
   241         3            7      2.3      0.0          if new_name:
   242                                                       changes.append((index, new_name))
   243                                           
   244         1            1      1.0      0.0      ret = True
   245         1            1      1.0      0.0      for index, new_name in changes:
   246                                                   args = ['install_name_tool']
   247                                                   if dylibs[index]['cmd'] == 'LC_ID_DYLIB':
   248                                                       args.extend(('-id', new_name, path))
   249                                                   else:
   250                                                       args.extend(('-change', dylibs[index]['name'], new_name, path))
   251                                                   if verbose:
   252                                                       print(' '.join(args))
   253                                                   p = Popen(args, stderr=PIPE)
   254                                                   _, stderr = p.communicate()
   255                                                   stderr = stderr.decode('utf-8')
   256                                                   if "Mach-O dynamic shared library stub file" in stderr:
   257                                                       print("Skipping Mach-O dynamic shared library stub file %s" % path)
   258                                                       ret = False
   259                                                       continue
   260                                                   else:
   261                                                       print(stderr, file=sys.stderr)
   262                                                   if p.returncode:
   263                                                       raise RuntimeError("install_name_tool failed with exit status %d"
   264                                                           % p.returncode)
   265         1            0      0.0      0.0      return ret

Total time: 0.64057 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: osx_ch_link at line 294

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   294                                           @do_profile(follow=[find_lib])
   295                                           def osx_ch_link(path, link_dict, prefix):
   296         1            2      2.0      0.0      link = link_dict['name']
   297         1            9      9.0      0.0      print("Fixing linking of %s in %s" % (link, path))
   298         1       640557 640557.0    100.0      link_loc = find_lib(link, prefix, path)
   299         1            1      1.0      0.0      if not link_loc:
   300         1            1      1.0      0.0          return
   301                                           
   302                                               lib_to_link = os.path.relpath(os.path.dirname(link_loc), 'lib')
   303                                               # path_to_lib = utils.relative(path[len(prefix) + 1:])
   304                                           
   305                                               # e.g., if
   306                                               # path = '/build_prefix/lib/some/stuff/libstuff.dylib'
   307                                               # link_loc = 'lib/things/libthings.dylib'
   308                                           
   309                                               # then
   310                                           
   311                                               # lib_to_link = 'things'
   312                                               # path_to_lib = '../..'
   313                                           
   314                                               # @rpath always means 'lib', link will be at
   315                                               # @rpath/lib_to_link/basename(link), like @rpath/things/libthings.dylib.
   316                                           
   317                                               # For when we can't use @rpath, @loader_path means the path to the library
   318                                               # ('path'), so from path to link is
   319                                               # @loader_path/path_to_lib/lib_to_link/basename(link), like
   320                                               # @loader_path/../../things/libthings.dylib.
   321                                           
   322                                               ret = '@rpath/%s/%s' % (lib_to_link, os.path.basename(link))
   323                                           
   324                                               # XXX: IF the above fails for whatever reason, the below can be used
   325                                               # TODO: This might contain redundant ..'s if link and path are both in
   326                                               # some subdirectory of lib.
   327                                               # ret = '@loader_path/%s/%s/%s' % (path_to_lib, lib_to_link, basename(link))
   328                                           
   329                                               ret = ret.replace('/./', '/')
   330                                           
   331                                               return ret

Total time: 0.640287 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: find_lib at line 256

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   256                                           def find_lib(link, prefix, path=None):
   257         1       640282 640282.0    100.0      files = utils.prefix_files(prefix)
   258         1            3      3.0      0.0      if link.startswith(prefix):
   259                                                   link = os.path.normpath(link[len(prefix) + 1:])
   260                                                   if link not in files:
   261                                                       sys.exit("Error: Could not find %s" % link)
   262                                                   return link
   263         1            1      1.0      0.0      if link.startswith('/'):  # but doesn't start with the build prefix
   264                                                   return
   265         1            1      1.0      0.0      if link.startswith('@rpath/'):
   266                                                   # Assume the rpath already points to lib, so there is no need to
   267                                                   # change it.
   268         1            0      0.0      0.0          return
   269                                               if '/' not in link or link.startswith('@executable_path/'):
   270                                                   link = os.path.basename(link)
   271                                                   file_names = defaultdict(list)
   272                                                   for f in files:
   273                                                       file_names[os.path.basename(f)].append(f)
   274                                                   if link not in file_names:
   275                                                       sys.exit("Error: Could not find %s" % link)
   276                                                   if len(file_names[link]) > 1:
   277                                                       if path and os.path.basename(path) == link:
   278                                                           # The link is for the file itself, just use it
   279                                                           return path
   280                                                       # Allow for the possibility of the same library appearing in
   281                                                       # multiple places.
   282                                                       md5s = set()
   283                                                       for f in file_names[link]:
   284                                                           md5s.add(md5_file(os.path.join(prefix, f)))
   285                                                       if len(md5s) > 1:
   286                                                           sys.exit("Error: Found multiple instances of %s: %s" % (link, file_names[link]))
   287                                                       else:
   288                                                           file_names[link].sort()
   289                                                           print("Found multiple instances of %s (%s).  "
   290                                                               "Choosing the first one." % (link, file_names[link]))
   291                                                   return file_names[link][0]
   292                                               print("Don't know how to find %s, skipping" % link)

Total time: 0.778892 s
File: /Users/rick/projects/conda-build/conda_build/utils.py
Function: prefix_files at line 1191

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
  1191                                           @do_profile(follow=[expand_globs])
  1192                                           def prefix_files(prefix):
  1193                                               '''
  1194                                               Returns a set of all files in prefix.
  1195                                               '''
  1196         1            1      1.0      0.0      res = set()
  1197       661       115461    174.7     14.8      for root, dirs, files in os.walk(prefix):
  1198     15613         5958      0.4      0.8          for fn in files:
  1199     14953        59731      4.0      7.7              res.add(join(root, fn)[len(prefix) + 1:])
  1200      1320          644      0.5      0.1          for dn in dirs:
  1201       660         2639      4.0      0.3              path = join(root, dn)
  1202       660         5526      8.4      0.7              if islink(path):
  1203         1            2      2.0      0.0                  res.add(path[len(prefix) + 1:])
  1204         1       588928 588928.0     75.6      res = set(expand_globs(res, prefix))
  1205         1            2      2.0      0.0      return res

Total time: 0.530403 s
File: /Users/rick/projects/conda-build/conda_build/utils.py
Function: expand_globs at line 767

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   767                                           def expand_globs(path_list, root_dir):
   768         1            1      1.0      0.0      files = []
   769     14955        12271      0.8      2.3      for path in path_list:
   770     14954        39512      2.6      7.4          if not os.path.isabs(path):
   771     14954        67470      4.5     12.7              path = os.path.join(root_dir, path)
```
```python
   772     14954       378640     25.3     71.4          if os.path.islink(path) or os.path.isfile(path):
```
```
   773     14954        14897      1.0      2.8              files.append(path)
   774                                                   elif os.path.isdir(path):
   775                                                       files.extend(os.path.join(root, f) for root, _, fs in os.walk(path) for f in fs)
   776                                                   else:
   777                                                       # File compared to the globs use / as separator indenpendently of the os
   778                                                       glob_files = glob(path)
   779                                                       if not glob_files:
   780                                                           log = get_logger(__name__)
   781                                                           log.error('invalid recipe path: {}'.format(path))
   782                                                       files.extend(glob_files)
   783         1          150    150.0      0.0      prefix_path_re = re.compile('^' + re.escape('%s%s' % (root_dir, os.path.sep)))
   784         1        17461  17461.0      3.3      files = [prefix_path_re.sub('', f, 1) for f in files]
   785         1            1      1.0      0.0      return files
```

Since this is a function that is called by a wide variety of other functions, the most general way to speed this up that I could think of was to split the path operation into an separate elif statements so we don't check the os.path.islink(path) if we don't need to. (os.path.isfile(path)) had ~80% hit rate in my very preliminary tests. 

There are a whole lot more optimizations to make here (I have a hunch that this is calculating the same thing over and over again, since the prefix that we are walking over shouldn't change often - if at all??). Looking forward to hearing your feedback.

### CODE REVIEW

**Comment by msarahan** [comment]
great start!  How are you getting your line profile info?  I'd like to combine any instructions you have with my instructions for doing the pytest-profiling stuff.

I'll take an in-depth look at this in a little while, but I'm very impressed with what you have so far.  I agree with your hunch that you should be able to assume that the prefix doesn't change.  If it were changing at this point, there would be much bigger problems.

**Comment by rlizzo** [comment]
That's an interesting idea. Looking forward to testing it out myself tonight. I was thinking more of a stateful dictionary, with files that we've already seen as the key, the the value a bool of weather to include them in the files list. 

Since these functions aren't mac OS specific, it might be cleaner to split this off into it's own methods? That or start passing in some kwargs to change function behavior.   Not entirely sure what the most pythonic way is  yet. Need to put some more thought into it.

l'll send you the profiling code when I can get to a computer later. Currently dictating this in the car.

**Comment by msarahan** [comment]
This latest idea is from @mingwandroid.  I think it's the best approach.  It avoids any complexity around caching not working right, and achieves the same purpose.  Please give it a spin tonight and let us know how it goes.

**Comment by rlizzo** [comment]
Will do. Thanks

**Comment by rlizzo** [comment]
Holy hell guys. This is incredible. 

I just rebuild ITK again and went **from 628 seconds to 7 seconds!** I did this again for the worst case library I have to distribute (VTK). Before this it went through the "fixing linking" phase for over an 1hr40min (6000 seconds). it is now 7.4 mins (445 seconds) 

I'm seeing between **98% to 93% speedups**! 

I went through the call stack again to see what was going on. Heres the result:

```
Total time: 7.09459 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: post_build at line 453

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   453                                           @do_profile(follow=[mk_relative])
   454                                           def post_build(m, files, prefix, build_python, croot):
   455         1           30     30.0      0.0      print('number of files:', len(files))
   456         1       343741 343741.0      4.8      fix_permissions(files, prefix)
   457                                           
   458      4607         3830      0.8      0.1      for f in files:
   459      4606       162050     35.2      2.3          make_hardlink_copy(f, prefix)
   460                                           
   461         1            1      1.0      0.0      if sys.platform == 'win32':
   462                                                   return
   463                                           
   464         1           55     55.0      0.0      binary_relocation = m.binary_relocation()
   465         1            0      0.0      0.0      if not binary_relocation:
   466                                                   print("Skipping binary relocation logic")
   467         1           26     26.0      0.0      osx_is_app = bool(m.get_value('build/osx_is_app', False)) and sys.platform == 'darwin'
   468                                           
   469         1       103857 103857.0      1.5      check_symlinks(files, prefix, croot)
   470         1       580463 580463.0      8.2      prefix_files = utils.prefix_files(prefix)
   471                                           
   472      4607         7619      1.7      0.1      for f in files:
   473      4606         5355      1.2      0.1          if f.startswith('bin/'):
   474         1          687    687.0      0.0              fix_shebang(f, prefix=prefix, build_python=build_python, osx_is_app=osx_is_app)
   475      4606         2789      0.6      0.0          if binary_relocation is True or (isinstance(binary_relocation, list) and
   476                                                                                    f in binary_relocation):
   477      4606      5884083   1277.5     82.9              mk_relative(m, f, prefix, prefix_files)

Total time: 5.86212 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: mk_relative at line 418

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   418                                           def mk_relative(m, f, prefix, files):
   419      4606         4771      1.0      0.1      assert sys.platform != 'win32'
   420      4606        36516      7.9      0.6      path = os.path.join(prefix, f)
   421      4606       426289     92.6      7.3      if not is_obj(path):
   422      4520         3864      0.9      0.1          return
   423                                           
   424        86          157      1.8      0.0      if sys.platform.startswith('linux'):
   425                                                   mk_relative_linux(f, prefix=prefix, rpaths=m.get_value('build/rpaths', ['lib']))
   426        86           71      0.8      0.0      elif sys.platform == 'darwin':
   427        86      5390449  62679.6     92.0          mk_relative_osx(path, prefix=prefix, files=files)

Total time: 0.059418 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: mk_relative_osx at line 331

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   331                                           @do_profile(follow=[macho.install_name_change])
   332                                           def mk_relative_osx(path, prefix, files, build_prefix=None):
   333                                               '''
   334                                               if build_prefix is None, then this is a standard conda build. The path
   335                                               and all dependencies are in the build_prefix.
   336                                           
   337                                               if package is built in develop mode, build_prefix is specified. Object
   338                                               specified by 'path' needs to relink runtime dependences to libs found in
   339                                               build_prefix/lib/. Also, in develop mode, 'path' is not in 'build_prefix'
   340                                               '''
   341         1            2      2.0      0.0      if build_prefix is None:
   342         1            2      2.0      0.0          assert path.startswith(prefix + '/')
   343                                               else:
   344                                                   prefix = build_prefix
   345                                           
   346         1          331    331.0      0.6      assert sys.platform == 'darwin' and is_obj(path)
   347         1        15922  15922.0     26.8      s = macho.install_name_change(path, partial(osx_ch_link, prefix=prefix, files=files))
   348                                           
   349         1        16278  16278.0     27.4      names = macho.otool(path)
   350         1            2      2.0      0.0      if names:
   351                                                   # Add an rpath to every executable to increase the chances of it
   352                                                   # being found.
   353         1            9      9.0      0.0          rpath = os.path.join('@loader_path',
   354         1           38     38.0      0.1                       os.path.relpath(os.path.join(prefix, 'lib'),
   355         1          157    157.0      0.3                               os.path.dirname(path)), '').replace('/./', '/')
   356         1         9942   9942.0     16.7          macho.add_rpath(path, rpath, verbose=True)
   357                                           
   358                                                   # 10.7 install_name_tool -delete_rpath causes broken dylibs, I will revisit this ASAP.
   359                                                   # .. and remove config.build_prefix/lib which was added in-place of
   360                                                   # DYLD_FALLBACK_LIBRARY_PATH since El Capitan's SIP.
   361                                                   # macho.delete_rpath(path, config.build_prefix + '/lib', verbose = True)
   362                                           
   363         1            3      3.0      0.0      if s:
   364                                                   # Skip for stub files, which have to use binary_has_prefix_files to be
   365                                                   # made relocatable.
   366         1        16732  16732.0     28.2          assert_relative_osx(path, prefix)

Total time: 0.015871 s
File: /Users/rick/projects/conda-build/conda_build/os_utils/macho.py
Function: install_name_change at line 227

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   227                                           def install_name_change(path, cb_func, verbose=False):
   228                                               """Change dynamic shared library load name or id name of Mach-O Binary `path`.
   229                                           
   230                                               `cb_func` is called for each shared library load command. The dictionary of
   231                                               the load command is passed in and the callback returns the new name or None
   232                                               if the name should be unchanged.
   233                                           
   234                                               When dealing with id load commands, `install_name_tool -id` is used.
   235                                               When dealing with dylib load commands `install_name_tool -change` is used.
   236                                               """
   237         1        15350  15350.0     96.7      dylibs = otool(path)
   238         1            2      2.0      0.0      changes = []
   239        14           12      0.9      0.1      for index, dylib in enumerate(dylibs):
   240        13          497     38.2      3.1          new_name = cb_func(path, dylib)
   241        13            8      0.6      0.1          if new_name:
   242                                                       changes.append((index, new_name))
   243                                           
   244         1            0      0.0      0.0      ret = True
   245         1            1      1.0      0.0      for index, new_name in changes:
   246                                                   args = ['install_name_tool']
   247                                                   if dylibs[index]['cmd'] == 'LC_ID_DYLIB':
   248                                                       args.extend(('-id', new_name, path))
   249                                                   else:
   250                                                       args.extend(('-change', dylibs[index]['name'], new_name, path))
   251                                                   if verbose:
   252                                                       print(' '.join(args))
   253                                                   p = Popen(args, stderr=PIPE)
   254                                                   _, stderr = p.communicate()
   255                                                   stderr = stderr.decode('utf-8')
   256                                                   if "Mach-O dynamic shared library stub file" in stderr:
   257                                                       print("Skipping Mach-O dynamic shared library stub file %s" % path)
   258                                                       ret = False
   259                                                       continue
   260                                                   else:
   261                                                       print(stderr, file=sys.stderr)
   262                                                   if p.returncode:
   263                                                       raise RuntimeError("install_name_tool failed with exit status %d"
   264                                                           % p.returncode)
   265         1            1      1.0      0.0      return ret


Total time: 0.015732 s
File: /Users/rick/projects/conda-build/conda_build/os_utils/macho.py
Function: otool at line 159

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   159                                           @do_profile(follow=[_get_matching_load_commands])
   160                                           def otool(path, cb_filter=is_dylib_info):
   161                                               """A wrapper around otool -l
   162                                           
   163                                               Parse the output of the otool -l 'load commands', filtered by
   164                                               cb_filter, returning a list of dictionairies for the records.
   165                                           
   166                                               cb_filter receives the whole load command record, including the
   167                                               first line, the 'Load Command N' one. All the records have been
   168                                               pre-stripped of white space.
   169                                           
   170                                               The output of otool -l is entirely freeform; delineation between
   171                                               key and value doesn't formally exist, so that is hard coded. I
   172                                               didn't want to use regexes to parse it for speed purposes.
   173                                           
   174                                               Any key values that can be converted to integers are converted
   175                                               to integers, the rest are strings.
   176                                               """
   177         1        14926  14926.0     94.9      lines = check_output(['otool', '-l', path]).decode('utf-8').splitlines()
   178         1          806    806.0      5.1      return _get_matching_load_commands(lines, cb_filter)

```

This looks good to me. The `mk_relative_osx` function has it's work evenly distributed, and the longest process in `macho.install_name_change` is the `macho.otool` function, which is then limited by the performance of the `check_output` module from subprocesses.

The one thing I'm looking at now is how `macho.otool` is called once when entering the `macho.install_name_change` module (line 237) and then it is called again when control returns to `post.mk_relative_osx` (line 349). will send in another update I can eliminate this as well. 

Also, to answer your questions about how I profiled this. I'm a big fan of the [line_profile](https://github.com/rkern/line_profiler) tool. You can just throw the following function at the top of your module, then just decorate a function you want to profile with `@do_profile` or `@do_profile(follow=[foo, bar])` depending on if you want to also monitor downstream function execution. I'm sure there's a way to integrate it into PyTest, but I'm not so familiar with that library. 

```python
from line_profiler import LineProfiler

def do_profile(follow=[]):
    def inner(func):
        def profiled_func(*args, **kwargs):
            try:
                profiler = LineProfiler()
                profiler.add_function(func)
                for f in follow:
                    profiler.add_function(f)
                profiler.enable_by_count()
                return func(*args, **kwargs)
            finally:
                profiler.print_stats()
        return profiled_func
    return inner
```
and an example:
```python
@do_profile(follow=[more_complicated_math, ackerman_function])
def annoyingly_long_function(foo):
    A = do_some_math(foo)
    B = more_complicated_math(foo, A)
    stupidly_long_computation = ackerman(A , B)
    return stupidly_long_computation
```
Thanks for all your help @msarahan & @mingwandroid. I wasn't quite expecting this level of enthusiasm, but it's appreciated.

**Comment by rlizzo** [comment]
I just moved the order that macho.otool is called. It passed the tests on my local machine, and brought the build time of ITK down from 7 to 5 seconds.

**Comment by msarahan** [comment]
Awesome!  Great to see.  Speaking only for myself here, but it's easy to be enthusiastic about coommunity members improving conda-build.  It's well-worth my time to help make contributing a positive experience, and it also helps conda-build get that much better.

Thanks again.  Merging.

**Pull request merged**
