### PR TITLE
Macos azure

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Hi @mingwandroid ,
I just saw that some tests are failing because of the ``otool``, which I really don't know how it works on ``osx``, ``osx`` is not my cup of tea. :sweat_smile:
```
ERROR :: Failed to run `/usr/bin/otool`.  Please use `conda` to install `cctools` into your base environment.
         An alternative option for users of macOS is to install `Xcode` or `Command Line Tools for Xcode`.
```
Should we install that ``cctools`` or should we skip the tests which need it?

I just saw that you are appending the conda path to each step, right? Doing the 
https://github.com/conda/conda-build/pull/3810/files#diff-fec826feae04e51c0d94076385408bdcR121
``eval "$($(Build.StagingDirectory)/miniconda/bin/python -m conda shell.bash hook)"``

If you want to improve it you can do something similar which we are doing for ``windows``:
https://github.com/conda/conda-build/blob/480aa03ef3826e537be8dd84699590a3d31f5b51/azure-pipelines.yml#L133
`` Write-Host "##vso[task.prependpath]$ENV:UserProfile\Miniconda3;$ENV:UserProfile\Miniconda3\Scripts;$ENV:UserProfile\Miniconda3\Library\bin"``

or if you want to you can let it as it is and I will modify it in a couple of weeks, because I have in my todo list some improvements to do on our ``Azure`` pipelines.

**Comment by mingwandroid** [comment]
Is Xcode installed on these images? Does anyone know? It is correct to fail if not, and we should add an xfail test for that probably, that's skipped if Xcode is installed (and not the stub exe), probably just run the test always though so we can do these inspections (does it link with that xcselect dylib?) without creating a new fixture?

**Comment by mingwandroid** [comment]
Can I do proper activation rather than prependingpath? I'm not interested in avoiding activation, it's important we do this correctly.

**Comment by marcelotrevisani** [comment]
> Can I do proper activation rather than prependingpath? I'm not interested in avoiding activation, it's important we do this correctly.

Sure, as you want to do the activation is better to keep your code then

**Comment by marcelotrevisani** [comment]
> Is Xcode installed on these images? Does anyone know? It is correct to fail if not, and we should add an xfail test for that probably, that's skipped if Xcode is installed (and not the stub exe), probably just run the test always though so we can do these inspections (does it link with that xcselect dylib?) without creating a new fixture?

Just for future references, the whole description of what is installed on ``osx 10.13``
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md

**Comment by mingwandroid** [comment]
This is ready to go now from my side. A few failures on macOS python 3.8 @jjhelmus .. think they could be showing an issue with our builds.

**Comment by mingwandroid** [comment]
Permissions thing on Windows, ok to merge @msarahan, @marcelotrevisani?

**Comment by marcelotrevisani** [comment]
> Permissions thing on Windows, ok to merge @msarahan, @marcelotrevisani?

I think so!
I will mark that test as serial in a couple of days.

**Comment by marcelotrevisani** [comment]
I think that is good to go from my side.
Very nice job @mingwandroid ! Thank! :smile: 
for me ``osx`` is always a pain to make it work properly

It closes #3756

**Pull request merged**
