### PR TITLE
Ignore check_symlinks() whenever readlink() is unavailable

### PR DESCRIPTION
**Pull request by tswicegood**
Related to #287 and should fix test failures on #286.

## Tasks
* [ ] Test on Windows

### CODE REVIEW

**Comment by tswicegood** [comment]
@asmeurer @ddale -- I don't have a Windows box handy for testing builds.  If either of you do and wouldn't mind giving this a go I'd appreciate it.

**Comment by asmeurer** [comment]
The tests themselves are run on Binstar Build ("default" in the GitHub CI list).

**Comment by asmeurer** [comment]
If there's not a test that tests this, what exactly should I run in Windows to see if this works?

**Comment by tswicegood** [comment]
@asmeurer that you can still build packages on Windows.  That seems to have been the problem.  I'm not sure the code path this takes to invoke this code.

**Pull request merged**
