### PR TITLE
Set ARCH from host_arch

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by msarahan** [comment]
I think the fallback from host_arch to arch is already there.  Was it not working?

Specifically:
https://github.com/conda/conda-build/blob/master/conda_build/config.py#L236

**Comment by mingwandroid** [comment]
I saw that pattern being used in the one place that did use host_arch so I cargo culted it everywhere to be safe.

**Comment by mingwandroid** [comment]
But yes it probably shouldn't be needed. It would be nicer from a DRY perspective if host_arch() called arch() I think, but it's minor. Feel free to change my PR here, I'll be stuck in debugging-land for a while.

**Comment by msarahan** [comment]
superseded by #2368; closing

**Pull request closed without merging**
