### PR TITLE
Include "extra" field of meta.yaml in about.json

### PR DESCRIPTION
**Pull request by mikecormier**
https://github.com/conda/conda-build/issues/3046

@msarahan

### CODE REVIEW

**Comment by mikecormier** [comment]
@msarahan,

Looking over the failed test from Travis CI and Appveyor I cannot see any reason that the changes I made would cause those errors. Were these errors present prior to my PR? Do you see any reason why the changes I have made would cause these errors? 

Failed Test:
```
tests/test_api_build.py::test_noarch_python_with_tests
tests/test_api_skeleton.py::test_repo[-rpm-libX11-devel-]
```

The only error that can be traced back to the change/addition I made is in the "Allowed Failure" test in Travis CI run. It errors because of an "E501 line to long error", which is caused by the addition of the "extra" field into the about.json file. 
```
./conda_build/build.py:551:44: E261 at least two spaces before inline comment
./conda_build/build.py:551:101: E501 line too long (105 > 100 characters)
```
The "E261 at least two spaces before inline comment" error can be easily fixed. (I just need to add an additional space to the comment I added)

Additionally, the python 2.7 run on Travis CI did not finish running due to the job timing out. We have had similar problems result from Travis CI building on a public repo for a max of 50 minutes: https://docs.travis-ci.com/user/customizing-the-build#build-timeouts. The script timed out at 49 minutes and 58 seconds.

**Comment by msarahan** [comment]
The CI fails are fine.  Please do fix the flake8 stuff, though.

**Comment by mikecormier** [comment]
@msarahan,

The flake8 errors are fixed, and the test is passing. The CI jobs are still running, but I don't expect anything to have changes for them to pass.

**Comment by mikecormier** [comment]
@msarahan,

I have rebased this PR with the most current commit. The Travis CI runs all pass, except for the python 2.7 run which times out. The Appveyor CI runs still fail. These results are consistent with the latest commit.

**Comment by msarahan** [comment]
Thanks, merging

**Pull request merged**
