### PR TITLE
[WIP] Git shallow clones

### PR DESCRIPTION
**Pull request by groutr**
Using a git shallow clone can save a lot of bandwidth in some cases when cloning large repositories.

### CODE REVIEW

**Comment by jakirkham** [comment]
:+1:

**Comment by pitrou** [comment]
Looking at the git clone man page, you may want to add the `--no-single-branch` option?
Also, is there a reason this option should not be enabled by default?

Last question :-) I see mention of a "git cache" in the source, but I cannot find a `git_cache` directory here. Where is it supposed to be located?

**Comment by groutr** [comment]
I haven't considered that option.  I'll look at it soon.

I haven't thought about making this default.  I'm not even sure what a 
good default would be.  Git has no mechanism for fetching back to a 
tag.  A lot of conda builds rely on tags, which if we only did a shallow 
clone would probably not fetch back far enough, especially for active 
projects.

The git_cache is stored in the $PREFIX/conda-bld directory.

**Comment by jakirkham** [comment]
@pitrou, I can think of a few reasons one might not want to have this enabled by default.

One easy example would be if you determine your version information from git. If you don't include enough commits, you might not reach a tag and your version information will be indeterminate or based off of a commit alone, which would be problematic.

Personally, I would prefer this be an option rather than the default.

**Comment by groutr** [comment]
@jakirkham, I think I agree with you not having this the default.

**Comment by kalefranz** [comment]
LGTM

**Comment by jakirkham** [comment]
Realized this didn't get documented. So adding a brief example in PR ( https://github.com/conda/conda-docs/pull/565 ).

**Pull request merged**
