### PR TITLE
Fix getting recipe text from a meta of an output

### LINKED ISSUE #3248: build_id does take into account manual build strings for subpackages
Namely, it does not seem to detect that a build string is set manually for a subpackage.

https://github.com/conda/conda-build/blob/a6e3a33c6588f89db4d81ec25cb637fcf54d1f78/conda_build/metadata.py#L1261

### PR DESCRIPTION
**Pull request by isuruf**
cc @SylvainCorlay

fixes #3248

### CODE REVIEW

**Comment by msarahan** [comment]
Sorry, this is breaking some important stuff, like the automatic activation of scripts for outputs.  The relevant test there is ``tests/test_subpackages.py::test_activation_in_output_scripts``

I'm trying to look into why, but the chances of me getting pulled sideways before I can figure it out are pretty high.

**Comment by msarahan** [comment]
The problem is that the parent_meta value here *never* has any output info.  It's something like this:

```
{'parent_recipe': {'path': '/Users/msarahan/code/conda-build/tests/test-recipes/split-packages/_output_activation', 'name': 'test_output_activation', 'version': '1.0'}
```

It is only the path to the recipe folder, not the recipe itself.

**Comment by msarahan** [comment]
Thanks for the extra effort here.  I have some work on this that I'll push up.  It has ended up being involved.

**Comment by SylvainCorlay** [comment]
Thanks!

**Pull request merged**
