### PR TITLE
Fixing source/path and GIT_* issues

### PR DESCRIPTION
**Pull request by groutr**
The overarching goal of this PR is to fix issues with source/path (https://github.com/conda/conda-build/issues/783).

I uncovered a subtle issue with the Metadata.get_value() method not behaving as expected (see https://github.com/conda/conda-build/commit/3bd490d6a280be6444781e885e07faf3edadba7a)

### CODE REVIEW

**Comment by stuarteberg** [comment]
BTW, #803 addresses some related (but different) issues than the ones you're addressing here.

**Comment by groutr** [comment]
@stuarteberg Could you explain to me what you expect `get_git_build_info(src_dir, git_url, None)` to mean?

**Comment by stuarteberg** [comment]
>Could you explain to me what you expect `get_git_build_info(src_dir, git_url, None)` to mean?

I'm thinking about [this line](https://github.com/conda/conda-build/blob/e827a77854bfaff799765a546484fbd26882fdfe/conda_build/environ.py#L163-L165):

```python
d.update(**get_git_build_info(d['SRC_DIR'],
                              git_url,
                              m.get_value('source/git_rev')))
```

If third argument evaluates to `None`, then `get_git_build_info()` needs to replace it with a suitable default value.  (The original default was `'master'`, but a better default would be `'HEAD'`, as proposed in #803.)

**Comment by groutr** [comment]
`m.get_value('source/git_rev')` won't evaluate to None.  By default it will evaluate to `text_type()`

**Comment by stuarteberg** [comment]
>By default it will evaluate to text_type()

Ah, okay. Still, for the purposes of this discussion, `None` and `''` have the same meaning.

**Comment by groutr** [comment]
Oh, that third option is supposed to be `m.get_value('source/git_rev', 'HEAD')`

**Comment by stuarteberg** [comment]
Sure, that works, too.

**Comment by stuarteberg** [comment]
BTW, there are likely to be a couple tiny conflicts between this PR and #803.  Not sure if you want to merge that first and rebase this or vice-versa.

**Comment by groutr** [comment]
Probably best to merge #803 first.

**Comment by stuarteberg** [comment]
Also, #790 touches the same function.  Might want to look there, too.

**Comment by jakirkham** [comment]
This probably needs its build restarted, but I don't know if it is worth worrying about at this point.

**Comment by ccordoba12** [comment]
@kalefranz, could you review this one? I'm sure the lack of GIT_* variables is breaking a lot of people's workflows (including ours in Navigator).

**Comment by msarahan** [comment]
LGTM.  Merging.  Thanks @groutr @stuarteberg @jakirkham

**Comment by stuarteberg** [comment]
I like these changes, @groutr.  Nicely done.  Thanks for merging, @msarahan.

**Pull request merged**
