### PR TITLE
Update the sha of script files to reflect the addition/removal of shebang

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by msarahan** [comment]
Excellent, thanks for cleaning this up.  Waiting on CI, but everything in the code looks good to me.

**Comment by msarahan** [comment]
Type confusion on f - https://travis-ci.org/conda/conda-build/jobs/346422107#L2316 - you are assuming it's a dict, but it is a string somehow.

I will clean this up if you can't get to it.  Thanks for your work so far.

**Comment by MatthieuDartiailh** [comment]
Hopefully my last commit will fix the test. I di not take the time to set a proper test env, just run a test on a broken package to see that the sha was indeed updated.

**Comment by msarahan** [comment]
Thanks, looks like your latest push should fix it.  conda-build should be easy to set up for a test env, so if you have issues in the future, let me know.  Using CI is fine for this, of course - it's just very slow to iterate with.

**Comment by msarahan** [comment]
Looks like Travis had a rough go with some slow workers.  I'm going to pull your changes in locally, test them, and push any necessary fixes.  Thanks for sticking with this.

**Comment by msarahan** [comment]
Thanks again @MatthieuDartiailh

**Comment by MatthieuDartiailh** [comment]
You are welcome, sorry for not testing this locally.

**Pull request merged**
