### PR TITLE
Standardize license disclaimer

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

Adding standardized license disclaimer ~and pragmas~. See https://github.com/conda/conda/pull/11183.

Copyright year picked based on the first commit timestamp.

### Checklist - did you ...

- [x] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [x] ~Add / update necessary tests?~
- [x] ~Add / update outdated documentation?~

### CODE REVIEW

**Review by dholth — DISMISSED** [review]
LGTM

**Comment by kenodegard** [comment]
pre-commit.ci autofix

**Comment by kenodegard** [comment]
pre-commit.ci autofix

**Comment by kenodegard** [comment]
Apparently, `pyupgrade` now strips out encoding pragmas, so removing that.

**Review by travishathaway — APPROVED** [review]

**Comment by mbargull** [comment]
> Copyright year picked based on the first commit timestamp.

TBH, this doesn't make a lot of sense since `conda-build` started out as being part of `conda` itself, hence `Copyright (c) 2012 Continuum Analytics, Inc.` would be applicable for its very first code.
However, a lot of the code/source files are from 2016+, i.e., `(c) 2012`/`(c) 2014` is not representative/true for that.

This should really be just
```
Copyright (c) Anaconda, Inc.
SPDX-License-Identifier: BSD-3-Clause
```
or even
```
SPDX-FileCopyrightText: Copyright (c) Anaconda, Inc.
SPDX-License-Identifier: BSD-3-Clause
```
to make all parts unambiguously parsable.

**Comment by mbargull** [comment]
Well, to be sure if dropping the date is okay for U.S. copyright law, I looked it up (from https://www.copyright.gov/title17/):
> Form of Notice.—If a notice appears on the copies, it shall consist of
the following three elements:
(1) the symbol © (the letter C in a circle), or the word “Copyright”, or the
abbreviation “Copr.”; and
(2) the year of first publication of the work; in the case of compilations or
derivative works incorporating previously published material, the year date of
first publication of the compilation or derivative work is sufficient. The year
date may be omitted where a pictorial, graphic, or sculptural work, with ac-
companying text matter, if any, is reproduced in or on greeting cards, postcards,
stationery, jewelry, dolls, toys, or any useful articles; and
(3) the name of the owner of copyright in the work, or an abbreviation by
which the name can be recognized, or a generally known alternative designa-
tion of the owner

So, probably best to retain the year...
I'd still rather go with 2012, though, i.e.,
```
SPDX-FileCopyrightText: Copyright (c) 2012 Anaconda, Inc.
SPDX-License-Identifier: BSD-3-Clause
```
then. It makes more sense to me and would also be more in line with the copyright notice from `LICENSE.txt` (that one still reads Continuum instead of Anaconda).

**Comment by dholth** [comment]
Unicode © anyone

**Comment by mbargull** [comment]
> Unicode © anyone

In theory, yes :laughing:.
I'm still worried about some random tool that manages to mess things up with non-ASCII source files -- stupid, ain't it!? Unicode 1.0 came about when I started to go to the "Kindergarten" ;).
(My brother's name has a non-ASCII character in it -- I'm still always a bit shocked when he dares to put it in his system user name...)

**Comment by kenodegard** [comment]
@mbargull good points, I've proposed the following updates:

- https://github.com/conda/conda-build/pull/4676
- https://github.com/conda/conda/pull/12183

**Comment by jezdez** [comment]
Hey all, please do not argue about copyright topics below an already closed PR, this is far too delicate to do that. @mbargull Please file a ticket the next time.

**Pull request merged**
