### PR TITLE
Rename license relative file paths starting with .. or .

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jjhelmus** [comment]
What is the behavior of a license file whose filename begins with `.`, such as `.license`?

**Comment by isuruf** [comment]
They'll also be renamed to something like `LICENSE0.txt` instead of keeping the name `.license`

**Comment by jjhelmus** [comment]
Sounds reasonable to me.

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
