### PR TITLE
Add compatibility for LIEF=0.14

### PR DESCRIPTION
**Pull request by mbargull**
### Description

Add compatibility for LIEF=0.14
Fixes gh-5227.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by mbargull** [comment]
@conda/builds-tools, I've just added the corresponding issue to the `24.3.x` milestone real quick so we have `conda-build` ready for whenever we make `py-lief>=0.14` packages widely available.

**Comment by jezdez** [comment]
@mbargull @beeankha and I are about to cut the release branch for 24.3.x to kickoff the release process, do you plan to work on the compatibility today? Since in case not, this is something we'll have to do in a minor release.

**Comment by mbargull** [comment]
> @beeankha and I are about to cut the release branch for 24.3.x to kickoff the release process

Haha, I just sent her a message asking if you have concrete plans :rofl: .

> do you plan to work on the compatibility today?

Yes, the code changes are likely ready already.
I'm just waiting for the CI to go through (current failures on Windows are unrelated CI setup flukes), will then revert https://github.com/conda/conda-build/pull/5228/commits/cb5df71c9afd743262a9fd1476f6f9c3cc98b126 and then this should be ready to go in.

**Review by kenodegard — APPROVED** [review]
Confirming constant renaming ([`lief.PE.HEADER_CHARACTERISTICS` → `lief.PE.Header.CHARACTERISTICS`](https://github.com/lief-project/LIEF/blob/bae887e095d87e756d1bf4aa4f95a97693a97b62/doc/sphinx/changelog.rst#L96-L104) and [`lief.EXE_FORMATS` → `lief.Binary.FORMATS`](https://github.com/lief-project/LIEF/blob/bae887e095d87e756d1bf4aa4f95a97693a97b62/doc/sphinx/changelog.rst#L143)) and [removal of `lief.Binary.name` (using `str(file)` instead)](https://github.com/lief-project/LIEF/blob/bae887e095d87e756d1bf4aa4f95a97693a97b62/doc/sphinx/changelog.rst#L157)

**Pull request merged**
