### PR TITLE
Master.nupatch

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
@isuruf and @mbargull, am I correct in this change? selectors isn't meant to mean 'selectors only' is it? If so I'd like to disambiguate that from 'selectors also' and check each usage.

**Comment by mingwandroid** [comment]
For me, the used vars are coming up empty without this change.

**Comment by isuruf** [comment]
It is supposed to mean selectors only. First we get the used selectors, then apply the selectors, then get the rest of the used vars. If it wasn't, we'd be marking some vars as used which are hidden behind a selector that evaluates to False.

**Comment by mingwandroid** [comment]
OK, I've figured out what was wrong, hopefully this doesn't break anything. Please check the latest commit message for details.

**Comment by isuruf** [comment]
Looks good to me

**Comment by mingwandroid** [comment]
Thanks @isuruf. Also, can you review the new patching stuff? The output is silly egomania, but the idea is solid! I'll come up with a key which doesn't encode to RAYMD1LOVE when all is good later!

We need a new CB release soon.

**Comment by isuruf** [comment]
> RAYMD1LOVE

:smile: 

I have very limited experience in using patch. Sorry, I'm not going to be useful reviewing that.

**Comment by mingwandroid** [comment]
OK, the other thing I've slipped in here is: `Add --build-id-pat option (WIP)`, I'm not really happy with the quality of that code so I may remove it from this PR.

**Comment by kenodegard** [comment]
superseded by:
- #4092
- 94c16481

**Pull request closed without merging**
