### PR TITLE
Add a method to shell out and execute a command through subprocess

### PR DESCRIPTION
**Pull request by alexandrucoman**
Hello,

This pull requests tries to remove some redundant blocks of code related to the `subprocess.Popen`.
I hope it will be useful. 

Thanks,
Alex

### CODE REVIEW

**Comment by groutr** [comment]
Thanks.  I'll take a look at it over the next few days.

**Comment by groutr** [comment]
I looked it over and the changes look good to me.  There has been a recent flurry of activity on conda-build in the last week or so in preparation for a new Anaconda release.  Can you update the PR to resolve the merge conflicts?

**Comment by alexandrucoman** [comment]
The merge conflicts are solved.

Thanks,
Alex

**Comment by groutr** [comment]
Thank you again for submitting this PR and later resolving the merge conflicts. :)

**Comment by jakirkham** [comment]
This appears to have broken version information for `git`-based source builds.

**Pull request merged**
