### PR TITLE
Keep python pinning in hashing if there's a space

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by mingwandroid** [comment]
@msarahan, could you give this a review? It's part of the multiple python interpreter support drive.

**Comment by msarahan** [comment]
It seems cleaner to me to just include all python pinning in the hashing, rather than restricting it only to cases with a space.  We didn't do that because of the legacy standard of putting python in the build string directly.  Python is also so much more commonly a point of interest that keeping it in the build string kept it easy for people to visually inspect packages.  With .conda files, pulling out the hash contents should now be fast enough that it might be feasible to get rid of python and the other special-cased junk in the build string and have only the hash.

That's definitely not a conversation I'd wade into recklessly, though.  People will feel strongly about it.  

If you keep only this change, how does this handle the rest of the build string?  What do you envision a final package filename looking like?

**Comment by isuruf** [comment]
For pypy packages it will have `py36` in the build string, but there'll also be a hash.

I wanted this to be backward compatible so that people relying on `--skip-existing` will not get affected.

**Comment by msarahan** [comment]
seems reasonable to me.  I'd say give it a try.

**Comment by isuruf** [comment]
I've marked this WIP, till I try it out. I'll let you know if this works.

**Comment by isuruf** [comment]
This works as expected. I've removed WIP

**Comment by mingwandroid** [comment]
Thank you!

**Comment by isuruf** [comment]
I don't suppose there's a new release that's going to happen soon, right? :smiley:

**Comment by mingwandroid** [comment]
Yes. ASAP. But probably not today. I must make patchelf the default patcher first.

**Pull request merged**
