### PR TITLE
fix: use copy(v) which works also on str, instead of v.copy() which doesn't

### LINKED ISSUE #3404: conda build traceback in _combine_spec_dictionaries
Don't have a MWE yet, but hit this on CI with CB v3.17.8 on Windows:
```Traceback (most recent call last):
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\cli\main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\cli\main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\build.py", line 2292, in build_tree
    bypass_env_check=True)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\render.py", line 803, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\variants.py", line 517, in get_package_variants
    combined_spec = combine_specs(specs, log_output=config.verbose)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\variants.py", line 277, in combine_specs
    log_output=log_output)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\variants.py", line 245, in _combine_spec_dictionaries
    values[k] = v.copy()
AttributeError: 'str' object has no attribute 'copy'
```

### LINKED ISSUE #5416: `AttributeError: 'str' object has no attribute 'copy'` when combining specs.
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

While testing a tarball ([this one](https://anaconda.org/danielpetry/pytorch/2.3.0/download/linux-64/pytorch-2.3.0-gpu_cuda118py39h7338b40_100.tar.bz2)):

```
(bld) [ec2-user@ip-172-31-80-63 ~]$ conda build -t mychan/linux-64/pytorch-2.3.0-gpu_cuda118py39h7338b40_100.tar.bz2 
TEST START: mychan/linux-64/pytorch-2.3.0-gpu_cuda118py39h7338b40_100.tar.bz2                                                                                                                                                                                                                                                 
WARNING: Multiple meta files found. The meta.yaml file in the base directory (/tmp/tmpeqg3qkgb/info/recipe) will be used.                                                                                                                                                                                                     
Adding in variants from internal_defaults                                                                                                                                                                                                                                                                                     
Adding in variants from /tmp/tmpeqg3qkgb/info/recipe/conda_build_config.yaml                                                                                                                                                                                                                                                  
Adding in variants from config.variant                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                              
Leaving build/test directories:                                                                                                                                                                                                                                                                                               
  Work:                                                                                                                                                                                                                                                                                                                       
 /opt/conda/envs/bld/conda-bld/work                                                                                                                                                                                                                                                                                           
  Test:                                                                                                                                                                                                                                                                                                                       
 /opt/conda/envs/bld/conda-bld/test_tmp                                                                                                                                                                                                                                                                                       
Leaving build/test environments:                                                                                                                                                                                                                                                                                              
  Test:                                                                                                                                                                                                                                                                                                                       
source activate  /opt/conda/envs/bld/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla                                                
  Build:                                                                                                                                                                                                                                                                                                                      
source activate  /opt/conda/envs/bld/conda-bld/_build_env                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              
Traceback (most recent call last):
  File "/opt/conda/envs/bld/bin/conda-build", line 11, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/cli/main_build.py", line 570, in execute
    test_action(recipe, config)
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/cli/main_build.py", line 526, in test_action
    return api.test(recipe, move_broken=False, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/api.py", line 290, in test
    return test(
           ^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/build.py", line 3243, in test
    metadata, hash_input = construct_metadata_for_test(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/build.py", line 2987, in construct_metadata_for_test
    m, hash_input = _construct_metadata_for_test_from_package(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/build.py", line 2899, in _construct_metadata_for_test_from_package
    metadata = render_recipe(
               ^^^^^^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/render.py", line 985, in render_recipe
    m.config.variants = get_package_variants(m, variants=variants)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/variants.py", line 698, in get_package_variants
    combined_spec, specs = get_package_combined_spec(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/variants.py", line 666, in get_package_combined_spec
    combined_spec = combine_specs(specs, log_output=config.verbose)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/variants.py", line 379, in combine_specs
    values = _combine_spec_dictionaries(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bld/lib/python3.11/site-packages/conda_build/variants.py", line 332, in _combine_spec_dictionaries
    values[k] = v.copy()
                ^^^^^^
AttributeError: 'str' object has no attribute 'copy'
```

Putting a breakpoint just before the line throwing the error shows:
```
(Pdb) print(k)
numpy
(Pdb) print(v)
1.21
(Pdb) print(values)
{'python': ['3.9'], 'numpy': ['1.21'], 'perl': ['5.34'], 'lua': ['5'], 'r_base': ['3.5'], 'cpu_optimization_target': ['nocona'], 'pin_run_as_build': {'python': {'max_pin': 'x.x', 'min_pin': 'x.x'}, 'r-base': {'max_pin': 'x.x', 'min_pin': 'x.x'}, 'libboost': {'max_pin': 'x.x.x'}}, 'ignore_version': [], 'ignore_build_only_deps': ['python', 'numpy'], 'extend_keys': ['pin_run_as_build', 'ignore_build_only_deps', 'extend_keys', 'ignore_version'], 'cran_mirror': ['https://mran.microsoft.com/snapshot/2018-01-01'], 'target_platform': ['linux-64'], 'c_compiler': ['gcc'], 'cxx_compiler': ['gxx'], 'fortran_compiler': ['gfortran'], 'VERBOSE_AT': ['V=1'], 'VERBOSE_CM': ['VERBOSE=1'], 'blas_impl': ['openblas'], 'boost': ['1.82'], 'boost_cpp': ['1.82'], 'bzip2': ['1.0'], 'c_compiler_version': ['11.2.0'], 'cairo': ['1.16'], 'channel_targets': ['defaults'], 'clang_variant': ['clang'], 'cuda_compiler': ['cuda-nvcc'], 'cuda_compiler_version': ['12.4'], 'cudatoolkit': ['11.8'], 'cudnn': ['8.9.2.26'], 'cxx_compiler_version': ['11.2.0'], 'cyrus_sasl': ['2.1.28'], 'dbus': ['1'], 'expat': ['2'], 'fontconfig': ['2.14'], 'fortran_compiler_version': ['11.2.0'], 'freetype': ['2.10'], 'g2clib': ['1.6'], 'geos': ['3.8.0'], 'giflib': ['5'], 'glib': ['2'], 'gmp': ['6.2'], 'gnu': ['2.12.2'], 'gpu_variant': ['cuda-11'], 'gst_plugins_base': ['1.14'], 'gstreamer': ['1.14'], 'harfbuzz': ['4.3.0'], 'hdf4': ['4.2'], 'hdf5': ['1.12.1'], 'hdfeos2': ['2.20'], 'hdfeos5': ['5.1'], 'icu': ['73'], 'jpeg': ['9'], 'libcurl': ['8.1.1'], 'libdap4': ['3.19'], 'libffi': ['3.4'], 'libgd': ['2.3.3'], 'libgdal': ['3.6.2'], 'libgsasl': ['1.10'], 'libkml': ['1.3'], 'libnetcdf': ['4.8'], 'libpng': ['1.6'], 'libprotobuf': ['3.20.3'], 'libtiff': ['4.2'], 'libwebp': ['1.3.2'], 'libxml2': ['2.10'], 'libxslt': ['1.1'], 'llvm_variant': ['llvm'], 'lzo': ['2'], 'mkl': ['2023.*'], 'mpfr': ['4'], 'openblas': ['0.3.21'], 'openjpeg': ['2.3'], 'openssl': ['3.0'], 'pixman': ['0.40'], 'proj': ['9.3.1'], 'proj4': ['5.2.0'], 'python_impl': ['cpython'], 'python_implementation': ['cpython'], 'r_implementation': ['r-base'], 'r_version': ['3.5.0'], 'readline': ['8.1'], 'rust_compiler': ['rust'], 'rust_compiler_version': ['1.71.1'], 'sqlite': ['3'], 'tk': ['8.6'], 'xz': ['5'], 'zip_keys': [['python', 'numpy']], 'zlib': ['1.2'], 'zstd': ['1.5.2']}
(Pdb) pprint.pprint(specs)
OrderedDict([('internal_defaults',
              {'c_compiler': 'gcc',
               'cpu_optimization_target': 'nocona',
               'cran_mirror': 'https://cran.r-project.org',
               'cxx_compiler': 'gxx',
               'extend_keys': ['pin_run_as_build',
                               'ignore_version',
                               'ignore_build_only_deps',
                               'extend_keys'],
               'fortran_compiler': 'gfortran',
               'ignore_build_only_deps': ['python', 'numpy'],
               'ignore_version': [],
               'lua': '5',
               'numpy': '1.23',
               'perl': '5.26.2',
               'pin_run_as_build': {'python': {'max_pin': 'x.x',
                                               'min_pin': 'x.x'},
                                    'r-base': {'max_pin': 'x.x',
                                               'min_pin': 'x.x'}},
               'python': '3.11',
               'r_base': '3.5',
               'target_platform': 'linux-64'}),
             ('/tmp/tmp0wue6mdn/info/recipe/conda_build_config.yaml',
              {'VERBOSE_AT': 'V=1',
               'VERBOSE_CM': 'VERBOSE=1',
               'blas_impl': 'openblas',
               'boost': '1.82',
               'boost_cpp': '1.82',
               'bzip2': '1.0',
               'c_compiler': 'gcc',
               'c_compiler_version': '11.2.0',
               'cairo': '1.16',
               'channel_targets': 'defaults',
               'clang_variant': 'clang',
               'cpu_optimization_target': 'nocona',
               'cran_mirror': 'https://mran.microsoft.com/snapshot/2018-01-01',
               'cuda_compiler': 'cuda-nvcc',
               'cuda_compiler_version': '12.4',
               'cudatoolkit': '11.8',
               'cudnn': '8.9.2.26',
               'cxx_compiler': 'gxx',
               'cxx_compiler_version': '11.2.0',
               'cyrus_sasl': '2.1.28',
               'dbus': '1',
               'expat': '2',
               'extend_keys': ['pin_run_as_build',
                               'extend_keys',
                               'ignore_build_only_deps',
                               'ignore_version'],
               'fontconfig': '2.14',
               'fortran_compiler': 'gfortran',
               'fortran_compiler_version': '11.2.0',
               'freetype': '2.10',
               'g2clib': '1.6',
               'geos': '3.8.0',
               'giflib': '5',
               'glib': '2',
               'gmp': '6.2',
               'gnu': '2.12.2',
               'gpu_variant': 'cuda-11',
               'gst_plugins_base': '1.14',
               'gstreamer': '1.14',
               'harfbuzz': '4.3.0',
               'hdf4': '4.2',
               'hdf5': '1.12.1',
               'hdfeos2': '2.20',
               'hdfeos5': '5.1',
               'icu': '73',
               'ignore_build_only_deps': ['python', 'numpy'],
               'jpeg': '9',
               'libcurl': '8.1.1',
               'libdap4': '3.19',
               'libffi': '3.4',
               'libgd': '2.3.3',
               'libgdal': '3.6.2',
               'libgsasl': '1.10',
               'libkml': '1.3',
               'libnetcdf': '4.8',
               'libpng': '1.6',
               'libprotobuf': '3.20.3',
               'libtiff': '4.2',
               'libwebp': '1.3.2',
               'libxml2': '2.10',
               'libxslt': '1.1',
               'llvm_variant': 'llvm',
               'lua': '5',
               'lzo': '2',
               'mkl': '2023.*',
               'mpfr': '4',
               'numpy': '1.21',
               'openblas': '0.3.21',
               'openjpeg': '2.3',
               'openssl': '3.0',
               'perl': '5.34',
               'pin_run_as_build': {'libboost': {'max_pin': 'x.x.x'},
                                    'python': {'max_pin': 'x.x',
                                               'min_pin': 'x.x'},
                                    'r-base': {'max_pin': 'x.x',
                                               'min_pin': 'x.x'}},
               'pixman': '0.40',
               'proj': '9.3.1',
               'proj4': '5.2.0',
               'python': '3.9',
               'python_impl': 'cpython',
               'python_implementation': 'cpython',
               'r_base': '3.5',
               'r_implementation': 'r-base',
               'r_version': '3.5.0',
               'readline': '8.1',
               'rust_compiler': 'rust',
               'rust_compiler_version': '1.71.1',
               'sqlite': '3',
               'target_platform': 'linux-64',
               'tk': '8.6',
               'xz': '5',
               'zip_keys': [['python', 'numpy']],
               'zlib': '1.2',
               'zstd': '1.5.2'}),
             ('config.variant',
              {'__cuda': '__cuda >=11.8',
               'blas_impl': 'openblas',
               'c_compiler': 'gcc',
               'c_compiler_version': '11.2.0',
               'channel_targets': 'defaults',
               'cudatoolkit': '11.8',
               'cudnn': '8.9.2.26',
               'cxx_compiler': 'gxx',
               'cxx_compiler_version': '11.2.0',
               'gpu_variant': 'cuda-11',
               'libprotobuf': '3.20.3',
               'numpy': '1.21',
               'openblas': '0.3.21',
               'target_platform': 'linux-64'})])
```
The tarball under test was built using the recipe/commit [here](https://github.com/AnacondaRecipes/pytorch-feedstock/tree/1ae8ecf0a4af4c7f3e517a70100ba1cf1551e378).

### Conda Info

_No response_

### Conda Config

_No response_

### Conda list

_No response_

### Additional Context

Seems to duplicate https://github.com/conda/conda-build/issues/3404, but that's closed.

### PR DESCRIPTION
**Pull request by corneliusroemer**
resolves #5416
resolves #3404 (closed because stale, not because fixed)

Bug was possibly introduced in #3344

@msarahan @isuruf I think you are best acquainted with this part of the code base. I don't really know what's going on here - but this workaround fixes the bug for my use case.

### Checklist - did you ...

Will fill out checklist if it's likely this will get merged

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by travishathaway** [comment]
@conda-bot check

**Comment by travishathaway** [comment]
@corneliusroemer,

Thanks for opening this. While we wait for the others to chime in, it would be really nice if you could add both a regression test for this and a news file entry. The regression test could go in `tests/test_variants.py`. We just need to test the `_combined_spec_dictionaries` function.

The tricky part is finding the exact data to feed into the function to recreate the stacktrace, but I hope that you might be able to generate that seeing that you can recreate this issue yourself.

Let us know if you need any help with that.

**Comment by corneliusroemer** [comment]
Thanks @travishathaway! Happy to add news and try to get a test working - just wanted to check I'd not be wasting my time.

**Comment by beckermr** [comment]
Please add a test and news, and then we can merge. This PR won't make a version of conda-build until next year.

**Comment by beckermr** [comment]
OK @conda/builds-tools This one is ready for review!

This bug is serious enough that it may make sense to include it as a bug fix release for 24.11. Thoughts?

**Review by kenodegard — APPROVED** [review]

**Review by kenodegard — APPROVED** [review]

**Review by beeankha — APPROVED** [review]

**Pull request merged**
