### PR TITLE
Drop extra Jinja w/package names from variants.rst

### PR DESCRIPTION
**Pull request by jakirkham**
### Description

AIUI including the package name in Jinja was something that use to be needed, but at some point this was added automatically when matching against a package name. So suggesting we drop this from the doc to simplify things for users learning about this functionality.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by pentschev** [comment]
Thanks @jakirkham !

**Comment by beeankha** [comment]
Hi @jakirkham , thanks for this pull request! Please add a [news file](https://github.com/conda/conda-build/blob/main/news/TEMPLATE) and include information about which version of conda-build we started to be able to drop these variables from (in the news file blurb), if you know that info!

**Comment by jakirkham** [comment]
AFAIK this was never needed in conda-build 3 (when the variants were introduced). Though I could be wrong, in which case it is some very old version of conda-build 3 (and I don't know what version that would be)

**Review by sven6002 — DISMISSED** [review]
Looks good to me..

**Review by beeankha — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 🙏

Anything else needed here?

**Review by jezdez — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks again! 🙏

**Pull request merged**
