### PR TITLE
refine tests for default values for environ.get in jinja2

### PR DESCRIPTION
**Pull request by msarahan**
cc @stuarteberg

### CODE REVIEW

**Comment by stuarteberg** [comment]
Not sure if this matters per se, but it looks like this branch is based off of an out-dated commit of the master branch.  (The condition in `parse_or_try_download()` function is slightly different now, for instance.)  Might be worth rebasing just to avoid confusion, unless this is what you intended.

**Comment by stuarteberg** [comment]
OK, I see the problem.  It's in your test.  You wrote:

```
version: {{ environ.get(GIT_DESCRIBE_TAG.replace('v', ''), "WRONG_ANSWER") }}
```

During the second pass, that will evaluate to something like this:

```
version: {{ environ.get('1.2.3'.replace('v', ''), "WRONG_ANSWER") }}
```

... and since '1.2.3' (or whatever) doesn't exist in `environ`, you'll always get `WRONG_ANSWER` as a result.


I think you meant to write this:

```
version: {{ environ.get("GIT_DESCRIBE_TAG", "WRONG_ANSWER").replace('v', '') }}
```

which will evaluate to this (assuming `"GIT_DESCRIBE_TAG"` exists in the environment.):

```
version: {{ '1.2.3'.replace('v', '') }}
```

**Comment by msarahan** [comment]
Ah!  good catch on both counts.  Rebasing and changing the test.

**Comment by msarahan** [comment]
@joelhullcio, I believe these tests exercise your recipe and do not show the error.  Can we please investigate which version of conda build you have installed?  I don't see any version output in the logs you sent me, so I think you're current, but I want to make certain.

**Comment by msarahan** [comment]
Merging these tests - they're good to have, anyway.

**Pull request merged**
