### PR TITLE
restore appveyor; rewrite shell tests as pytest tests

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like Travis is encountering a couple of test failures.

**Comment by msarahan** [comment]
@stuarteberg can you take a look at https://travis-ci.org/conda/conda-build/jobs/120510300?  The recursive tests are failing, but I'm not sure if that's expected behavior right now, given https://github.com/conda/conda-build/issues/849

**Comment by stuarteberg** [comment]
Sorry, I'm not in the loop on the changes that caused #849.  Not sure what should/should not pass here.

**Comment by jakirkham** [comment]
The last thing I remember seeing on recursive builds was this PR ( https://github.com/conda/conda-build/pull/826 ).

**Comment by msarahan** [comment]
Thanks @stuarteberg and @jakirkham - mistake was mine, dumb one: conda has to see the recipes, so it has to have the metadata folder as its cwd.  Fixed now, at least on my PC.  We'll see what Travis says.

**Comment by jakirkham** [comment]
Awesome job by converting the `.sh` tests to `.py`. That was an ugly business. :+1:

**Comment by msarahan** [comment]
Thanks!  This should make the whole build more reliable - I think the amount of text output before was too much.  I was inspired by the work I did on @patricksnape's PR.  Py.test is pretty neat once you get the hang of it.

**Comment by jakirkham** [comment]
:tada:

**Comment by pelson** [comment]
Great job @msarahan!

**Pull request merged**
