### PR TITLE
Filter out *.conda_trash files when packaging

### LINKED ISSUE #3455: Build with bdist_conda leaves *.conda_trash files in the package
### Actual Behavior
I have a python package that I am packaging with `python setup.py bdist_conda`, which has worked flawlessly in the past. I have just noticed that now, on building the package, the finished package ends up with lots and lots of files that do not belong there, and that have a `conda_trash` prefix, **sometimes multiple times**. 
For example, I have a file called `python.exe.conda_trash.conda_trash` in the root of my .tar file. 
Compared to an earlier version, the yellow marked files/directory are new/should not be there:
image

Is this some build clean-up phase failing?

During build, I also notice lots of
```
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\pyexpat.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\select.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\unicodedata.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_asyncio.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_bz2.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_decimal.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_hashlib.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_lzma.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_multiprocessing.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_overlapped.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_socket.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_sqlite3.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\DLLs\_ssl.pyd.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\Library\bin\libssl-1_1-x64.dll.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\Library\bin\sqlite3.dll.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\Library\bin\zlib.dll.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\python.exe.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\python3.dll.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\python36.dll.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\HOST_P~1.1-P\vcruntime140.dll.conda_trash.conda_trash.conda_trash.conda_trash - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\pyexpat.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\select.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\unicodedata.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_asyncio.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_bz2.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_decimal.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_hashlib.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_lzma.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_multiprocessing.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_overlapped.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_socket.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_sqlite3.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\DLLs\_ssl.pyd - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\Library\bin\libssl-1_1-x64.dll - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\Library\bin\sqlite3.dll - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\Library\bin\zlib.dll - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\python.exe - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\python3.dll - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\python36.dll - Access is denied.
C:\Continuum\miniconda3\conda-bld\bdist_conda_1553265400948\_TEST_~1\vcruntime140.dll - Access is denied.
```
but as far as I know these have always been there, and not made a problem.
I also notice multiple occurrences of
```
WARNING:conda_build.build:failed to open python.exe.conda_trash.conda_trash for detecting prefix.  Skipping it.
```
(with different files).

### Expected Behavior
The package should just have the `info` and `Lib` folder with all the related files therein, and no `conda_trash` files.

### Steps to Reproduce
The package is not public, I have not yet tried to reproduce independently with some minimal python package.

##### `Output of conda info`

```
     active environment : base
    active env location : C:\Continuum\miniconda3
            shell level : 1
       user config file : C:\Users\buchner\.condarc
 populated config files : C:\Users\buchner\.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : C:\Continuum\miniconda3  (writable)
           channel URLs : <a local channel>/win-64
                           <a local channel>/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Continuum\miniconda3\pkgs
                          C:\Users\buchner\.conda\pkgs
                          C:\Users\buchner\AppData\Local\conda\conda\pkgs
       envs directories : C:\Continuum\miniconda3\envs
                          C:\Users\buchner\.conda\envs
                          C:\Users\buchner\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
This is on Windows with miniconda, python 3.6, conda 4.6.8, conda-build 3.17.8, conda-env 2.6.0, conda-verify 3.1.1.

### PR DESCRIPTION
**Pull request by bilderbuchi**
Make sure to filter out *.conda_trash files when packaging.
Closes #3455.

@msarahan please review.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
I have tested this locally in my conda installation, works as intended.

**Comment by bilderbuchi** [comment]
I don't know what the failing test `test_cran_license[r-ruchardet-MPL-OTHER-]` is about, but its failure seems unrelated to my changes. 
Pinging @jdblischak who added those tests recently, could you check [the output](https://travis-ci.org/conda/conda-build/jobs/511375605#L1731-L1762) and see what went wrong here?

**Comment by bilderbuchi** [comment]
Ah, searching for this package: 
```
Package ‘Ruchardet’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2019-03-02 for policy violation. 
```

So, should this be dropped from the test or replaced by another parametrize entry?

**Comment by msarahan** [comment]
Thanks!  Don't worry about Ruchardet.  We can ignore that test for now.  You can remove it from that parametrize entry if you want to.

The function that renames files to trash is here: https://github.com/conda/conda/blob/master/conda/gateways/disk/delete.py#L69-L108

Conda's trash cleanup is this: https://github.com/conda/conda/blob/master/conda/gateways/disk/delete.py#L150-L164

Your addition here is probably sufficient, given that conda-build is operating on temporary environments, not long-lived ones.  It would be nice to tweak the regex to filter out the potential numbered extensions, but I wouldn't call it mandatory for this to go in.

**Comment by jdblischak** [comment]
@bilderbuchi Thanks for alerting me to this error. The package ruchardet was arbitrarily chosed as an example CRAN package that uses the MPL license. Since it has been archived, I'll replace it with another one.

**Comment by bilderbuchi** [comment]
> tweak the regex to filter out the potential numbered extensions, but I wouldn't call it mandatory for this to go in.

what do you mean with this, exactly? If `bla.conda_trash.conda_trash`, this is already being filtered correctly.

**Comment by jdblischak** [comment]
@bilderbuchi The fixed test has been merged into the master branch.

**Comment by bilderbuchi** [comment]
Great, thanks for the quick work!

**Comment by msarahan** [comment]
The conda code that I linked you to shows that you could end up with files that end with

.conda_trash_2

for example.  https://github.com/conda/conda/blob/master/conda/gateways/disk/delete.py#L91-L93

**Comment by bilderbuchi** [comment]
Thank you, I have adapted the regex pattern to include those files.

**Comment by bilderbuchi** [comment]
OK, so the builds time out. 
I looked through the CI setup to check if something can be accelerated, and I am wondering, @msarahan, why the test script that is run [creates multiple environments](https://github.com/conda/conda-build/blob/e31e5401a87a8a388be1a3ce91ec938f7daaa8e2/ci/travis/run.sh#L28-L31) and then does nothing with them? 

This is especially interesting considering that
* a build for a given python version in the build matrix (e.g. Python3.6) just builds a conda environment for _another_ python version (e.g. 2.7)?
* and that these environments won't contain conda-build anyway, so what should these lines test in the first place?

There is no timing information because this all happens in one test phase (btw, maybe some of that logic can be put in the travis config?), but I suspect creating 4 envs will take a significant amount of time.

**Comment by bilderbuchi** [comment]
Also, reminder to self to add some more things to the test case for filter_files, to test for the new exclusions.

**Comment by msarahan** [comment]
Creating those 4 envs is done to cache packages.  It helps make sure that later env creation in the test suite (which is run in parallel) does not do dumb things in the package cache, because conda is not at all safe to run in multiple processes.  In other words, it's a hack, but that's probably not the speed issue.

The last time I looked, it seemed like conda-build might be doing its solving stuff one too many times.  The tricky thing is that conda-build's data model for outputs and top-level recipes is very mixed up and bad.  Ideally, there should be a data model for the top-level part of the recipe (everything but the stuff in outputs), and a different data model for the outputs.  Right now, there's only one, MetaData, and it's very awkward to say whether the top-level metadata is an output, and whether it needs to be rendered, and often things accidentally get rendered twice.  If you want to look into it, the best way is probably to identify a simple test with no outputs, and check the call counts.  You'll have up to 3 calls to conda to get the env deps - one for build, host, and test envs.  Outputs will add the same 3, but if there's an output that is for the top-level recipe, ideally you should not need to re-do these 3.  I think this is probably the problem.

**Comment by msarahan** [comment]
Thanks for fixing this.  Merging.

**Comment by bilderbuchi** [comment]
Thanks for the info. I think I'm actually more confused now :D I think I'll have to pass on digging into the internals like that :D , it's just a pity that most test runs just time out, this should be improved...

**Pull request merged**
