### PR TITLE
Added conjunction to comma_join, fixed islist

### PR DESCRIPTION
**Pull request by kenodegard**
Added ability to change the conjunction used by `comma_join` (e.g. `comma_join(iterable, conjunction="or"`). Fixed `islist` bug which caused it to incorrectly treat classes with `__iter__` as lists (e.g. `islist(dict)`).

Both of these changes are prompted by #4179, separated out here to make reviewing easier.

### CODE REVIEW

**Comment by njalerikson** [comment]
It would appear that the failing test (macOS py37-release: test_api_build/test_env_creation_fail_exits_build) is unrelated to this change and fails erratically as seen in other pipelines.

**Comment by njalerikson** [comment]
@mingwandroid - still no rush just didn't want to forget about these changes

**Comment by mingwandroid** [comment]
Hey @njalerikson, they've not been forgotten, as soon as I get back to conda-build, merging your changes will be my top priority. Thanks for the ping.

**Review by jezdez — APPROVED** [review]

**Comment by jezdez** [comment]
Blast from the past!

**Pull request merged**
