### PR TITLE
Add `extra` to `outputs` in `FIELDS`

### PR DESCRIPTION
**Pull request by jakirkham**
Adding it here should also avoid some lint that I'm [running into]( https://github.com/conda-forge/ucx-split-feedstock/pull/14#issuecomment-533550603 ).

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Hi @jakirkham , is it possible to also add a test to cover this scenario? I would appreciate that! :)

**Comment by jakirkham** [comment]
Not sure how `FIELDS` is tested now TBH, but have pushed a test recipe that leverages the `extra` field. Does that help?

**Comment by jakirkham** [comment]
@marcelotrevisani , is there anything else to do here?

**Comment by marcelotrevisani** [comment]
> Not sure how `FIELDS` is tested now TBH, but have pushed a test recipe that leverages the `extra` field. Does that help?

I was just expecting one recipe with those fields, so we can be sure that at least ``conda-build`` is supporting it. But I think that is fine then. I will merge it! thanks! :)

**Comment by jakirkham** [comment]
Ah ok thanks for clarifying. Also thanks for the review. 😀

**Pull request merged**
