### PR TITLE
Moved try block in copy_recipe further up in order to catch values that are lists

### PR DESCRIPTION
**Pull request by mandeep**
@mingwandroid brought up the issue that PR #2149 may result in an AttributeError traceback when a section contains a list as its value instead of a dictionary. This PR will fix that issue.

### CODE REVIEW

**Comment by msarahan** [comment]
I'm not sure this is the right fix.  Let's take a step back and figure out exactly what data types we expect.  From there, we can write better code to either check type and dispatch accordingly, or write better comments for what a given try/except block is handling, and also what it is ignoring.

**Comment by mandeep** [comment]
I'm with you. Do you want me to push a commit to this branch that removes the code since its breaking things?

**Comment by msarahan** [comment]
eh, just use this branch to do the right thing.  It's fine that master is a bit broken right now.  Ray has reverted it locally anyway, and hopefully you can figure out the right, clean way to do this quickly.

**Comment by msarahan** [comment]
@mingwandroid any opinions on this?  I think it should work better than the code that broke you, but I'd also appreciate if you could tell us which recipe triggered the bug you saw.

**Comment by msarahan** [comment]
Thanks @mandeep

**Pull request merged**
