### PR TITLE
Test with `setup.py` in a subdirectory

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a test case like the one in issue ( https://github.com/conda/conda-build/issues/3754 ).

cc @marcelotrevisani

### CODE REVIEW

**Comment by jakirkham** [comment]
If there is a way to mark this as an xfail, would be happy to make that change so we can get it in. 🙂

**Comment by marcelotrevisani** [comment]
> If there is a way to mark this as an xfail, would be happy to make that change so we can get it in. slightly_smiling_face

Sure, I can mark it as Xfail if you want to. Just to be sure, this PR is to cover the issue which you described, right? Do you want to fix it or just want to have this test case that reproduces the error to another person to fix it?

**Comment by jakirkham** [comment]
That would be great! Thanks.

Yes. I haven’t managed to fix it yet, but maybe the test helps someone fix it in the future.

**Comment by jakirkham** [comment]
Looks like some the AppVeyor tests are hanging and thus timing out on the CI. Is this expected? Doesn't seem related to this PR.

**Comment by marcelotrevisani** [comment]
> Looks like some the AppVeyor tests are hanging and thus timing out on the CI. Is this expected? Doesn't seem related to this PR.

It is not related to this PR indeed. Sometimes some tests take more time to finish and we have some strict timeout on ``appveyor``. I was trying to run the tests using azure for windows as well, but I am seeing some problems regarding the ``git`` env variables and ``cython`` which for some reason is not using the MSVC correctly.

**Comment by marcelotrevisani** [comment]
is it ready to be integrate this test case?

**Comment by jakirkham** [comment]
Yep. Thanks @marcelotrevisani! 😀

**Comment by jakirkham** [comment]
Thanks for the review 🙂

**Pull request merged**
