### PR TITLE
Fix no include recipe with tests

### LINKED ISSUE #2457: --no-include-recipe breaks build when run_test.sh is present
Doing `conda build .` is fine, but `conda build --no-include-recipe .` fails with
```
Traceback (most recent call last):
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/environ.py", line 680, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 853, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - condatest 0.0.1 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/pmadden/o/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1782, in build_tree
    test(pkg, config=metadata.config)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1556, in test
    channel_urls=tuple(metadata.config.channel_urls))
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/environ.py", line 682, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['condatest 0.0.1 0']
```
Background info:
```
% cat meta.yaml
package:
  name: condatest
  version: '0.0.1'

requirements:
  run:
    - numpy 1.13.3.*

% cat run_test.sh 
true

% conda build --version
conda-build 3.0.27
```

### LINKED ISSUE #2588: --no-include-recipe skips tests
Running conda build with the `--no-include-recipe` argument skips any tests present in the recipe.

For example:

``` yaml
package:
  name: example
  version: "1.0.0"

test:
  commands:
    - exit 1
```

```
$ conda build -V
conda-build 3.1.6
$ conda build .
Attempting to finalize metadata for example
INFO:conda_build.metadata:Attempting to finalize metadata for example
BUILD START: ['example-1.0.0-0.tar.bz2']
source tree in: /home/jhelmus/anaconda3/conda-bld/example_1513628615828/work
Packaging example
INFO:conda_build.build:Packaging example
Packaging example-1.0.0-0
INFO:conda_build.build:Packaging example-1.0.0-0
No files or script found for output example
WARNING:conda_build.build:No files or script found for output example
number of files: 0
Fixing permissions
Fixing permissions
updating: example-1.0.0-0.tar.bz2
Updating index at /home/jhelmus/anaconda3/conda-bld/linux-64 to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/jhelmus/anaconda3/conda-bld/linux-64 to make package installable with dependencies
Updating index at /home/jhelmus/anaconda3/conda-bld/noarch to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/jhelmus/anaconda3/conda-bld/noarch to make package installable with dependencies
TEST START: /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2
Renaming work directory,  /home/jhelmus/anaconda3/conda-bld/example_1513628615828/work  to  /home/jhelmus/anaconda3/conda-bld/example_1513628615828/work_moved_example-1.0.0-0_linux-64

The following NEW packages will be INSTALLED:

    example: 1.0.0-0 local

+ exit 1
Tests failed for example-1.0.0-0.tar.bz2 - moving package to /home/jhelmus/anaconda3/conda-bld/broken
WARNING:conda_build.build:Tests failed for example-1.0.0-0.tar.bz2 - moving package to /home/jhelmus/anaconda3/conda-bld/broken
removing: example-1.0.0-0.tar.bz2
TESTS FAILED: example-1.0.0-0.tar.bz2
```
```
 example-1.0.0-0.tar.bz2
~/sandbox/bug$ conda build --no-include-recipe .
Attempting to finalize metadata for example
INFO:conda_build.metadata:Attempting to finalize metadata for example
BUILD START: ['example-1.0.0-0.tar.bz2']
source tree in: /home/jhelmus/anaconda3/conda-bld/example_1513628647377/work
Packaging example
INFO:conda_build.build:Packaging example
Packaging example-1.0.0-0
INFO:conda_build.build:Packaging example-1.0.0-0
No files or script found for output example
WARNING:conda_build.build:No files or script found for output example
number of files: 0
Fixing permissions
Fixing permissions
updating: example-1.0.0-0.tar.bz2
Error extracting info/recipe/meta.yaml in /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2: KeyError("filename 'info/recipe/meta.yaml' not found",)
Traceback (most recent call last):
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/index.py", line 313, in _read_index_tar
    t.extractfile('info/recipe/meta.yaml').read().decode('utf-8')
  File "/home/jhelmus/anaconda3/lib/python3.6/tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "/home/jhelmus/anaconda3/lib/python3.6/tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/recipe/meta.yaml' not found"
WARNING:conda_build.index:Error extracting info/recipe/meta.yaml in /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2: KeyError("filename 'info/recipe/meta.yaml' not found",)
Traceback (most recent call last):
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/index.py", line 313, in _read_index_tar
    t.extractfile('info/recipe/meta.yaml').read().decode('utf-8')
  File "/home/jhelmus/anaconda3/lib/python3.6/tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "/home/jhelmus/anaconda3/lib/python3.6/tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/recipe/meta.yaml' not found"
Updating index at /home/jhelmus/anaconda3/conda-bld/linux-64 to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/jhelmus/anaconda3/conda-bld/linux-64 to make package installable with dependencies
Updating index at /home/jhelmus/anaconda3/conda-bld/noarch to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/jhelmus/anaconda3/conda-bld/noarch to make package installable with dependencies
Nothing to test for: /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []



####################################################################################
Source and build intermediates have been left in /home/jhelmus/anaconda3/conda-bld.
There are currently 2 accumulated.
To remove them, you can run the ```conda build purge``` command
````

### PR DESCRIPTION
**Pull request by msarahan**
fixes #2588 
fixes #2457 

CC @jjhelmus

### CODE REVIEW

**Comment by rainwoodman** [comment]
I tried 371043b -- it didn't seem to include all files installed to the target, producing an empty package with only the info folder. Also be aware that `$PYTHON` is no longer defined in this version. I don't know if this is intended or not.

**Comment by msarahan** [comment]
There is an explicit test for $PYTHON being defined: https://github.com/conda/conda-build/blob/master/tests/test-recipes/metadata/python_env_defined/run_test.py#L3

Please post a full recipe and build log that reproduces your problem.  Please post in a new issue as that is completely unrelated to this PR.

**Comment by rainwoodman** [comment]
Sure. I will retest against master after this PR is merged. But it appears that there was a test suite effectiveness issue?

**Comment by rainwoodman** [comment]
Here are two conda_build.sh

From newer version of conda-build(here)
```
[yfeng1@waterfall conda-channel-bccp]$ cat ~/anaconda3/install/conda-bld//mpi4py_1513644742163/work/conda_build.sh
export CONDA_BUILD="1"
export PYTHONNOUSERSITE="1"
export CONDA_DEFAULT_ENV="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh"
export ARCH="64"
export PREFIX="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh"
export BUILD_PREFIX="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_build_env"
export SYS_PREFIX="/home/yfeng1/anaconda3/install"
export SYS_PYTHON="/home/yfeng1/anaconda3/install/bin/python"
export SUBDIR="linux-64"
export SRC_DIR="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/work"
export ROOT="/home/yfeng1/anaconda3/install"
export CONDA_PY="36"
export PY3K="1"
export PY_VER="3.6"
export STDLIB_DIR="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6"
export SP_DIR="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages"
export NPY_VER="1.9"
export CONDA_NPY="19"
export PERL_VER="5.26"
export CONDA_PERL="5.26"
export LUA_VER="5"
export CONDA_LUA="5"
export R_VER="3.4"
export CONDA_R="3.4"
export PKG_NAME="mpi4py"
export PKG_VERSION="3.0.0"
export PKG_BUILDNUM="4"
export PKG_BUILD_STRING="placeholder"
export PKG_HASH="1234567"
export RECIPE_DIR="/home/yfeng1/source/conda-channel-bccp/platform/mpi4py"
export CPU_COUNT="4"
export LANG="en_US.utf8"
export SHLIB_EXT=".so"
export PATH="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_build_env:/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_build_env/bin:/home/yfeng1/anaconda3/install/bin:/home/yfeng1/.local/bin:/home/yfeng1/.npm/node_modules/.bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
export HOME="/home/yfeng1"
export PKG_CONFIG_PATH="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pkgconfig"
export CMAKE_GENERATOR="Unix Makefiles"
export CFLAGS="-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe"
export LDFLAGS="-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now"
export DISPLAY=":0"
export LD_RUN_PATH="/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib"
export BUILD="x86_64-conda_cos6-linux-gnu"
export r_base="3.4"
export cpu_optimization_target="nocona"
export target_platform="linux-64"
export c_compiler="gcc"
export cxx_compiler="gxx"
export fortran_compiler="gfortran"
export mpi="mpich2"
export ignore_build_only_deps="['python']"
export pin_run_as_build="{'python': {'min_pin': 'x.x', 'max_pin': 'x.x'}, 'r-base': {'min_pin': 'x.x.x', 'max_pin': 'x.x.x'}, 'openmpi': {'max_pin': 'x.x'}, 'mpich': {'max_pin': 'x.x'}, 'mpich2': {'max_pin': 'x.x'}}"
export CONDA_BUILD_STATE="BUILD"
source "/home/yfeng1/anaconda3/install/bin/activate" "/home/yfeng1/anaconda3/install/conda-bld/mpi4py_1513644742163/_build_env"
#!/bin/bash

$PYTHON setup.py install
```

From older version of conda-build (3.1.3)
```
export CONDA_BUILD="1"
export PYTHONNOUSERSITE="1"
export CONDA_DEFAULT_ENV="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p"
export ARCH="64"
export PREFIX="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p"
export BUILD_PREFIX="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p"
export SYS_PREFIX="/home/yfeng1/anaconda3/install"
export SYS_PYTHON="/home/yfeng1/anaconda3/install/bin/python"
export SUBDIR="linux-64"
export SRC_DIR="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/work"
export ROOT="/home/yfeng1/anaconda3/install"
export CONDA_PY="36"
export PY3K="1"
export PY_VER="3.6"
export STDLIB_DIR="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6"
export SP_DIR="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages"
export PYTHON="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python"
export NPY_VER="1.9"
export CONDA_NPY="19"
export PERL_VER="5.26"
export CONDA_PERL="5.26"
export LUA_VER="5"
export CONDA_LUA="5"
export R_VER="3.4"
export CONDA_R="3.4"
export PKG_NAME="pfft-python"
export PKG_VERSION="0.1.14"
export PKG_BUILDNUM="3"
export PKG_BUILD_STRING="placeholder"
export PKG_HASH="1234567"
export RECIPE_DIR="/home/yfeng1/source/conda-channel-bccp/recipes/pfft-python-0.1.14"
export CPU_COUNT="4"
export LANG="en_US.utf8"
export SHLIB_EXT=".so"
export PATH="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p:/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/home/yfeng1/anaconda3/install/bin:/home/yfeng1/.local/bin:/home/yfeng1/.npm/node_modules/.bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
export HOME="/home/yfeng1"
export PKG_CONFIG_PATH="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/pkgconfig"
export CMAKE_GENERATOR="Unix Makefiles"
export CFLAGS="-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe"
export LDFLAGS="-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now"
export DISPLAY=":0"
export LD_RUN_PATH="/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib"
export BUILD="x86_64-conda_cos6-linux-gnu"
export r_base="3.4"
export cpu_optimization_target="nocona"
export target_platform="linux-64"
export c_compiler="gcc"
export cxx_compiler="gxx"
export fortran_compiler="gfortran"
export mpi="mpich2"
export pin_run_as_build="{'python': {'min_pin': 'x.x', 'max_pin': 'x.x'}, 'r-base': {'min_pin': 'x.x.x', 'max_pin': 'x.x.x'}, 'openmpi': {'max_pin': 'x.x'}, 'mpich': {'max_pin': 'x.x'}, 'mpich2': {'max_pin': 'x.x'}}"
export ignore_build_only_deps="['python']"
export CONDA_BUILD_STATE="BUILD"
source "/home/yfeng1/anaconda3/install/bin/activate" "/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p"
unset CONDA_PATH_BACKUP
export CONDA_MAX_SHLVL=2
source "/home/yfeng1/anaconda3/install/bin/activate" "/home/yfeng1/anaconda3/install/conda-bld/pfft-python_1513646785546/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p"
#!/bin/bash

# workaround mpich/openmpi not built with the new toolchain

#if [[ $OSTYPE != darwin* ]]; then
#    # for MAC use system compilers
#    # because cross complilation doesn't work
#    export OMPI_CC=$CC
#    export MPICH_CC=$CC
#    export OMPI_CXX=$CXX
#    export MPICH_CXX=$CXX
#    export OMPI_FC=$FC
#    export MPICH_FC=$FC
#    export OMPI_CPPFLAGS="$CPPFLAGS -I$CONDA_PREFIX/include"
#    export OMPI_LDFLAGS="$LDFLAGS -L$CONDA_PREFIX/lib"
#    export OMPI_LIBS=$LIBS
#    export OMPI_CFLAGS="$CFLAGS -I$CONDA_PREFIX/include"
#    export OMPI_CXXFLAGS=$CXXFLAGS
#    export OMPI_FCFLAGS=$FCFLAGS
#else
#    export LIBS="-Wl,-rpath,$CONDA_PREFIX/lib"
#    export LDFLAGS="-headerpad_max_install_names"
#    export CXXFLAGS=$CFLAGS
#fi

if [[ $OSTYPE == darwin* ]]; then
    # this may need to be done on linux too,
    # see https://github.com/ContinuumIO/anaconda-issues/issues/739
    export LDFLAGS="$LDFLAGS -Wl,-rpath,${CONDA_PREFIX}/lib"
fi

# don't know if this is useful.
export FCFLAGS="$FFLAGS"

$PYTHON setup.py install 

if [[ $OSTYPE != darwin* ]]; then
    cp $RECIPE_DIR/../../check-glibc.sh .
    bash check-glibc.sh $SP_DIR/pfft || exit 1
```

Notice the newer version defined SYS_PYTHON but not PYTHON.

**Pull request merged**
