### PR TITLE
Keep zip_keys intact

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/conda/conda-build/issues/2956
Fixes https://github.com/conda-forge/conda-smithy/issues/791

cc @sodre

### CODE REVIEW

**Comment by isuruf** [comment]
Travis-ci errors seem to be unrelated

**Comment by sodre** [comment]
Would it be worth adding a test case to make sure this does not happen again in a future update?

**Comment by isuruf** [comment]
Sure. @sodre, do you have a minimal test-case instead of the go-feedstock?

**Comment by sodre** [comment]
Touché, no I don't

**Comment by msarahan** [comment]
Test fails look like the usual dumb stuff.  Thanks for the fix.  Merging.

**Pull request merged**
