### PR TITLE
Problem: Croot path cannot be relative

### PR DESCRIPTION
**Pull request by gabm**
Solution: make any path absolute

### CODE REVIEW

**Comment by msarahan** [comment]
I haven't played much with using solely abspath - I usually do a bit more with normpath, like https://github.com/conda/conda-build/blob/9a01114a990d1fa530f82f94191f3860b1823c48/conda_build/utils.py#L248

I don't think that's strictly necessary, but I'd like to hear your opinion on whether it's a good idea.  It keeps paths cleaner as they trickle through conda-build, though I don't think it affects the actual outcome.

**Comment by gabm** [comment]
ok, I'm having a look - maybe that solves a problem that I just observed in windows with spaces in paths... I'll ping you back

**Comment by gabm** [comment]
@msarahan I updated to use normpath.. as I read indeed both is needed. mm

I still have a problem on windows that git does not clone properly when the croot contains spaces - but i think it's unrelated to this PR... so ready to be merged!

**Comment by msarahan** [comment]
Looks like the appveyor failures are there from before.  Merging.  Thanks!

**Pull request merged**
