### PR TITLE
Simplify find_config_files call

### PR DESCRIPTION
**Pull request by njalerikson**
Simplify the call and add additional documentation.

This is an attempt to split PR #4079 into smaller changes.

### CODE REVIEW

**Comment by njalerikson** [comment]
I'm *very sure* the failures are unrelated to this change. Let me know if anything else is needed here.

**Comment by mingwandroid** [comment]
Do you mind if I hold off on this PR until the next conda-build release after the one I'm about to do @njalerikson?

**Comment by mingwandroid** [comment]
Thanks!

**Comment by njalerikson** [comment]
Just to confirm - was the intention to reject these changes?

**Comment by mingwandroid** [comment]
No!

**Comment by mingwandroid** [comment]
No idea how that happened.

**Pull request merged**
