### PR TITLE
fix #2756 ignore non-rendered jinja2 in info/recipe/meta.yaml during indexing

### LINKED ISSUE #2756: 'conda index' is broken when info/recipe/meta.yaml contains non-rendered jinja2
Apparently, some older packages can contain non-rendered jinja2 in info/recipe/meta.yaml.

### PR DESCRIPTION
**Pull request by kalefranz**
fix #2756

### CODE REVIEW

**Comment by kalefranz** [comment]
CC @ilanschnell

**Comment by ilanschnell** [comment]
Thanks!  I will verify that this fix solves the original problem some of our customers have been seeing.

**Comment by msarahan** [comment]
I believe that this does not conflict with #2740 because it is its own section.  I'm OK with this being there as a catch-all gutter that may elicit more bug reports, and thus more refinement of the proper exception handling.  Merging - although version 3.7.1, which included #2740, should already fix @ilanschnell's problem.

**Comment by ilanschnell** [comment]
Thanks for merging.  The original fix #2740 already fixed my problem, and I just verified that this PR also still fixes the problem.

**Pull request merged**
