### PR TITLE
Lazy index

### PR DESCRIPTION
**Pull request by zklaus**
### Description

Update conda-build to use the new `conda.core.index.Index`.

Xref https://github.com/conda/conda/pull/13880
Xref https://github.com/conda/conda-build/issues/5154

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda-build/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by kenodegard** [comment]
@zklaus we currently don't have any memray tests hence why the memray CI job fails, do we have a test to add here or should we remove the memray CI job?

**Comment by beckermr** [comment]
@zklaus @kenodegard @jaimergp Do we not have the proper benchmark to see performance improvements from this change? Should we write one?

**Comment by kenodegard** [comment]
@beckermr I agree adding a benchmark to see the improvement would be great. I'll take a look and see if I can come up with something simple.

**Comment by kenodegard** [comment]
@beckermr I think https://github.com/conda/conda-build/pull/5508 will do the trick, I've tested this locally and saw a 10x speedup, let's see what CodSpeed says once we merge the test into `main`

**Comment by zklaus** [comment]
Regarding memray, it would be nice to have a similar reading about possible memory usage improvements. I'll see if I can add something simple to #5508 quickly.

**Comment by kenodegard** [comment]
@zklaus unfortunately #5508 has already been merged, can we instead work on adding the memray CI workflow and the associated memray test in a separate PR?

**Review by beeankha — APPROVED** [review]

**Comment by bgruening** [comment]
Could we cut a new release please with this change? We have memory problems on Azure 😔

**Comment by jaimergp** [comment]
I guess this will be included in 24.11.

**Pull request merged**
