### PR TITLE
Remove unused function call

### PR DESCRIPTION
**Pull request by isuruf**
Let's see if it passes tests

### CODE REVIEW

**Comment by msarahan** [comment]
fingers crossed.  Even if the profiling doesn't get any better/faster, it's still nice to get rid of chunks like that.

**Comment by isuruf** [comment]
saves 4.2 s out of 5 seconds

**Comment by msarahan** [comment]
awesome!  Great find!

**Comment by isuruf** [comment]
Travis error seems to be unrelated.

**Comment by msarahan** [comment]
Thanks!

**Comment by isuruf** [comment]
@msarahan, what do you think about a `distribute_variants` option which will be `True` by default? Cuts the time by half to 0.4s

**Comment by msarahan** [comment]
sure, seems fine to me.  There's probably room for a top-level api function that is an extremely minimal "just tell me about the top-level metadata" functionality.

**Pull request merged**
