### PR TITLE
Issue2521 condarc env vars WIP

### PR DESCRIPTION
**Pull request by akovner**
This PR attempts to allow the conda-build section of the .condarc file to include environment variables in the two path entries; namely, `pypirc` and `root-dir`. The changes are straightforward, but I'm not sure how to test them.

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks!  I'll push a test a little later today.  Changes look fine.

**Comment by msarahan** [comment]
I extended this good start to a few more paths, and added a test.  I think it's good to go, once we hear back from the CI services.

**Comment by msarahan** [comment]
all good.  The few failures are race conditions we haven't found time to fix yet.  Thanks for getting this going, it's a good improvement.

**Comment by akovner** [comment]
Awesome. Glad to help. I had no idea there were that many path settings.

**Pull request merged**
