### PR TITLE
Upload collected test data as artifacts

### PR DESCRIPTION
**Pull request by dholth**
### Description

We merged most of this except the last "upload" step.

Collects artifacts like these https://github.com/conda/conda-build/actions/runs/3433669396#artifacts

Necessary to generate this kind of reports, but the actual report generation happens elsewhere https://dholth.github.io/conda-build-allure/

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by dholth** [comment]
We might want to pin the pip-installed test dependency, or even package it as a conda package.

**Comment by jezdez** [comment]
> We might want to pin the pip-installed test dependency, or even package it as a conda package.

FWIW there is https://anaconda.org/pdrops/allure-pytest so somewhere, someone wrote a recipe already.

**Review by kenodegard — APPROVED** [review]

**Review by kenodegard — DISMISSED** [review]

**Review by sven6002 — APPROVED** [review]
Looks good to me

**Comment by dholth** [comment]
Thanks @kenodegard merged this into #4693

**Pull request closed without merging**
