### PR TITLE
Print the license file was packaged

### PR DESCRIPTION
**Pull request by jakirkham**
Provide feedback to the user that the license file was found and packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Not sure how this would cause CI failures. 😕

**Comment by msarahan** [comment]
Unrelated.  Don't worry about it.  Do you think it would be helpful to output more info about exactly which license file gets found?  It's a bit superfluous in my opinion, but might be helpful to resolve any potential ambiguity.

**Comment by jakirkham** [comment]
Ok, thanks for letting me know.

Thought about it. Was kind of on the fence for a few reasons. First wasn't sure if the path here was absolute, which might make things a bit noisy. Second the name of the license file is in `meta.yaml` anyways. Third we are only packaging one license file instead of multiple at this time. That said, I don't have strong feelings about it. If you would prefer to have it printed, would be happy to add it.

**Comment by msarahan** [comment]
*shrug* - I'll merge this as-is and we'll see if anyone has more to say down the road.

**Comment by jakirkham** [comment]
Thanks Mike :)

**Pull request merged**
