### PR TITLE
Master overlinking fixes post 3.20.0

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
@jjhelmus, please review.

**Comment by mingwandroid** [comment]
There's another minor fix to come for this series.

**Comment by mingwandroid** [comment]
macOS failure is a very old package cache bug we see now and then (always on macOS though).

**Comment by mingwandroid** [comment]
@jjhelmus This is ready now. Please merge if you agree and I'll prepare the release.

**Comment by jjhelmus** [comment]
LGTM, I'll merge once CI finishes.

**Pull request merged**
