### PR TITLE
run tests with conda-libmamba-solver enabled (DNM)

### PR DESCRIPTION
**Pull request by jaimergp**
I have modified the GHA workflows to install `conda-libmamba-solver` and export `CONDA_EXPERIMENTAL_SOLVER=libmamba`.

The CI pipelines are failing for different reasons (`conda skeleton`), so the errors are noisy. Fortunately, the same tests also run on Azure, so we can use those as the control group. Diffing the failures, we see that our failing tests are:

__Linux__
- [x] `tests/test_api_skeleton_cran.py::test_cran_os_type[blatr-skip: True  # [not win]]`
- [x] `tests/test_post.py::test_pypi_installer_metadata`
- [x] `tests/test_subpackages.py::test_python_line_up_with_compiled_lib` 
  - [x] Parameter: `_line_up_python_compiled_libs_top_level_same_name_output`
  - [x] Parameter: `_line_up_python_compiled_libs`
- [x] `tests/test_subpackages.py::test_subpackage_recipes[python_test_dep]`
- [x] `tests/test_subpackages.py::test_subpackage_variant_override`
- [x] `tests/test_variants.py::test_numpy_used_variable_looping`
- [x] `tests/test_api_build.py::test_version_mismatch_in_variant_does_not_infinitely_rebuild_folder`

__Windows__
- [x] `tests/test_api_build.py::test_croot_with_spaces`
- [ ] `tests/test_cli.py::test_inspect_hash_input`

Note that we need to fix that on `conda-libmamba-solver`, not here. The accompanying PR containing the necessary changes:

* https://github.com/conda-incubator/conda-libmamba-solver/pull/30

### CODE REVIEW

**Comment by jaimergp** [comment]
All tests are passing on Linux. I need to fix the Windows CI now.

**Comment by jaimergp** [comment]
The remaining failure on Windows passes locally if executed individually. To reproduce the error, you need two more tests executed before (yes, I had tons of fun bisecting the list of tests...):

```powershell
pytest -v `
  tests\test_cli.py::test_metapackage_metadata `
  tests\test_cli.py::test_inspect_installable `
  tests\test_cli.py::test_inspect_hash_input 
```

(the backtick is the escape-newline character in Powershell).

Anyway, since this seems to be an artifact of the test suite and not a problem with conda build (and this is part of `conda inspect`, which I don't think enjoys too much use these days), I won't investigate further.

**Comment by jezdez** [comment]
@jaimergp Should we try again?

**Comment by jaimergp** [comment]
Given the recent interest in using the solver in conda-forge, let's give it a new try here.

**Comment by jaimergp** [comment]
So, the results so far:


### Linux tests

- `Tests / linux (3.8, release, serial)` has multiple failures with the same error and all can be ignored because (a) it looks like a local cache corruption thingy, (b) it doesn't appear in other matrix entries, (c) tests do pass locally.
- `tests/test_api_build.py::test_recipe_builds[unicode_all_over]` in the other serial tests fails with  `SystemExit: TESTS FAILED: ♥-1-0.tar.bz2`. I don't know if unicode is allowed in conda packages, but I don't expect libmamba to support that, and I've never seen it in real life, so I think this is a clear `xfail`.
- `tests/cli/test_main_metapackage.py::test_metapackage_metadata` fails in 3.8 but passes in other Python versions. Nothing solver related anyway.

(To be updated).

**Comment by jaimergp** [comment]
I can't reproduce `tests/test_api_render.py::test_resolved_packages_recipe` locally on my macbook with:

```
# Name                    Version                   Build  Channel
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310hf8d0d8f_1004    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.0          py310hf10583b_0    conda-forge
chardet                   5.1.0           py310hbe9552e_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     23.7.2          py310hbe9552e_0    conda-forge
conda-build               3.26.1.dev19+dirty          pypi_0    pypi
conda-index               0.2.3              pyhd8ed1ab_0    conda-forge
conda-libmamba-solver     22.3.1                   pypi_0    pypi
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
coverage                  7.2.6                    pypi_0    pypi
cryptography              41.0.2          py310hdd3b5e7_0    conda-forge
docutils                  0.18.1          py310hbe9552e_1    conda-forge
exceptiongroup            1.1.1                    pypi_0    pypi
filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
flit                      3.9.0              pyhd8ed1ab_0    conda-forge
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                hffc8910_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       70.1                 h6b3803e_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
krb5                      1.21.1               h92f50d5_0    conda-forge
libarchive                3.6.2                h83f22c9_0    conda-forge
libcurl                   8.2.1                hc52a3a8_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
liblief                   0.12.3               hb7217d7_0    conda-forge
libmamba                  1.4.9                h4fa9c85_0    conda-forge
libmambapy                1.4.9           py310hb7070d9_0    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libsolv                   0.7.24               ha614eb4_1    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libxml2                   2.10.3               h67585b2_4    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
markupsafe                2.1.1           py310hf8d0d8f_1    conda-forge
more-itertools            9.1.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
openssl                   3.1.2                h53f4e23_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
psutil                    5.9.5           py310h8e9501a_0    conda-forge
py-lief                   0.12.3          py310h0f1eb42_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py310hf8d0d8f_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1           py310hbe9552e_5    conda-forge
pytest                    7.3.1                    pypi_0    pypi
pytest-cov                4.1.0                    pypi_0    pypi
python                    3.10.12         h01493a6_0_cpython    conda-forge
python-libarchive-c       5.0             py310hbe9552e_1    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h8e9501a_5    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
reproc                    14.2.3               h3422bc3_0    conda-forge
reproc-cpp                14.2.3               hbdafb3b_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h65448a5_2    conda-forge
ruamel.yaml               0.17.32         py310h2aa6e3c_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h8e9501a_1    conda-forge
ruamel_yaml               0.15.80         py310he2143c4_1006    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.2               h7e3ccbd_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomli-w                   1.0.0              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yaml-cpp                  0.7.0                hb7217d7_2    conda-forge
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.13               h53f4e23_5    conda-forge
zstandard                 0.19.0          py310had9512b_1    conda-forge
zstd                      1.5.2                h861e0a7_0    conda-forge
```

**Comment by jaimergp** [comment]
And I can't reproduce `tests/test_api_build.py::test_build_msvc_compiler[14.0]` on the Windows VM either. 🤷

**Comment by jaimergp** [comment]
We can't mock the index like this because later conda-build internals will still try to find the PackageRecord entries in there. So we are paying twice to build the index and working that out will involve messing with a few parts of build internals.

Even with `conda` now [lazily loading the `PackageRecord` list](https://github.com/conda/conda/blob/875ed9149862d3c1ff9f96bd53939139b5624bff/conda/core/subdir_data.py#L89-L90), this becomes a futile exercise because conda-build will iterate the whole thing right away in via [`conda.core.index.fetch_index()`](https://github.com/conda/conda/blob/875ed9149862d3c1ff9f96bd53939139b5624bff/conda/core/index.py#L101) and then _again_ in [`conda.exports.{get,fetch}_index()`](https://github.com/conda/conda/blob/875ed9149862d3c1ff9f96bd53939139b5624bff/conda/exports.py#L239-L257), just to have the `Dist -> PackageRecord` mapping 🤷 

So I am afraid we can't easily avoid that index loading overhead.

**Comment by dholth** [comment]
@jaimergp I'm interested in that Dist -> PackageRecord mapping, seems like we could make that more efficient. They enjoyed iterating over everything.

**Comment by jaimergp** [comment]
> @jaimergp I'm interested in that Dist -> PackageRecord mapping, seems like we could make that more efficient. They enjoyed iterating over everything.

I'll open an issue!

**Pull request closed without merging**
