### PR TITLE
Conda Convert - Update the info/paths.json file

### LINKED ISSUE #1678: paths.json not updated during causing installation failure in conda 4.3.4
When converting from a win-64 package to a linux-64 package the `Lib/site-packages` directory should become `lib/python2.7/site-packages`. This is correctly updated in 'files' but should be updated in paths.json also. Otherwise this error is given when installing under conda 4.3.4 on Linux:

`
CondaError: Cannot link a source that does not exist. /home/NETWORK/e.hughes/miniconda3/pkgs/package-v1.0.0/Lib/site-packages/package-v1.0.0-py2.7.egg-info
`

### PR DESCRIPTION
**Pull request by ElliotJH**
This file is now used in Conda 4.3 to identify files to be hardlinked.

Fixes #1678

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks @ElliotJH!  This looks great.  Do you mind adding a test?  Do you need any help with how to do that?

**Comment by ElliotJH** [comment]
(I can fix those test failures, just need to handle the older package format properly again.)

For the new test: it looks like I could parameterise `test_convert_platform_to_others` to check two different packages, one old and one new and then maybe validate the paths.json if present? Open to other suggestions.

**Comment by msarahan** [comment]
Sure, your proposal sounds like a reasonable approach. Please ask if you have any issues with how to do the parameterization. Happy to help.

**Comment by msarahan** [comment]
@ElliotJH do you mind signing the CLA?  You don't need to if you have already signed Conda's; unfortunately we don't have a unified one yet.

**Comment by msarahan** [comment]
@ElliotJH just pinging you one more time on the CLA.  I can't merge your PR unless you sign it.  Please tell us whether or not you're willing to sign it.  If not, we'll need to re-implement your fixes in our own way, and I'd really rather be able to give you credit for the work you've done.

**Comment by ElliotJH** [comment]
@msarahan It should be ok. I just need to get an approval for it from my employer which isn't possible over the weekend. Should have it tomorrow.

**Comment by msarahan** [comment]
Excellent!  Thanks again.

**Comment by kalefranz** [comment]
Thanks @ElliotJH both for the PR itself and for working through the CLA hassle.  We're eager to get this merged :)

**Comment by msarahan** [comment]
@ElliotJH any word from your employer?

**Comment by ElliotJH** [comment]
It's making its way through the process. I'm really sorry for the delay, it should be soon.

**Comment by msarahan** [comment]
No problem, just checking in.  Thanks for going through the trouble.

**Comment by ElliotJH** [comment]
Signed, ready to go.

**Comment by msarahan** [comment]
Thanks Elliot!

**Pull request merged**
