### PR TITLE
Fix typo in cran skeleton

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Thanks

**Comment by isuruf** [comment]
Did you mean to close without merging?

**Comment by mingwandroid** [comment]
Nope!

**Comment by isuruf** [comment]
Thanks

**Comment by jdblischak** [comment]
Wow. I was always curious why that extra logic was added since it would rarely be used (and never by conda-forge). Thanks @isuruf for finding the issue and simplifying build scripts for R package binaries! 🎉

**Pull request merged**
