### PR TITLE
Remove the work directory earlier in the build

### PR DESCRIPTION
**Pull request by asmeurer**
See #322. The templating of the meta.yaml might pull in false information from
previous work directories.

Note that I left the removal in the provide() function because it
can be called from elsewhere.

### CODE REVIEW

**Comment by tswicegood** [comment]
This is going to make builds potentially slower.  One advantage to this directory sticking around is that only new data has to be pushed.  Rather than force the directory removal, what about naming the directory something unique to the project.  Say `os.path.join(work_dir, slugified_pkg_name)`?  Might be more work than its worth, but that's what I thought was happening.

**Comment by asmeurer** [comment]
I don't follow you. The work directory is already always removed, just in a different place (when the source is retrieved).

**Comment by tswicegood** [comment]
It might be that my understanding of what was happening is flawed.  As I understood it with the directory still being there a pull was done instead of a clone.  I don't remember if that was an assumption or if I based that on code.  I thought I had seen code to that effect, but might be mistaken.

**Comment by asmeurer** [comment]
I see. No, that doesn't happen. See https://github.com/conda/conda-build/blob/72c4e8610692c0d92d91f7c0d465ee14b1f95a7c/conda_build/source.py#L246. I suppose could special-case git and do a `git clean -df; git clean -Xdf; git checkout`. I'm not really sure it would be that much faster. I do often see removing the work and build directories take a few seconds (usually more the build directory than the work directory), though that's typically only on my VMs with slow filesystems. But even then it's never been something that I've felt was slow enough to warrant trying to avoid.

**Comment by tswicegood** [comment]
Fair enough.  :+1: on this.

**Pull request merged**
