### PR TITLE
Fix stdlib being recognized in variant hash inputs

### PR DESCRIPTION
**Pull request by mbargull**
### Description

Fixes gh-5190.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by mbargull** [comment]
```
tests/test_metadata.py::test_native_stdlib_metadata[linux-64-sysroot-2.12] 
[gw1] [ 43%] FAILED tests/test_metadata.py::test_native_stdlib_metadata[linux-64-sysroot-2.12] 
tests/test_metadata.py::test_native_stdlib_metadata[linux-aarch64-sysroot-2.17] 
[gw1] [ 43%] FAILED tests/test_metadata.py::test_native_stdlib_metadata[linux-aarch64-sysroot-2.17] 
tests/test_metadata.py::test_native_stdlib_metadata[osx-64-macosx_deployment_target-10.13] 
[gw1] [ 43%] FAILED tests/test_metadata.py::test_native_stdlib_metadata[osx-64-macosx_deployment_target-10.13] 
tests/test_metadata.py::test_native_stdlib_metadata[osx-arm64-macosx_deployment_target-11.0] 
[gw1] [ 43%] FAILED tests/test_metadata.py::test_native_stdlib_metadata[osx-arm64-macosx_deployment_target-11.0] 
```

**Comment by mbargull** [comment]
pre-commit.ci autofix

**Review by h-vetinari — APPROVED** [review]
Thank you very much for tackling this! 🙏 

The changes LGTM.

**Review by beeankha — APPROVED** [review]

**Comment by h-vetinari** [comment]
Thank you all! :)

Given that this is a straightforward and well-scoped patch for functionality that isn't in use anywhere yet, and arguably a bugfix for a faulty implementation in #4999, would you consider a backport to 24.1.x?

The reason I'm asking is because a lot of work in conda-forge is backed up on this (w.r.t. moving to glibc 2.17 resp. macOS 10.13, both of which are getting more pressing every week), and so it would be great to reduce time spent waiting for procedure, and hopefully reduce the hair-on-fire likelihood later on this year by starting some very long-running things (like migrating all our compiled recipes to contain `{{ stdlib("c") }}` , c.f. https://github.com/regro/cf-scripts/pull/2135) as soon as possible.

Independently of your choice for how to handle this in conda-build itself, I'll also propose this for backporting on the conda-forge feedstock, which would be "good enough" for unblocking work in https://github.com/conda-forge/conda-forge.github.io/issues/1844, though of course a new patch version would be preferable.

**Pull request merged**
