### PR TITLE
Add QuickTime Kit Framework to default missing_dso_whitelist

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by mingwandroid** [comment]
The default whitelist is something I'm not 100% on (should anything exist, should we put this in a file instead?)..

Also not sure this is 'core' enough as not many things will use Quicktime these days and I expect it's deprecated.

Sorry to be so indecisive, passing the buck right along to @msarahan

**Comment by nehaljwani** [comment]
I added it here since wxpython needed it. If it's deprecated, then oh, well.

**Comment by mingwandroid** [comment]
Your can add it to the recipe? builds/missing_dso_whitelist

**Comment by msarahan** [comment]
I'd prefer to add it to wxpython, and if we encounter it again, then we should add it here.

**Comment by msarahan** [comment]
@nehaljwani I'm going to close this for now, but I'm open to re-opening it if you want to discuss this more.

**Pull request closed without merging**
