### PR TITLE
Master 3.20.2 release

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Ping @jjhelmus. If this is merged, then we can tag 3.20.2 (though merging might do that? I dunno, tags I never fully grok!)

**Comment by jjhelmus** [comment]
For releasing with rever the CHANGELOG.txt should not be edited directly.  Rather create a file in the news directory.  `rever` will take care of creating the tag, updating the CHANGELOG.txt and uploading a static tarball to the GH release entry.

**Comment by mingwandroid** [comment]
It wasn't edited directly, I just skipped adding news entries to git and did it locally. Does it matter?

**Comment by mingwandroid** [comment]
The only workflow difference between this and 3.20.0 was that I made a PR this time instead of just merging to master.

**Comment by jjhelmus** [comment]
> The only workflow difference between this and 3.20.1 was that I made a PR this time instead of just merging to master.

I'm following now.  I think it it better push to master.  A PR will create a merge commit which will not align with the tag that rever creates.

**Comment by kenodegard** [comment]
[conda-build 3.20.2](https://github.com/conda/conda-build/releases/tag/3.20.2) was released in September 2020, this is no longer needed

**Pull request closed without merging**
