### PR TITLE
Fix import for auxlib.

### LINKED ISSUE #4333: ImportError when trying to import from previously vendored auxlib
### Actual Behavior

conda-build imports from a "vendored" version of the auxlib in conda, which was recently inlined since it diverged significantly from the upstream project. https://github.com/conda/conda/pull/11025

### Expected Behavior

There shouldn't be an ImportError when trying to import from auxlib.

Code in question: https://github.com/conda/conda-build/blob/a3af116b7192a31d000e4b36e766f73368310901/conda_build/environ.py#L191

### PR DESCRIPTION
**Pull request by jezdez**
Fix #4333.

### CODE REVIEW

**Review by JanuszL — APPROVED** [review]

**Review by mbargull — CHANGES_REQUESTED** [review]
Please move this to `conda_interface`

**Review by mbargull — APPROVED** [review]

**Review by kenodegard — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Jannis! 😄

Was there anything else still needed here or is this ready to go?

**Comment by jezdez** [comment]
> Thanks Jannis! 😄
> 
> Was there anything else still needed here or is this ready to go?

Nope, nothing, we'll do a conda-build release this week with this.

**Comment by jakirkham** [comment]
Sounds good. Thanks for the update! 🙂

**Comment by bryevdv** [comment]
Is this in a release yet? Our CI just broke, and updating everything (conda, conda-build) to latest did not seem to fix.

**Comment by kenodegard** [comment]
`conda-build` 3.21.7 was released to defaults on Monday (containing this fix)
`conda` 4.11.0 was released to defaults <30min ago

**Pull request merged**
