### PR TITLE
Update README with testing dependencies

### PR DESCRIPTION
**Pull request by kenodegard**
README is missing some dependencies needed to run the test suite.

### CODE REVIEW

**Comment by jezdez** [comment]
@anaconda-issue-bot check

**Comment by jezdez** [comment]
@kenodegard Hey Ken! The development and CI setup is pretty messy and there is a bunch of old and outdated installation scripts/docs in this repo, including the README. I've been meaning to clean that up and move the repo to GitHub Actions like conda (in the mid-term), but this is probably a good step in between.

One thing that I did for example in the conda repo recently was putting the deps for running the tests into one [tests/requirements.txt](https://github.com/conda/conda/blob/master/tests/requirements.txt) file, which can be used when creating a conda env during CI setup, e.g.: for the [Linux CI Docker image](https://github.com/conda/conda/blob/0b1312ce65bf0fbb8cbea3750f07c32a2492c57a/ci/Dockerfile#L26-L32) and for [Windows](https://github.com/conda/conda/blob/0b1312ce65bf0fbb8cbea3750f07c32a2492c57a/ci/scripts/windows/setup.bat#L10) so the various environments are in sync and we get to dev/prod parity.

Do you think we could already do something like this here or should we open a separate ticket for it?

**Comment by kenodegard** [comment]
@jezdez moved the dependencies into `tests/requirements.txt` and updated `README.rst` to specify the correct `conda install` command

**Review by jezdez — APPROVED** [review]

**Comment by jezdez** [comment]
Cheers @kenodegard!

**Pull request merged**
