### PR TITLE
WIP: add option to disable intermediate git cache

### PR DESCRIPTION
**Pull request by msarahan**
Intended to address https://github.com/conda/conda-build/issues/1462 but not working meaningfully yet.  Needs reproducer of LFS issue.

### CODE REVIEW

**Comment by loriab** [comment]
FYI, I hit the LFS issue. Applied this patch atop current conda pkgs (versions below). Hardcoded the `def ...(..., cache=cache)` to False to invoke it. Got the error below (truncated) upon conda-build. I'll just revert and build from local source, but if you'd like anything tested (or the full debug log posted), please let me know.

```
conda                     4.3.23                   py27_0    defaults
conda-build               3.0.9                    py27_0    defaults
conda-env                 2.6.0                         0    anaconda
```


```
DEBUG:conda.instructions: LINK(Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'pip-9.0.1-py27_1', name=u'pip', version=u'9.0.1', build_string=u'py27_1', build_number=1, with_features_depends=None, base_url=None, platform=None))
DEBUG:conda.instructions: SYMLINK_CONDA('/Users/loriab/linux/miniconda3')
DEBUG:conda.instructions:Conda environment at /Users/loriab/linux/miniconda3/conda-bld/qcdb_1502235921093/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol start with '_'. Skipping symlinking conda.
fatal: Not a git repository (or any of the parent directories): .git
+ export REQUESTS_CA_BUNDLE=
+ REQUESTS_CA_BUNDLE=
+ export SP_DIR=/Users/loriab/linux/miniconda3/conda-bld/qcdb_1502235921093/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python2.7/site-packages

...

BUILD START: [u'qcdb-0.5-py27h69ad184_3.tar.bz2']

The following NEW packages will be INSTALLED:

    openssl:    1.0.2l-0      defaults
    pip:        9.0.1-py27_1  defaults
    python:     2.7.13-0      defaults
    readline:   6.2-2         defaults
    setuptools: 27.2.0-py27_0 defaults
    sqlite:     3.13.0-0      defaults
    tk:         8.5.18-0      defaults
    wheel:      0.29.0-py27_0 defaults
    zlib:       1.2.8-3       defaults

Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was:
Command '['/usr/bin/git', 'fetch']' returned non-zero exit status 128
source tree in: /Users/loriab/linux/miniconda3/conda-bld/qcdb_1502235921093/work
Traceback (most recent call last):
  File "/Users/loriab/linux/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/loriab/linux/miniconda3/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 387, in main
    execute(sys.argv[1:])
  File "/Users/loriab/linux/miniconda3/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 378, in execute
    noverify=args.no_verify)
  File "/Users/loriab/linux/miniconda3/lib/python2.7/site-packages/conda_build/api.py", line 184, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/loriab/linux/miniconda3/lib/python2.7/site-packages/conda_build/build.py", line 1715, in build_tree
    notest=notest,
  File "/Users/loriab/linux/miniconda3/lib/python2.7/site-packages/conda_build/build.py", line 1124, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/Users/loriab/linux/miniconda3/lib/python2.7/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/Users/loriab/linux/miniconda3/lib/python2.7/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/Users/loriab/linux/miniconda3/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/Users/loriab/linux/miniconda3/conda-bld/qcdb_1502235921093/work/conda_build.sh']' returned non-zero exit status 1
```

**Comment by msarahan** [comment]
I can haz recipe?

Thanks!

**Comment by loriab** [comment]
Sure, it's a really stupid move-data-into-place recipe for a journal suppmat, but it does involve one very large file (`SSI_DbLoaded.pickle`) under git-lfs control.

`qcdb/meta.yaml`
```
qcdb/meta.yaml 
{% set version = "0.5" %}

package:
  name: qcdb
  version: {{ version }}

source:
  #path: ../../../../../../linux/qcdb
  git_url: https://github.com/cdsgroup/qcdb.git
  git_tag: master

build:
  skip: true           # [win]
  number: 3

requirements:
  build:
    - python 2.7*                 # define site-packages install dir
  run:
    - python 2.7*

test:
  commands:
    - conda list
  imports:
    - qcdb
```

`qcdb/build.sh`
```
PY_ABBR="python2.7"
PYPATH="${PREFIX}/lib/${PY_ABBR}/site-packages"

# install
mkdir -p ${PYPATH}/qcdb
cp qcdb/__init__.py                ${PYPATH}/qcdb/
cp qcdb/balancederror.py           ${PYPATH}/qcdb/
cp qcdb/basislist.py               ${PYPATH}/qcdb/
cp qcdb/basislistdunning.py        ${PYPATH}/qcdb/
cp qcdb/basislistother.py          ${PYPATH}/qcdb/
cp qcdb/cfour.py                   ${PYPATH}/qcdb/
cp qcdb/cov_radii.py               ${PYPATH}/qcdb/
cp qcdb/dashparam.py               ${PYPATH}/qcdb/
cp qcdb/dbproc.py                  ${PYPATH}/qcdb/
cp qcdb/dbwrap.py                  ${PYPATH}/qcdb/
cp qcdb/exceptions.py              ${PYPATH}/qcdb/
cp qcdb/inputparser.py             ${PYPATH}/qcdb/
cp qcdb/interface_dftd3.py         ${PYPATH}/qcdb/
cp qcdb/jajo.py                    ${PYPATH}/qcdb/
cp qcdb/libmintsbasisset.py        ${PYPATH}/qcdb/
cp qcdb/libmintsbasissetparser.py  ${PYPATH}/qcdb/
cp qcdb/libmintscoordentry.py      ${PYPATH}/qcdb/
cp qcdb/libmintsgshell.py          ${PYPATH}/qcdb/
cp qcdb/libmintsmolecule.py        ${PYPATH}/qcdb/
cp qcdb/libmintspointgrp.py        ${PYPATH}/qcdb/
cp qcdb/modelchems.py              ${PYPATH}/qcdb/
cp qcdb/molecule.py                ${PYPATH}/qcdb/
cp qcdb/molpro.py                  ${PYPATH}/qcdb/
cp qcdb/molpro2.py                 ${PYPATH}/qcdb/
cp qcdb/molpro_basissets.py        ${PYPATH}/qcdb/
cp qcdb/mpl.py                     ${PYPATH}/qcdb/
cp qcdb/options.py                 ${PYPATH}/qcdb/
cp qcdb/orca.py                    ${PYPATH}/qcdb/
cp qcdb/orient.py                  ${PYPATH}/qcdb/
cp qcdb/p4regex.py                 ${PYPATH}/qcdb/
cp qcdb/parker.py                  ${PYPATH}/qcdb/
cp qcdb/pdict.py                   ${PYPATH}/qcdb/
cp qcdb/periodictable.py           ${PYPATH}/qcdb/
cp qcdb/physconst.py               ${PYPATH}/qcdb/
cp qcdb/psi4.py                    ${PYPATH}/qcdb/
cp qcdb/psiutil.py                 ${PYPATH}/qcdb/
cp qcdb/psivardefs.py              ${PYPATH}/qcdb/
cp qcdb/psivarrosetta.py           ${PYPATH}/qcdb/
cp qcdb/qcformat.py                ${PYPATH}/qcdb/
cp qcdb/qchem.py                   ${PYPATH}/qcdb/
cp qcdb/subsetgenerator.py         ${PYPATH}/qcdb/
cp qcdb/textables.py               ${PYPATH}/qcdb/
cp qcdb/thermo.py                  ${PYPATH}/qcdb/
cp qcdb/vecutil.py                 ${PYPATH}/qcdb/

mkdir ${PYPATH}/databases/
cp databases/HSG.py                ${PYPATH}/databases/
cp databases/HBC6.py               ${PYPATH}/databases/
cp databases/NBC10.py              ${PYPATH}/databases/
cp databases/S22.py                ${PYPATH}/databases/
cp databases/UBQ.py                ${PYPATH}/databases/
cp databases/S66.py                ${PYPATH}/databases/
cp databases/JSCH.py               ${PYPATH}/databases/
cp databases/ACONF.py              ${PYPATH}/databases/
cp databases/SCONF.py              ${PYPATH}/databases/
cp databases/CYCONF.py             ${PYPATH}/databases/
cp databases/NBC10ext.py           ${PYPATH}/databases/
cp databases/ACHC.py               ${PYPATH}/databases/
cp databases/BBI.py                ${PYPATH}/databases/
cp databases/SSI.py                ${PYPATH}/databases/
cp databases/PCONF.py              ${PYPATH}/databases/
cp databases/S22by7.py             ${PYPATH}/databases/
cp databases/A24.py                ${PYPATH}/databases/

mkdir ${PYPATH}/data/
cp data/SSI_saptmisc.py            ${PYPATH}/data/
cp data/SSI_bfdbmm.py              ${PYPATH}/data/
cp data/SSI_dfit.py                ${PYPATH}/data/
cp data/SSI_dfitm.py               ${PYPATH}/data/
cp data/SSI_bfdbdft.py             ${PYPATH}/data/
cp data/SSI_bfdbdftm.py            ${PYPATH}/data/
cp data/SSI_pt2misc.py             ${PYPATH}/data/
cp data/SSI_ccmisc.py              ${PYPATH}/data/
cp data/SSI_dftmisc.py             ${PYPATH}/data/
cp data/SSI_hrxn_saptmisc.pickle   ${PYPATH}/data/
cp data/SSI_hrxn_bfdbmm.pickle     ${PYPATH}/data/
cp data/SSI_hrxn_dfit.pickle       ${PYPATH}/data/
cp data/SSI_hrxn_dfitm.pickle      ${PYPATH}/data/
cp data/SSI_hrxn_bfdbdft.pickle    ${PYPATH}/data/
cp data/SSI_hrxn_bfdbdftm.pickle   ${PYPATH}/data/
cp data/SSI_hrxn_pt2misc.pickle    ${PYPATH}/data/
cp data/SSI_hrxn_ccmisc.pickle     ${PYPATH}/data/
cp data/SSI_hrxn_dftmisc.pickle    ${PYPATH}/data/
cp data/SSI_WDb.pickle             ${PYPATH}/data/
cp data/SSI_Db.pickle              ${PYPATH}/data/
cp data/SSI_DbLoaded.pickle        ${PYPATH}/data/
```

**Comment by msarahan** [comment]
Perfect. Enough to write a test and dig in. Thanks!

On Aug 8, 2017 8:38 PM, "Lori A. Burns" <notifications@github.com> wrote:

Sure, it's a really stupid move-data-into-place recipe for a journal
suppmat, but it does involve one very large file (SSI_DbLoaded.pickle)
under git-lfs control.

qcdb/meta.yaml

qcdb/meta.yaml
{% set version = "0.5" %}

package:
  name: qcdb
  version: {{ version }}

source:
  #path: ../../../../../../linux/qcdb
  git_url: https://github.com/cdsgroup/qcdb.git
  git_tag: master

build:
  skip: true           # [win]
  number: 3

requirements:
  build:
    - python 2.7*                 # define site-packages install dir
  run:
    - python 2.7*

test:
  commands:
    - conda list
  imports:
    - qcdb

qcdb/build.sh

PY_ABBR="python2.7"
PYPATH="${PREFIX}/lib/${PY_ABBR}/site-packages"

# install
mkdir -p ${PYPATH}/qcdb
cp qcdb/__init__.py                ${PYPATH}/qcdb/
cp qcdb/balancederror.py           ${PYPATH}/qcdb/
cp qcdb/basislist.py               ${PYPATH}/qcdb/
cp qcdb/basislistdunning.py        ${PYPATH}/qcdb/
cp qcdb/basislistother.py          ${PYPATH}/qcdb/
cp qcdb/cfour.py                   ${PYPATH}/qcdb/
cp qcdb/cov_radii.py               ${PYPATH}/qcdb/
cp qcdb/dashparam.py               ${PYPATH}/qcdb/
cp qcdb/dbproc.py                  ${PYPATH}/qcdb/
cp qcdb/dbwrap.py                  ${PYPATH}/qcdb/
cp qcdb/exceptions.py              ${PYPATH}/qcdb/
cp qcdb/inputparser.py             ${PYPATH}/qcdb/
cp qcdb/interface_dftd3.py         ${PYPATH}/qcdb/
cp qcdb/jajo.py                    ${PYPATH}/qcdb/
cp qcdb/libmintsbasisset.py        ${PYPATH}/qcdb/
cp qcdb/libmintsbasissetparser.py  ${PYPATH}/qcdb/
cp qcdb/libmintscoordentry.py      ${PYPATH}/qcdb/
cp qcdb/libmintsgshell.py          ${PYPATH}/qcdb/
cp qcdb/libmintsmolecule.py        ${PYPATH}/qcdb/
cp qcdb/libmintspointgrp.py        ${PYPATH}/qcdb/
cp qcdb/modelchems.py              ${PYPATH}/qcdb/
cp qcdb/molecule.py                ${PYPATH}/qcdb/
cp qcdb/molpro.py                  ${PYPATH}/qcdb/
cp qcdb/molpro2.py                 ${PYPATH}/qcdb/
cp qcdb/molpro_basissets.py        ${PYPATH}/qcdb/
cp qcdb/mpl.py                     ${PYPATH}/qcdb/
cp qcdb/options.py                 ${PYPATH}/qcdb/
cp qcdb/orca.py                    ${PYPATH}/qcdb/
cp qcdb/orient.py                  ${PYPATH}/qcdb/
cp qcdb/p4regex.py                 ${PYPATH}/qcdb/
cp qcdb/parker.py                  ${PYPATH}/qcdb/
cp qcdb/pdict.py                   ${PYPATH}/qcdb/
cp qcdb/periodictable.py           ${PYPATH}/qcdb/
cp qcdb/physconst.py               ${PYPATH}/qcdb/
cp qcdb/psi4.py                    ${PYPATH}/qcdb/
cp qcdb/psiutil.py                 ${PYPATH}/qcdb/
cp qcdb/psivardefs.py              ${PYPATH}/qcdb/
cp qcdb/psivarrosetta.py           ${PYPATH}/qcdb/
cp qcdb/qcformat.py                ${PYPATH}/qcdb/
cp qcdb/qchem.py                   ${PYPATH}/qcdb/
cp qcdb/subsetgenerator.py         ${PYPATH}/qcdb/
cp qcdb/textables.py               ${PYPATH}/qcdb/
cp qcdb/thermo.py                  ${PYPATH}/qcdb/
cp qcdb/vecutil.py                 ${PYPATH}/qcdb/

mkdir ${PYPATH}/databases/
cp databases/HSG.py                ${PYPATH}/databases/
cp databases/HBC6.py               ${PYPATH}/databases/
cp databases/NBC10.py              ${PYPATH}/databases/
cp databases/S22.py                ${PYPATH}/databases/
cp databases/UBQ.py                ${PYPATH}/databases/
cp databases/S66.py                ${PYPATH}/databases/
cp databases/JSCH.py               ${PYPATH}/databases/
cp databases/ACONF.py              ${PYPATH}/databases/
cp databases/SCONF.py              ${PYPATH}/databases/
cp databases/CYCONF.py             ${PYPATH}/databases/
cp databases/NBC10ext.py           ${PYPATH}/databases/
cp databases/ACHC.py               ${PYPATH}/databases/
cp databases/BBI.py                ${PYPATH}/databases/
cp databases/SSI.py                ${PYPATH}/databases/
cp databases/PCONF.py              ${PYPATH}/databases/
cp databases/S22by7.py             ${PYPATH}/databases/
cp databases/A24.py                ${PYPATH}/databases/

mkdir ${PYPATH}/data/
cp data/SSI_saptmisc.py            ${PYPATH}/data/
cp data/SSI_bfdbmm.py              ${PYPATH}/data/
cp data/SSI_dfit.py                ${PYPATH}/data/
cp data/SSI_dfitm.py               ${PYPATH}/data/
cp data/SSI_bfdbdft.py             ${PYPATH}/data/
cp data/SSI_bfdbdftm.py            ${PYPATH}/data/
cp data/SSI_pt2misc.py             ${PYPATH}/data/
cp data/SSI_ccmisc.py              ${PYPATH}/data/
cp data/SSI_dftmisc.py             ${PYPATH}/data/
cp data/SSI_hrxn_saptmisc.pickle   ${PYPATH}/data/
cp data/SSI_hrxn_bfdbmm.pickle     ${PYPATH}/data/
cp data/SSI_hrxn_dfit.pickle       ${PYPATH}/data/
cp data/SSI_hrxn_dfitm.pickle      ${PYPATH}/data/
cp data/SSI_hrxn_bfdbdft.pickle    ${PYPATH}/data/
cp data/SSI_hrxn_bfdbdftm.pickle   ${PYPATH}/data/
cp data/SSI_hrxn_pt2misc.pickle    ${PYPATH}/data/
cp data/SSI_hrxn_ccmisc.pickle     ${PYPATH}/data/
cp data/SSI_hrxn_dftmisc.pickle    ${PYPATH}/data/
cp data/SSI_WDb.pickle             ${PYPATH}/data/
cp data/SSI_Db.pickle              ${PYPATH}/data/
cp data/SSI_DbLoaded.pickle        ${PYPATH}/data/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda/conda-build/pull/2186#issuecomment-321119747>,
or mute
the thread

**Comment by beeankha** [comment]
This pull request is being closed in order to reduce the number of outdated/stale PRs on this repo; if this work is still actively in progress, please feel free to re-open!

**Pull request closed without merging**
