### PR TITLE
Fix/license family

### PR DESCRIPTION
**Pull request by caseyclements**
* improve logic used to filter by license_family.
  * make consistent with conda-build by moving logic to there.

Plan is to merge, then create a new release. See changelog

### CODE REVIEW

**Comment by msarahan** [comment]
LGTM.  Do you mind breaking up the tests, or does that not make sense?  I generally prefer to keep test cases shorter and more focused.

**Comment by msarahan** [comment]
Travis failure is due to bad multiprocessing.  No worries there.  Just ignore it.  

As a Continuum employee, you're not strictly required to sign the CLA, but it would be nice.

**Comment by caseyclements** [comment]
Broken up, and added a few more. This revealed a new special case that I fixed up. 'GPL (>= 2)' was choosing GPL2, where I feel the better choice is GPL3. 'GPL >= 2', and 'GPL>=2', were covered already handled as GPL3.

**Comment by msarahan** [comment]
Cool, thanks.  Travis CI is toast right now, but I'll close and reopen this PR once it is behaving again and then merge.

**Comment by msarahan** [comment]
Looks like you have the same error across the CI's (plus one or two sporadic ones you can ignore):

https://travis-ci.org/conda/conda-build/jobs/172389286#L1003

**Comment by msarahan** [comment]
All clear here.  Travis failures look like CI race condition to me.  Merging.

**Pull request merged**
