### PR TITLE
Improvements to CRAN skeletons

### PR DESCRIPTION
**Pull request by mcg1969**
Three changes:

- Add Windows-specific `sed` and `coreutils` build dependencies whenever `make` is added, because the Makefiles seem to require these. Otherwise I would get errors that `sed` and `basename` were missing.
- Remove the `automake` build dependency. We don't actually _have_ an automake package; instead, we have `automake-wrapper` (which is already included), and this in turn pulls in all the versions of `automake` that we have. I don't know why it's structured this way, but it is!
- Add `zip` as a build dependency on Windows. I've noted that the Windows build step requires `zip`. I think it's used just to build the binary package, which if I understand correctly we don't need. But seeing the error when it fails to run `zip` makes me uneasy. I'd rather either patch the Makefile or just let it succeed.

As an example, here are the build dependencies for `fgarch` after this is applied:
```
# Suggests: RUnit, tcltk
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
```

### CODE REVIEW

**Comment by mcg1969** [comment]
And here's the build dependencies for `r-akima`:
```
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
```

**Comment by mcg1969** [comment]
Looks like #2963 does part of this.

**Comment by mcg1969** [comment]
Ah! sed's there twice in that second one.

**Comment by mcg1969** [comment]
Revised `r-akima` results:
```
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
```

**Comment by msarahan** [comment]
Looks fine to me.  @mingwandroid can you please take a look?  The test failures are unrelated to this PR.

**Comment by mingwandroid** [comment]
LGTM.

**Comment by mingwandroid** [comment]
Oh, sorry, I just spotted this, `automake` should have a `# [not win]` selector on it here rather than being removed.

**Comment by mcg1969** [comment]
Crap! I didn’t know that. Good catch

**Comment by mcg1969** [comment]
I will fix

**Comment by msarahan** [comment]
Thanks both.  Hoping to cut a release sometime tomorrow.  No rush, though, just it's about time for one.

**Pull request merged**
