### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by jjhelmus**
cherry-picked commits from PR #4010 that are ready to be merged.

### CODE REVIEW

**Comment by wolfv** [comment]
I believe that the call to `create_info_files` in line 2853 will fail right now because the API changed (needs a replacement object).

**Comment by wolfv** [comment]
I don't understand what this replacements stuff is about actually, and why it was necessary to change the API in this way? I understand that these are internal functions but still :)

Is there some docs on the replacement?

**Comment by mingwandroid** [comment]
You can just ignore it until it's documented.

**Comment by mingwandroid** [comment]
Without the CBC keys to drive it it does nothing, yes the code is used, but for the old prefix replacement stuff, which still works as before.

I will change internal APIs occasionally in the interest of cleanup, sorry.

**Comment by mingwandroid** [comment]
Ah I see what you mean about line 2853, will fix it, thanks

**Comment by mingwandroid** [comment]
https://github.com/conda/conda-build/pull/4041

**Comment by wolfv** [comment]
just FYI we're using the same functions in boa, that's why I noticed that it now fails :)

**Comment by mingwandroid** [comment]
OK, sorry about the breakage! Good luck with boa.

**Pull request merged**
