### PR TITLE
Fix post.py when SDK has install names surrounded by single qoutes

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Any idea how this happens?

**Comment by mingwandroid** [comment]
Could I request a news entry @isuruf?

**Comment by isuruf** [comment]
11.0 SDK has `install-name:    '/usr/lib/libSystem.B.dylib'` instead of `install-name:    /usr/lib/libSystem.B.dylib`

> Seems fine though, should we also check for starting with a "'"?

We've already removed the first character assuming it is `/`. So we can't check that it is `'`. I think it's fine to just check the last character.

**Comment by mingwandroid** [comment]
Thank you @isuruf!

**Comment by mingwandroid** [comment]
I was wondering about file names that contain a single literal "'" here, but I guess that'll never happen as it'd break Apple's .tbd parser anyway.

**Pull request merged**
