### PR TITLE
fix PEP420 namespace packages 

### PR DESCRIPTION
**Pull request by ikalev**
See #1074  for details.

### CODE REVIEW

**Comment by msarahan** [comment]
@ikalev sorry I forgot earlier, this has been proposed once before: https://github.com/conda/conda-build/pull/859

There, I suggested one change: throw an exception if copying would overwrite any file(s).  I think that this is very important for sanity - otherwise it is ill-defined what the contents of your files are.  Any ideas on that point?

**Comment by ikalev** [comment]
@msarahan It's a bit of a grey zone: If we are merging namespace packages some overwriting might happen and that might be okay in edge cases... But otherwise it would be an error indeed.

I think it's reasonable to ignore said edge cases and assume that this is an error. I'll try to extend the implementation with an explicit check. Should be easy.

**Comment by ikalev** [comment]
@msarahan should be good to merge now.

**Comment by msarahan** [comment]
Looks great.  Minor PEP8 errors and existing errors on Travis.  Will wait for AppVeyor, then merge.

**Comment by msarahan** [comment]
(I am happy to fix PEP8 - you don't need another push.)

**Comment by msarahan** [comment]
Thanks again, @ikalev

**Comment by ikalev** [comment]
Great, thanks!

**Comment by 183amir** [comment]
Thank you this is awesome. Sorry I was busy and could not find a time to write proper test cases for my pull request.

**Comment by ikalev** [comment]
Note that this does not solve all cases of #649 . Python 2 namespace packages (declared with setuptools or distutils) contain ``__init__.py`` files, which ``copy_into()`` might attempt to overwrite. This will obviously not pass our test for merge conflicts. The workaround on Python 2 is to use ``pkg_resources. declare_namespace()`` and enable ``preserve_egg_dir``, which hides shared namespace files in private egg folders.

**Comment by ikalev** [comment]
@msarahan I don't see these changes in the source tree at the moment. I deleted my fork after the merge, but this should be fine, right? I'm confused.

**Comment by msarahan** [comment]
@ikalev could you please resubmit this?  I don't know how, but I don't see it in the git history.  Nor do I see any force pushes that I would have overwritten it with...

**Comment by ikalev** [comment]
@msarahan Unfortunately I have deleted my fork of the repo, but I can try to extract a patch from this diff and prepare a new PR: https://github.com/conda/conda-build/pull/1090/files

**Comment by msarahan** [comment]
Sorry for the mess.  I can submit this PR for you, if you'd prefer.

**Comment by ikalev** [comment]
No problem. Here is the new PR: #1105.

**Pull request merged**
