### PR TITLE
Set build_platform for aid in cross compiling

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
Ping @mingwandroid

**Comment by jjhelmus** [comment]
Is the intention to have `build_platform` be a this be a pre-processor selector or an environment variable exported into the build environment?  

This PR does the former but the later seems like a useful feature.

**Comment by isuruf** [comment]
I wanted the former. For example along with https://github.com/conda/conda-build/pull/4011,
```
package:
  name: icu
requirements:
  build:
    - icu    # [build_platform != target_platform]
  run:
  host:
```

I can add this as a environment variable too.

**Comment by jjhelmus** [comment]
Thanks @isuruf.  These will need to be added to the docs at some point.  I created #4018 for this.

**Pull request merged**
