### PR TITLE
Fix sphinx warnings

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

There are some warnings/errors when building HTML docs. This PR fixes all those errors, including:

- Broken links
- Bad indentation on doc tree

Regards!

### CODE REVIEW

**Comment by rrigdon** [comment]
Hi Uilian, thanks for the edits. I'm a little confused about some of these, though. When I make the html, it shows all of the notes and warnings properly (see attached photo). I also couldn't tell what changes you made to the .. notes:: parts -- it looked like maybe you removed a trailing whitespace, but that doesn't seem to be affecting the notes on my html checks. What browser are you using? 
conda-build notes

**Comment by uilianries** [comment]
Hi @rrigdon !

I use Firefox 65.0.2 (64-bit) for Linux.

Maybe I should reset my changes and use vim to edit only what I need. Indeed my editor code (visual code) messed some parts of code, sorry about that.

Regards!

**Comment by rrigdon** [comment]
No worries! It looks like the edits should work so I'll go ahead and merge--I just wanted to confirm what may have been causing the errors. Thanks for contributing!

**Comment by uilianries** [comment]
Thanks!

Maybe you could think about adding some support for tags on PRs, like #docs #sanity ..., that way the CI will be able to run only specific tests.

Regards!

**Pull request merged**
